/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/NVIDIA/k8s-test-infra/pkg/gpu/mocknvml/bridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 6 "bridge_generated.go"

#include <stdlib.h>
#include <string.h>

typedef int nvmlReturn_t;
typedef void* nvmlDevice_t;

typedef struct nvmlPciInfo_st {
    char busIdLegacy[16];
    unsigned int domain;
    unsigned int bus;
    unsigned int device;
    unsigned int pciDeviceId;
    unsigned int pciSubSystemId;
    char busId[32];
} nvmlPciInfo_t;

typedef struct nvmlMemory_st {
    unsigned long long total;
    unsigned long long free;
    unsigned long long used;
} nvmlMemory_t;

typedef struct nvmlProcessInfo_st {
    unsigned int pid;
    unsigned long long usedGpuMemory;
} nvmlProcessInfo_t;

#define NVML_SUCCESS                    0
#define NVML_ERROR_UNINITIALIZED        1
#define NVML_ERROR_INVALID_ARGUMENT     2
#define NVML_ERROR_NOT_SUPPORTED        3
#define NVML_ERROR_INSUFFICIENT_SIZE    7
#define NVML_ERROR_UNKNOWN              999

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern nvmlReturn_t nvmlInit_v2(void);
extern nvmlReturn_t nvmlInitWithFlags(unsigned int flags);
extern nvmlReturn_t nvmlShutdown(void);
extern char* nvmlErrorString(nvmlReturn_t result);
extern nvmlReturn_t nvmlSystemGetDriverVersion(void* version, unsigned int length);
extern nvmlReturn_t nvmlSystemGetNVMLVersion(void* version, unsigned int length);
extern nvmlReturn_t nvmlSystemGetCudaDriverVersion(void* cudaDriverVersion);
extern nvmlReturn_t nvmlSystemGetCudaDriverVersion_v2(void* cudaDriverVersion);
extern nvmlReturn_t nvmlSystemGetProcessName(unsigned int pid, void* name, unsigned int length);
extern nvmlReturn_t nvmlSystemGetHicVersion(void* hwbcCount, void* hwbcEntries);
extern nvmlReturn_t nvmlSystemGetTopologyGpuSet(unsigned int cpuNumber, void* count, void* deviceArray);
extern nvmlReturn_t nvmlSystemGetDriverBranch(void* branchInfo, unsigned int length);
extern nvmlReturn_t nvmlUnitGetCount(void* unitCount);
extern nvmlReturn_t nvmlUnitGetHandleByIndex(unsigned int index, void* nvmlUnit);
extern nvmlReturn_t nvmlUnitGetUnitInfo(void* nvmlUnit, void* info);
extern nvmlReturn_t nvmlUnitGetLedState(void* nvmlUnit, void* state);
extern nvmlReturn_t nvmlUnitGetPsuInfo(void* nvmlUnit, void* psu);
extern nvmlReturn_t nvmlUnitGetTemperature(void* nvmlUnit, unsigned int _type, void* temp);
extern nvmlReturn_t nvmlUnitGetFanSpeedInfo(void* nvmlUnit, void* fanSpeeds);
extern nvmlReturn_t nvmlUnitGetDevices(void* nvmlUnit, void* deviceCount, void* devices);
extern nvmlReturn_t nvmlDeviceGetCount_v2(void* deviceCount);
extern nvmlReturn_t nvmlDeviceGetAttributes_v2(void* nvmlDevice, void* attributes);
extern nvmlReturn_t nvmlDeviceGetHandleByIndex_v2(unsigned int index, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetHandleBySerial(char* serial, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetHandleByUUID(char* uuid, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetHandleByUUIDV(void* uuid, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetHandleByPciBusId_v2(char* pciBusId, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetName(void* nvmlDevice, void* name, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetBrand(void* nvmlDevice, void* _type);
extern nvmlReturn_t nvmlDeviceGetIndex(void* nvmlDevice, void* index);
extern nvmlReturn_t nvmlDeviceGetSerial(void* nvmlDevice, void* serial, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetModuleId(void* nvmlDevice, void* moduleId);
extern nvmlReturn_t nvmlDeviceGetC2cModeInfoV(void* nvmlDevice, void* c2cModeInfo);
extern nvmlReturn_t nvmlDeviceGetMemoryAffinity(void* nvmlDevice, unsigned int nodeSetSize, void* nodeSet, void* scope);
extern nvmlReturn_t nvmlDeviceGetCpuAffinityWithinScope(void* nvmlDevice, unsigned int cpuSetSize, void* cpuSet, void* scope);
extern nvmlReturn_t nvmlDeviceGetCpuAffinity(void* nvmlDevice, unsigned int cpuSetSize, void* cpuSet);
extern nvmlReturn_t nvmlDeviceSetCpuAffinity(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceClearCpuAffinity(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetNumaNodeId(void* nvmlDevice, void* node);
extern nvmlReturn_t nvmlDeviceGetAddressingMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceGetRepairStatus(void* nvmlDevice, void* repairStatus);
extern nvmlReturn_t nvmlDeviceGetTopologyCommonAncestor(void* device1, void* device2, void* pathInfo);
extern nvmlReturn_t nvmlDeviceGetTopologyNearestGpus(void* nvmlDevice, void* level, void* count, void* deviceArray);
extern nvmlReturn_t nvmlDeviceGetP2PStatus(void* device1, void* device2, void* p2pIndex, void* p2pStatus);
extern nvmlReturn_t nvmlDeviceGetUUID(void* nvmlDevice, void* uuid, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetMinorNumber(void* nvmlDevice, void* minorNumber);
extern nvmlReturn_t nvmlDeviceGetBoardPartNumber(void* nvmlDevice, void* partNumber, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetInforomVersion(void* nvmlDevice, void* object, void* version, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetInforomImageVersion(void* nvmlDevice, void* version, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetInforomConfigurationChecksum(void* nvmlDevice, void* checksum);
extern nvmlReturn_t nvmlDeviceValidateInforom(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetLastBBXFlushTime(void* nvmlDevice, void* timestamp, void* durationUs);
extern nvmlReturn_t nvmlDeviceGetDisplayMode(void* nvmlDevice, void* display);
extern nvmlReturn_t nvmlDeviceGetDisplayActive(void* nvmlDevice, void* isActive);
extern nvmlReturn_t nvmlDeviceGetPersistenceMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceGetPciInfoExt(void* nvmlDevice, void* pci);
extern nvmlReturn_t nvmlDeviceGetPciInfo_v3(void* nvmlDevice, void* pci);
extern nvmlReturn_t nvmlDeviceGetMaxPcieLinkGeneration(void* nvmlDevice, void* maxLinkGen);
extern nvmlReturn_t nvmlDeviceGetGpuMaxPcieLinkGeneration(void* nvmlDevice, void* maxLinkGenDevice);
extern nvmlReturn_t nvmlDeviceGetMaxPcieLinkWidth(void* nvmlDevice, void* maxLinkWidth);
extern nvmlReturn_t nvmlDeviceGetCurrPcieLinkGeneration(void* nvmlDevice, void* currLinkGen);
extern nvmlReturn_t nvmlDeviceGetCurrPcieLinkWidth(void* nvmlDevice, void* currLinkWidth);
extern nvmlReturn_t nvmlDeviceGetPcieThroughput(void* nvmlDevice, void* counter, void* value);
extern nvmlReturn_t nvmlDeviceGetPcieReplayCounter(void* nvmlDevice, void* value);
extern nvmlReturn_t nvmlDeviceGetClockInfo(void* nvmlDevice, void* _type, void* clock);
extern nvmlReturn_t nvmlDeviceGetMaxClockInfo(void* nvmlDevice, void* _type, void* clock);
extern nvmlReturn_t nvmlDeviceGetGpcClkVfOffset(void* nvmlDevice, void* offset);
extern nvmlReturn_t nvmlDeviceGetApplicationsClock(void* nvmlDevice, void* clockType, void* clockMHz);
extern nvmlReturn_t nvmlDeviceGetDefaultApplicationsClock(void* nvmlDevice, void* clockType, void* clockMHz);
extern nvmlReturn_t nvmlDeviceGetClock(void* nvmlDevice, void* clockType, void* clockId, void* clockMHz);
extern nvmlReturn_t nvmlDeviceGetMaxCustomerBoostClock(void* nvmlDevice, void* clockType, void* clockMHz);
extern nvmlReturn_t nvmlDeviceGetSupportedMemoryClocks(void* nvmlDevice, void* count, void* clocksMHz);
extern nvmlReturn_t nvmlDeviceGetSupportedGraphicsClocks(void* nvmlDevice, unsigned int memoryClockMHz, void* count, void* clocksMHz);
extern nvmlReturn_t nvmlDeviceGetAutoBoostedClocksEnabled(void* nvmlDevice, void* isEnabled, void* defaultIsEnabled);
extern nvmlReturn_t nvmlDeviceGetFanSpeed(void* nvmlDevice, void* speed);
extern nvmlReturn_t nvmlDeviceGetFanSpeed_v2(void* nvmlDevice, unsigned int fan, void* speed);
extern nvmlReturn_t nvmlDeviceGetFanSpeedRPM(void* nvmlDevice, void* fanSpeed);
extern nvmlReturn_t nvmlDeviceGetTargetFanSpeed(void* nvmlDevice, unsigned int fan, void* targetSpeed);
extern nvmlReturn_t nvmlDeviceGetMinMaxFanSpeed(void* nvmlDevice, void* minSpeed, void* maxSpeed);
extern nvmlReturn_t nvmlDeviceGetFanControlPolicy_v2(void* nvmlDevice, unsigned int fan, void* policy);
extern nvmlReturn_t nvmlDeviceGetNumFans(void* nvmlDevice, void* numFans);
extern nvmlReturn_t nvmlDeviceGetTemperature(void* nvmlDevice, void* sensorType, void* temp);
extern nvmlReturn_t nvmlDeviceGetCoolerInfo(void* nvmlDevice, void* coolerInfo);
extern nvmlReturn_t nvmlDeviceGetTemperatureV(void* nvmlDevice, void* temperature);
extern nvmlReturn_t nvmlDeviceGetTemperatureThreshold(void* nvmlDevice, void* thresholdType, void* temp);
extern nvmlReturn_t nvmlDeviceGetMarginTemperature(void* nvmlDevice, void* marginTempInfo);
extern nvmlReturn_t nvmlDeviceGetThermalSettings(void* nvmlDevice, unsigned int sensorIndex, void* pThermalSettings);
extern nvmlReturn_t nvmlDeviceGetPerformanceState(void* nvmlDevice, void* pState);
extern nvmlReturn_t nvmlDeviceGetCurrentClocksEventReasons(void* nvmlDevice, void* clocksEventReasons);
extern nvmlReturn_t nvmlDeviceGetCurrentClocksThrottleReasons(void* nvmlDevice, void* clocksThrottleReasons);
extern nvmlReturn_t nvmlDeviceGetSupportedClocksEventReasons(void* nvmlDevice, void* supportedClocksEventReasons);
extern nvmlReturn_t nvmlDeviceGetSupportedClocksThrottleReasons(void* nvmlDevice, void* supportedClocksThrottleReasons);
extern nvmlReturn_t nvmlDeviceGetPowerState(void* nvmlDevice, void* pState);
extern nvmlReturn_t nvmlDeviceGetDynamicPstatesInfo(void* nvmlDevice, void* pDynamicPstatesInfo);
extern nvmlReturn_t nvmlDeviceGetMemClkVfOffset(void* nvmlDevice, void* offset);
extern nvmlReturn_t nvmlDeviceGetMinMaxClockOfPState(void* nvmlDevice, void* _type, void* pstate, void* minClockMHz, void* maxClockMHz);
extern nvmlReturn_t nvmlDeviceGetSupportedPerformanceStates(void* nvmlDevice, void* pstates, unsigned int size);
extern nvmlReturn_t nvmlDeviceGetGpcClkMinMaxVfOffset(void* nvmlDevice, void* minOffset, void* maxOffset);
extern nvmlReturn_t nvmlDeviceGetMemClkMinMaxVfOffset(void* nvmlDevice, void* minOffset, void* maxOffset);
extern nvmlReturn_t nvmlDeviceGetClockOffsets(void* nvmlDevice, void* info);
extern nvmlReturn_t nvmlDeviceSetClockOffsets(void* nvmlDevice, void* info);
extern nvmlReturn_t nvmlDeviceGetPerformanceModes(void* nvmlDevice, void* perfModes);
extern nvmlReturn_t nvmlDeviceGetCurrentClockFreqs(void* nvmlDevice, void* currentClockFreqs);
extern nvmlReturn_t nvmlDeviceGetPowerManagementMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceGetPowerManagementLimit(void* nvmlDevice, void* limit);
extern nvmlReturn_t nvmlDeviceGetPowerManagementLimitConstraints(void* nvmlDevice, void* minLimit, void* maxLimit);
extern nvmlReturn_t nvmlDeviceGetPowerManagementDefaultLimit(void* nvmlDevice, void* defaultLimit);
extern nvmlReturn_t nvmlDeviceGetPowerUsage(void* nvmlDevice, void* power);
extern nvmlReturn_t nvmlDeviceGetPowerMizerMode_v1(void* nvmlDevice, void* powerMizerMode);
extern nvmlReturn_t nvmlDeviceSetPowerMizerMode_v1(void* nvmlDevice, void* powerMizerMode);
extern nvmlReturn_t nvmlDeviceGetTotalEnergyConsumption(void* nvmlDevice, void* energy);
extern nvmlReturn_t nvmlDeviceGetEnforcedPowerLimit(void* nvmlDevice, void* limit);
extern nvmlReturn_t nvmlDeviceGetGpuOperationMode(void* nvmlDevice, void* current, void* pending);
extern nvmlReturn_t nvmlDeviceGetMemoryInfo(void* nvmlDevice, void* memory);
extern nvmlReturn_t nvmlDeviceGetMemoryInfo_v2(void* nvmlDevice, void* memory);
extern nvmlReturn_t nvmlDeviceGetComputeMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceGetCudaComputeCapability(void* nvmlDevice, void* major, void* minor);
extern nvmlReturn_t nvmlDeviceGetDramEncryptionMode(void* nvmlDevice, void* current, void* pending);
extern nvmlReturn_t nvmlDeviceSetDramEncryptionMode(void* nvmlDevice, void* dramEncryption);
extern nvmlReturn_t nvmlDeviceGetEccMode(void* nvmlDevice, void* current, void* pending);
extern nvmlReturn_t nvmlDeviceGetDefaultEccMode(void* nvmlDevice, void* defaultMode);
extern nvmlReturn_t nvmlDeviceGetBoardId(void* nvmlDevice, void* boardId);
extern nvmlReturn_t nvmlDeviceGetMultiGpuBoard(void* nvmlDevice, void* multiGpuBool);
extern nvmlReturn_t nvmlDeviceGetTotalEccErrors(void* nvmlDevice, void* errorType, void* counterType, void* eccCounts);
extern nvmlReturn_t nvmlDeviceGetDetailedEccErrors(void* nvmlDevice, void* errorType, void* counterType, void* eccCounts);
extern nvmlReturn_t nvmlDeviceGetMemoryErrorCounter(void* nvmlDevice, void* errorType, void* counterType, void* locationType, void* count);
extern nvmlReturn_t nvmlDeviceGetUtilizationRates(void* nvmlDevice, void* utilization);
extern nvmlReturn_t nvmlDeviceGetEncoderUtilization(void* nvmlDevice, void* utilization, void* samplingPeriodUs);
extern nvmlReturn_t nvmlDeviceGetEncoderCapacity(void* nvmlDevice, void* encoderQueryType, void* encoderCapacity);
extern nvmlReturn_t nvmlDeviceGetEncoderStats(void* nvmlDevice, void* sessionCount, void* averageFps, void* averageLatency);
extern nvmlReturn_t nvmlDeviceGetEncoderSessions(void* nvmlDevice, void* sessionCount, void* sessionInfos);
extern nvmlReturn_t nvmlDeviceGetDecoderUtilization(void* nvmlDevice, void* utilization, void* samplingPeriodUs);
extern nvmlReturn_t nvmlDeviceGetJpgUtilization(void* nvmlDevice, void* utilization, void* samplingPeriodUs);
extern nvmlReturn_t nvmlDeviceGetOfaUtilization(void* nvmlDevice, void* utilization, void* samplingPeriodUs);
extern nvmlReturn_t nvmlDeviceGetFBCStats(void* nvmlDevice, void* fbcStats);
extern nvmlReturn_t nvmlDeviceGetFBCSessions(void* nvmlDevice, void* sessionCount, void* sessionInfo);
extern nvmlReturn_t nvmlDeviceGetDriverModel_v2(void* nvmlDevice, void* current, void* pending);
extern nvmlReturn_t nvmlDeviceGetVbiosVersion(void* nvmlDevice, void* version, unsigned int length);
extern nvmlReturn_t nvmlDeviceGetBridgeChipInfo(void* nvmlDevice, void* bridgeHierarchy);
extern nvmlReturn_t nvmlDeviceGetComputeRunningProcesses_v3(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetGraphicsRunningProcesses_v3(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetMPSComputeRunningProcesses_v3(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetRunningProcessDetailList(void* nvmlDevice, void* plist);
extern nvmlReturn_t nvmlDeviceOnSameBoard(void* device1, void* device2, void* onSameBoard);
extern nvmlReturn_t nvmlDeviceGetAPIRestriction(void* nvmlDevice, void* apiType, void* isRestricted);
extern nvmlReturn_t nvmlDeviceGetSamples(void* nvmlDevice, void* _type, unsigned long long lastSeenTimeStamp, void* sampleValType, void* sampleCount, void* samples);
extern nvmlReturn_t nvmlDeviceGetBAR1MemoryInfo(void* nvmlDevice, void* bar1Memory);
extern nvmlReturn_t nvmlDeviceGetViolationStatus(void* nvmlDevice, void* perfPolicyType, void* violTime);
extern nvmlReturn_t nvmlDeviceGetIrqNum(void* nvmlDevice, void* irqNum);
extern nvmlReturn_t nvmlDeviceGetNumGpuCores(void* nvmlDevice, void* numCores);
extern nvmlReturn_t nvmlDeviceGetPowerSource(void* nvmlDevice, void* powerSource);
extern nvmlReturn_t nvmlDeviceGetMemoryBusWidth(void* nvmlDevice, void* busWidth);
extern nvmlReturn_t nvmlDeviceGetPcieLinkMaxSpeed(void* nvmlDevice, void* maxSpeed);
extern nvmlReturn_t nvmlDeviceGetPcieSpeed(void* nvmlDevice, void* pcieSpeed);
extern nvmlReturn_t nvmlDeviceGetAdaptiveClockInfoStatus(void* nvmlDevice, void* adaptiveClockStatus);
extern nvmlReturn_t nvmlDeviceGetBusType(void* nvmlDevice, void* _type);
extern nvmlReturn_t nvmlDeviceGetGpuFabricInfo(void* nvmlDevice, void* gpuFabricInfo);
extern nvmlReturn_t nvmlDeviceGetGpuFabricInfoV(void* nvmlDevice, void* gpuFabricInfo);
extern nvmlReturn_t nvmlSystemGetConfComputeCapabilities(void* capabilities);
extern nvmlReturn_t nvmlSystemGetConfComputeState(void* state);
extern nvmlReturn_t nvmlDeviceGetConfComputeMemSizeInfo(void* nvmlDevice, void* memInfo);
extern nvmlReturn_t nvmlSystemGetConfComputeGpusReadyState(void* isAcceptingWork);
extern nvmlReturn_t nvmlDeviceGetConfComputeProtectedMemoryUsage(void* nvmlDevice, void* memory);
extern nvmlReturn_t nvmlDeviceGetConfComputeGpuCertificate(void* nvmlDevice, void* gpuCert);
extern nvmlReturn_t nvmlDeviceGetConfComputeGpuAttestationReport(void* nvmlDevice, void* gpuAtstReport);
extern nvmlReturn_t nvmlSystemGetConfComputeKeyRotationThresholdInfo(void* pKeyRotationThrInfo);
extern nvmlReturn_t nvmlDeviceSetConfComputeUnprotectedMemSize(void* nvmlDevice, unsigned long long sizeKiB);
extern nvmlReturn_t nvmlSystemSetConfComputeGpusReadyState(unsigned int isAcceptingWork);
extern nvmlReturn_t nvmlSystemSetConfComputeKeyRotationThresholdInfo(void* pKeyRotationThrInfo);
extern nvmlReturn_t nvmlSystemGetConfComputeSettings(void* settings);
extern nvmlReturn_t nvmlDeviceGetGspFirmwareVersion(void* nvmlDevice, void* version);
extern nvmlReturn_t nvmlDeviceGetGspFirmwareMode(void* nvmlDevice, void* isEnabled, void* defaultMode);
extern nvmlReturn_t nvmlDeviceGetSramEccErrorStatus(void* nvmlDevice, void* status);
extern nvmlReturn_t nvmlDeviceSetPowerManagementLimit_v2(void* nvmlDevice, void* powerValue);
extern nvmlReturn_t nvmlDeviceGetAccountingMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceGetAccountingStats(void* nvmlDevice, unsigned int pid, void* stats);
extern nvmlReturn_t nvmlDeviceGetAccountingPids(void* nvmlDevice, void* count, void* pids);
extern nvmlReturn_t nvmlDeviceGetAccountingBufferSize(void* nvmlDevice, void* bufferSize);
extern nvmlReturn_t nvmlDeviceGetRetiredPages(void* nvmlDevice, void* cause, void* pageCount, void* addresses);
extern nvmlReturn_t nvmlDeviceGetRetiredPages_v2(void* nvmlDevice, void* cause, void* pageCount, void* addresses, void* timestamps);
extern nvmlReturn_t nvmlDeviceGetRetiredPagesPendingStatus(void* nvmlDevice, void* isPending);
extern nvmlReturn_t nvmlDeviceGetRemappedRows(void* nvmlDevice, void* corrRows, void* uncRows, void* isPending, void* failureOccurred);
extern nvmlReturn_t nvmlDeviceGetRowRemapperHistogram(void* nvmlDevice, void* values);
extern nvmlReturn_t nvmlDeviceGetArchitecture(void* nvmlDevice, void* arch);
extern nvmlReturn_t nvmlDeviceGetClkMonStatus(void* nvmlDevice, void* status);
extern nvmlReturn_t nvmlDeviceGetProcessUtilization(void* nvmlDevice, void* utilization, void* processSamplesCount, unsigned long long lastSeenTimeStamp);
extern nvmlReturn_t nvmlDeviceGetProcessesUtilizationInfo(void* nvmlDevice, void* procesesUtilInfo);
extern nvmlReturn_t nvmlDeviceGetPlatformInfo(void* nvmlDevice, void* platformInfo);
extern nvmlReturn_t nvmlDeviceGetPdi(void* nvmlDevice, void* pdi);
extern nvmlReturn_t nvmlUnitSetLedState(void* nvmlUnit, void* color);
extern nvmlReturn_t nvmlDeviceSetPersistenceMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceSetComputeMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceSetEccMode(void* nvmlDevice, void* ecc);
extern nvmlReturn_t nvmlDeviceClearEccErrorCounts(void* nvmlDevice, void* counterType);
extern nvmlReturn_t nvmlDeviceSetDriverModel(void* nvmlDevice, void* driverModel, unsigned int flags);
extern nvmlReturn_t nvmlDeviceSetGpuLockedClocks(void* nvmlDevice, unsigned int minGpuClockMHz, unsigned int maxGpuClockMHz);
extern nvmlReturn_t nvmlDeviceResetGpuLockedClocks(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceSetMemoryLockedClocks(void* nvmlDevice, unsigned int minMemClockMHz, unsigned int maxMemClockMHz);
extern nvmlReturn_t nvmlDeviceResetMemoryLockedClocks(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceSetApplicationsClocks(void* nvmlDevice, unsigned int memClockMHz, unsigned int graphicsClockMHz);
extern nvmlReturn_t nvmlDeviceResetApplicationsClocks(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceSetAutoBoostedClocksEnabled(void* nvmlDevice, void* enabled);
extern nvmlReturn_t nvmlDeviceSetDefaultAutoBoostedClocksEnabled(void* nvmlDevice, void* enabled, unsigned int flags);
extern nvmlReturn_t nvmlDeviceSetDefaultFanSpeed_v2(void* nvmlDevice, unsigned int fan);
extern nvmlReturn_t nvmlDeviceSetFanControlPolicy(void* nvmlDevice, unsigned int fan, void* policy);
extern nvmlReturn_t nvmlDeviceSetTemperatureThreshold(void* nvmlDevice, void* thresholdType, void* temp);
extern nvmlReturn_t nvmlDeviceSetPowerManagementLimit(void* nvmlDevice, unsigned int limit);
extern nvmlReturn_t nvmlDeviceSetGpuOperationMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceSetAPIRestriction(void* nvmlDevice, void* apiType, void* isRestricted);
extern nvmlReturn_t nvmlDeviceSetFanSpeed_v2(void* nvmlDevice, unsigned int fan, unsigned int speed);
extern nvmlReturn_t nvmlDeviceSetGpcClkVfOffset(void* nvmlDevice, int offset);
extern nvmlReturn_t nvmlDeviceSetMemClkVfOffset(void* nvmlDevice, int offset);
extern nvmlReturn_t nvmlDeviceSetAccountingMode(void* nvmlDevice, void* mode);
extern nvmlReturn_t nvmlDeviceClearAccountingPids(void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetNvLinkState(void* nvmlDevice, unsigned int link, void* isActive);
extern nvmlReturn_t nvmlDeviceGetNvLinkVersion(void* nvmlDevice, unsigned int link, void* version);
extern nvmlReturn_t nvmlDeviceGetNvLinkCapability(void* nvmlDevice, unsigned int link, void* capability, void* capResult);
extern nvmlReturn_t nvmlDeviceGetNvLinkRemotePciInfo_v2(void* nvmlDevice, unsigned int link, void* pci);
extern nvmlReturn_t nvmlDeviceGetNvLinkErrorCounter(void* nvmlDevice, unsigned int link, void* counter, void* counterValue);
extern nvmlReturn_t nvmlDeviceResetNvLinkErrorCounters(void* nvmlDevice, unsigned int link);
extern nvmlReturn_t nvmlDeviceSetNvLinkUtilizationControl(void* nvmlDevice, unsigned int link, unsigned int counter, void* control, unsigned int reset);
extern nvmlReturn_t nvmlDeviceGetNvLinkUtilizationControl(void* nvmlDevice, unsigned int link, unsigned int counter, void* control);
extern nvmlReturn_t nvmlDeviceGetNvLinkUtilizationCounter(void* nvmlDevice, unsigned int link, unsigned int counter, void* rxcounter, void* txcounter);
extern nvmlReturn_t nvmlDeviceFreezeNvLinkUtilizationCounter(void* nvmlDevice, unsigned int link, unsigned int counter, void* freeze);
extern nvmlReturn_t nvmlDeviceResetNvLinkUtilizationCounter(void* nvmlDevice, unsigned int link, unsigned int counter);
extern nvmlReturn_t nvmlDeviceGetNvLinkRemoteDeviceType(void* nvmlDevice, unsigned int link, void* pNvLinkDeviceType);
extern nvmlReturn_t nvmlDeviceSetNvLinkDeviceLowPowerThreshold(void* nvmlDevice, void* info);
extern nvmlReturn_t nvmlSystemSetNvlinkBwMode(unsigned int nvlinkBwMode);
extern nvmlReturn_t nvmlSystemGetNvlinkBwMode(void* nvlinkBwMode);
extern nvmlReturn_t nvmlDeviceGetNvlinkSupportedBwModes(void* nvmlDevice, void* supportedBwMode);
extern nvmlReturn_t nvmlDeviceGetNvlinkBwMode(void* nvmlDevice, void* getBwMode);
extern nvmlReturn_t nvmlDeviceSetNvlinkBwMode(void* nvmlDevice, void* setBwMode);
extern nvmlReturn_t nvmlDeviceGetNvLinkInfo(void* nvmlDevice, void* info);
extern nvmlReturn_t nvmlEventSetCreate(void* set);
extern nvmlReturn_t nvmlDeviceRegisterEvents(void* nvmlDevice, unsigned long long eventTypes, void* set);
extern nvmlReturn_t nvmlDeviceGetSupportedEventTypes(void* nvmlDevice, void* eventTypes);
extern nvmlReturn_t nvmlEventSetWait_v2(void* set, void* data, unsigned int timeoutms);
extern nvmlReturn_t nvmlEventSetFree(void* set);
extern nvmlReturn_t nvmlSystemEventSetCreate(void* request);
extern nvmlReturn_t nvmlSystemEventSetFree(void* request);
extern nvmlReturn_t nvmlSystemRegisterEvents(void* request);
extern nvmlReturn_t nvmlSystemEventSetWait(void* request);
extern nvmlReturn_t nvmlDeviceModifyDrainState(void* pciInfo, void* newState);
extern nvmlReturn_t nvmlDeviceQueryDrainState(void* pciInfo, void* currentState);
extern nvmlReturn_t nvmlDeviceRemoveGpu_v2(void* pciInfo, void* gpuState, void* linkState);
extern nvmlReturn_t nvmlDeviceDiscoverGpus(void* pciInfo);
extern nvmlReturn_t nvmlDeviceGetFieldValues(void* nvmlDevice, int valuesCount, void* values);
extern nvmlReturn_t nvmlDeviceClearFieldValues(void* nvmlDevice, int valuesCount, void* values);
extern nvmlReturn_t nvmlDeviceGetVirtualizationMode(void* nvmlDevice, void* pVirtualMode);
extern nvmlReturn_t nvmlDeviceGetHostVgpuMode(void* nvmlDevice, void* pHostVgpuMode);
extern nvmlReturn_t nvmlDeviceSetVirtualizationMode(void* nvmlDevice, void* virtualMode);
extern nvmlReturn_t nvmlDeviceGetVgpuHeterogeneousMode(void* nvmlDevice, void* pHeterogeneousMode);
extern nvmlReturn_t nvmlDeviceSetVgpuHeterogeneousMode(void* nvmlDevice, void* pHeterogeneousMode);
extern nvmlReturn_t nvmlVgpuInstanceGetPlacementId(void* nvmlVgpuInstance, void* pPlacement);
extern nvmlReturn_t nvmlDeviceGetVgpuTypeSupportedPlacements(void* nvmlDevice, void* nvmlVgpuTypeId, void* pPlacementList);
extern nvmlReturn_t nvmlDeviceGetVgpuTypeCreatablePlacements(void* nvmlDevice, void* nvmlVgpuTypeId, void* pPlacementList);
extern nvmlReturn_t nvmlVgpuTypeGetGspHeapSize(void* nvmlVgpuTypeId, void* gspHeapSize);
extern nvmlReturn_t nvmlVgpuTypeGetFbReservation(void* nvmlVgpuTypeId, void* fbReservation);
extern nvmlReturn_t nvmlVgpuInstanceGetRuntimeStateSize(void* nvmlVgpuInstance, void* pState);
extern nvmlReturn_t nvmlDeviceSetVgpuCapabilities(void* nvmlDevice, void* capability, void* state);
extern nvmlReturn_t nvmlDeviceGetGridLicensableFeatures_v4(void* nvmlDevice, void* pGridLicensableFeatures);
extern nvmlReturn_t nvmlGetVgpuDriverCapabilities(void* capability, void* capResult);
extern nvmlReturn_t nvmlDeviceGetVgpuCapabilities(void* nvmlDevice, void* capability, void* capResult);
extern nvmlReturn_t nvmlDeviceGetSupportedVgpus(void* nvmlDevice, void* vgpuCount, void* vgpuTypeIds);
extern nvmlReturn_t nvmlDeviceGetCreatableVgpus(void* nvmlDevice, void* vgpuCount, void* vgpuTypeIds);
extern nvmlReturn_t nvmlVgpuTypeGetClass(void* nvmlVgpuTypeId, void* vgpuTypeClass, void* size);
extern nvmlReturn_t nvmlVgpuTypeGetName(void* nvmlVgpuTypeId, void* vgpuTypeName, void* size);
extern nvmlReturn_t nvmlVgpuTypeGetGpuInstanceProfileId(void* nvmlVgpuTypeId, void* gpuInstanceProfileId);
extern nvmlReturn_t nvmlVgpuTypeGetDeviceID(void* nvmlVgpuTypeId, void* deviceID, void* subsystemID);
extern nvmlReturn_t nvmlVgpuTypeGetFramebufferSize(void* nvmlVgpuTypeId, void* fbSize);
extern nvmlReturn_t nvmlVgpuTypeGetNumDisplayHeads(void* nvmlVgpuTypeId, void* numDisplayHeads);
extern nvmlReturn_t nvmlVgpuTypeGetResolution(void* nvmlVgpuTypeId, unsigned int displayIndex, void* xdim, void* ydim);
extern nvmlReturn_t nvmlVgpuTypeGetLicense(void* nvmlVgpuTypeId, void* vgpuTypeLicenseString, unsigned int size);
extern nvmlReturn_t nvmlVgpuTypeGetFrameRateLimit(void* nvmlVgpuTypeId, void* frameRateLimit);
extern nvmlReturn_t nvmlVgpuTypeGetMaxInstances(void* nvmlDevice, void* nvmlVgpuTypeId, void* vgpuInstanceCount);
extern nvmlReturn_t nvmlVgpuTypeGetMaxInstancesPerVm(void* nvmlVgpuTypeId, void* vgpuInstanceCountPerVm);
extern nvmlReturn_t nvmlVgpuTypeGetBAR1Info(void* nvmlVgpuTypeId, void* bar1Info);
extern nvmlReturn_t nvmlDeviceGetActiveVgpus(void* nvmlDevice, void* vgpuCount, void* vgpuInstances);
extern nvmlReturn_t nvmlVgpuInstanceGetVmID(void* nvmlVgpuInstance, void* vmId, unsigned int size, void* vmIdType);
extern nvmlReturn_t nvmlVgpuInstanceGetUUID(void* nvmlVgpuInstance, void* uuid, unsigned int size);
extern nvmlReturn_t nvmlVgpuInstanceGetVmDriverVersion(void* nvmlVgpuInstance, void* version, unsigned int length);
extern nvmlReturn_t nvmlVgpuInstanceGetFbUsage(void* nvmlVgpuInstance, void* fbUsage);
extern nvmlReturn_t nvmlVgpuInstanceGetLicenseStatus(void* nvmlVgpuInstance, void* licensed);
extern nvmlReturn_t nvmlVgpuInstanceGetType(void* nvmlVgpuInstance, void* nvmlVgpuTypeId);
extern nvmlReturn_t nvmlVgpuInstanceGetFrameRateLimit(void* nvmlVgpuInstance, void* frameRateLimit);
extern nvmlReturn_t nvmlVgpuInstanceGetEccMode(void* nvmlVgpuInstance, void* eccMode);
extern nvmlReturn_t nvmlVgpuInstanceGetEncoderCapacity(void* nvmlVgpuInstance, void* encoderCapacity);
extern nvmlReturn_t nvmlVgpuInstanceSetEncoderCapacity(void* nvmlVgpuInstance, unsigned int encoderCapacity);
extern nvmlReturn_t nvmlVgpuInstanceGetEncoderStats(void* nvmlVgpuInstance, void* sessionCount, void* averageFps, void* averageLatency);
extern nvmlReturn_t nvmlVgpuInstanceGetEncoderSessions(void* nvmlVgpuInstance, void* sessionCount, void* sessionInfo);
extern nvmlReturn_t nvmlVgpuInstanceGetFBCStats(void* nvmlVgpuInstance, void* fbcStats);
extern nvmlReturn_t nvmlVgpuInstanceGetFBCSessions(void* nvmlVgpuInstance, void* sessionCount, void* sessionInfo);
extern nvmlReturn_t nvmlVgpuInstanceGetGpuInstanceId(void* nvmlVgpuInstance, void* gpuInstanceId);
extern nvmlReturn_t nvmlVgpuInstanceGetGpuPciId(void* nvmlVgpuInstance, void* vgpuPciId, void* length);
extern nvmlReturn_t nvmlVgpuTypeGetCapabilities(void* nvmlVgpuTypeId, void* capability, void* capResult);
extern nvmlReturn_t nvmlVgpuInstanceGetMdevUUID(void* nvmlVgpuInstance, void* mdevUuid, unsigned int size);
extern nvmlReturn_t nvmlGpuInstanceGetCreatableVgpus(void* nvmlGpuInstance, void* pVgpus);
extern nvmlReturn_t nvmlVgpuTypeGetMaxInstancesPerGpuInstance(void* pMaxInstance);
extern nvmlReturn_t nvmlGpuInstanceGetActiveVgpus(void* nvmlGpuInstance, void* pVgpuInstanceInfo);
extern nvmlReturn_t nvmlGpuInstanceSetVgpuSchedulerState(void* nvmlGpuInstance, void* pScheduler);
extern nvmlReturn_t nvmlGpuInstanceGetVgpuSchedulerState(void* nvmlGpuInstance, void* pSchedulerStateInfo);
extern nvmlReturn_t nvmlGpuInstanceGetVgpuSchedulerLog(void* nvmlGpuInstance, void* pSchedulerLogInfo);
extern nvmlReturn_t nvmlGpuInstanceGetVgpuTypeCreatablePlacements(void* nvmlGpuInstance, void* pCreatablePlacementInfo);
extern nvmlReturn_t nvmlGpuInstanceGetVgpuHeterogeneousMode(void* nvmlGpuInstance, void* pHeterogeneousMode);
extern nvmlReturn_t nvmlGpuInstanceSetVgpuHeterogeneousMode(void* nvmlGpuInstance, void* pHeterogeneousMode);
extern nvmlReturn_t nvmlVgpuInstanceGetMetadata(void* nvmlVgpuInstance, void* nvmlVgpuMetadata, void* bufferSize);
extern nvmlReturn_t nvmlDeviceGetVgpuMetadata(void* nvmlDevice, void* pgpuMetadata, void* bufferSize);
extern nvmlReturn_t nvmlGetVgpuCompatibility(void* nvmlVgpuMetadata, void* pgpuMetadata, void* compatibilityInfo);
extern nvmlReturn_t nvmlDeviceGetPgpuMetadataString(void* nvmlDevice, void* pgpuMetadata, void* bufferSize);
extern nvmlReturn_t nvmlDeviceGetVgpuSchedulerLog(void* nvmlDevice, void* pSchedulerLog);
extern nvmlReturn_t nvmlDeviceGetVgpuSchedulerState(void* nvmlDevice, void* pSchedulerState);
extern nvmlReturn_t nvmlDeviceGetVgpuSchedulerCapabilities(void* nvmlDevice, void* pCapabilities);
extern nvmlReturn_t nvmlDeviceSetVgpuSchedulerState(void* nvmlDevice, void* pSchedulerState);
extern nvmlReturn_t nvmlGetVgpuVersion(void* supported, void* current);
extern nvmlReturn_t nvmlSetVgpuVersion(void* vgpuVersion);
extern nvmlReturn_t nvmlDeviceGetVgpuUtilization(void* nvmlDevice, unsigned long long lastSeenTimeStamp, void* sampleValType, void* vgpuInstanceSamplesCount, void* utilizationSamples);
extern nvmlReturn_t nvmlDeviceGetVgpuInstancesUtilizationInfo(void* nvmlDevice, void* vgpuUtilInfo);
extern nvmlReturn_t nvmlDeviceGetVgpuProcessUtilization(void* nvmlDevice, unsigned long long lastSeenTimeStamp, void* vgpuProcessSamplesCount, void* utilizationSamples);
extern nvmlReturn_t nvmlDeviceGetVgpuProcessesUtilizationInfo(void* nvmlDevice, void* vgpuProcUtilInfo);
extern nvmlReturn_t nvmlVgpuInstanceGetAccountingMode(void* nvmlVgpuInstance, void* mode);
extern nvmlReturn_t nvmlVgpuInstanceGetAccountingPids(void* nvmlVgpuInstance, void* count, void* pids);
extern nvmlReturn_t nvmlVgpuInstanceGetAccountingStats(void* nvmlVgpuInstance, unsigned int pid, void* stats);
extern nvmlReturn_t nvmlVgpuInstanceClearAccountingPids(void* nvmlVgpuInstance);
extern nvmlReturn_t nvmlVgpuInstanceGetLicenseInfo_v2(void* nvmlVgpuInstance, void* licenseInfo);
extern nvmlReturn_t nvmlGetExcludedDeviceCount(void* deviceCount);
extern nvmlReturn_t nvmlGetExcludedDeviceInfoByIndex(unsigned int index, void* info);
extern nvmlReturn_t nvmlDeviceReadWritePRM_v1(void* nvmlDevice, void* buffer);
extern nvmlReturn_t nvmlDeviceSetMigMode(void* nvmlDevice, unsigned int mode, void* activationStatus);
extern nvmlReturn_t nvmlDeviceGetMigMode(void* nvmlDevice, void* currentMode, void* pendingMode);
extern nvmlReturn_t nvmlDeviceGetGpuInstanceProfileInfo(void* nvmlDevice, unsigned int profile, void* info);
extern nvmlReturn_t nvmlDeviceGetGpuInstanceProfileInfoV(void* nvmlDevice, unsigned int profile, void* info);
extern nvmlReturn_t nvmlDeviceGetGpuInstanceProfileInfoByIdV(void* nvmlDevice, unsigned int profileId, void* info);
extern nvmlReturn_t nvmlDeviceGetGpuInstancePossiblePlacements_v2(void* nvmlDevice, unsigned int profileId, void* placements, void* count);
extern nvmlReturn_t nvmlDeviceGetGpuInstanceRemainingCapacity(void* nvmlDevice, unsigned int profileId, void* count);
extern nvmlReturn_t nvmlDeviceCreateGpuInstance(void* nvmlDevice, unsigned int profileId, void* nvmlGpuInstance);
extern nvmlReturn_t nvmlDeviceCreateGpuInstanceWithPlacement(void* nvmlDevice, unsigned int profileId, void* placement, void* nvmlGpuInstance);
extern nvmlReturn_t nvmlGpuInstanceDestroy(void* nvmlGpuInstance);
extern nvmlReturn_t nvmlDeviceGetGpuInstances(void* nvmlDevice, unsigned int profileId, void* gpuInstances, void* count);
extern nvmlReturn_t nvmlDeviceGetGpuInstanceById(void* nvmlDevice, unsigned int id, void* nvmlGpuInstance);
extern nvmlReturn_t nvmlGpuInstanceGetInfo(void* nvmlGpuInstance, void* info);
extern nvmlReturn_t nvmlGpuInstanceGetComputeInstanceProfileInfo(void* nvmlGpuInstance, unsigned int profile, unsigned int engProfile, void* info);
extern nvmlReturn_t nvmlGpuInstanceGetComputeInstanceProfileInfoV(void* nvmlGpuInstance, unsigned int profile, unsigned int engProfile, void* info);
extern nvmlReturn_t nvmlGpuInstanceGetComputeInstanceRemainingCapacity(void* nvmlGpuInstance, unsigned int profileId, void* count);
extern nvmlReturn_t nvmlGpuInstanceGetComputeInstancePossiblePlacements(void* nvmlGpuInstance, unsigned int profileId, void* placements, void* count);
extern nvmlReturn_t nvmlGpuInstanceCreateComputeInstance(void* nvmlGpuInstance, unsigned int profileId, void* nvmlComputeInstance);
extern nvmlReturn_t nvmlGpuInstanceCreateComputeInstanceWithPlacement(void* nvmlGpuInstance, unsigned int profileId, void* placement, void* nvmlComputeInstance);
extern nvmlReturn_t nvmlComputeInstanceDestroy(void* nvmlComputeInstance);
extern nvmlReturn_t nvmlGpuInstanceGetComputeInstances(void* nvmlGpuInstance, unsigned int profileId, void* computeInstances, void* count);
extern nvmlReturn_t nvmlGpuInstanceGetComputeInstanceById(void* nvmlGpuInstance, unsigned int id, void* nvmlComputeInstance);
extern nvmlReturn_t nvmlComputeInstanceGetInfo_v2(void* nvmlComputeInstance, void* info);
extern nvmlReturn_t nvmlDeviceIsMigDeviceHandle(void* nvmlDevice, void* isMigDevice);
extern nvmlReturn_t nvmlDeviceGetGpuInstanceId(void* nvmlDevice, void* id);
extern nvmlReturn_t nvmlDeviceGetComputeInstanceId(void* nvmlDevice, void* id);
extern nvmlReturn_t nvmlDeviceGetMaxMigDeviceCount(void* nvmlDevice, void* count);
extern nvmlReturn_t nvmlDeviceGetMigDeviceHandleByIndex(void* nvmlDevice, unsigned int index, void* migDevice);
extern nvmlReturn_t nvmlDeviceGetDeviceHandleFromMigDeviceHandle(void* migDevice, void* nvmlDevice);
extern nvmlReturn_t nvmlGpmMetricsGet(void* metricsGet);
extern nvmlReturn_t nvmlGpmSampleFree(void* nvmlGpmSample);
extern nvmlReturn_t nvmlGpmSampleAlloc(void* nvmlGpmSample);
extern nvmlReturn_t nvmlGpmSampleGet(void* nvmlDevice, void* nvmlGpmSample);
extern nvmlReturn_t nvmlGpmMigSampleGet(void* nvmlDevice, unsigned int gpuInstanceId, void* nvmlGpmSample);
extern nvmlReturn_t nvmlGpmQueryDeviceSupport(void* nvmlDevice, void* gpmSupport);
extern nvmlReturn_t nvmlGpmQueryIfStreamingEnabled(void* nvmlDevice, void* state);
extern nvmlReturn_t nvmlGpmSetStreamingEnabled(void* nvmlDevice, unsigned int state);
extern nvmlReturn_t nvmlDeviceGetCapabilities(void* nvmlDevice, void* caps);
extern nvmlReturn_t nvmlDeviceWorkloadPowerProfileGetProfilesInfo(void* nvmlDevice, void* profilesInfo);
extern nvmlReturn_t nvmlDeviceWorkloadPowerProfileGetCurrentProfiles(void* nvmlDevice, void* currentProfiles);
extern nvmlReturn_t nvmlDeviceWorkloadPowerProfileSetRequestedProfiles(void* nvmlDevice, void* requestedProfiles);
extern nvmlReturn_t nvmlDeviceWorkloadPowerProfileClearRequestedProfiles(void* nvmlDevice, void* requestedProfiles);
extern nvmlReturn_t nvmlDevicePowerSmoothingActivatePresetProfile(void* nvmlDevice, void* profile);
extern nvmlReturn_t nvmlDevicePowerSmoothingUpdatePresetProfileParam(void* nvmlDevice, void* profile);
extern nvmlReturn_t nvmlDevicePowerSmoothingSetState(void* nvmlDevice, void* state);
extern nvmlReturn_t nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts(void* nvmlDevice, void* errorCounts);
extern nvmlReturn_t nvmlInit_v1(void);
extern nvmlReturn_t nvmlDeviceGetCount_v1(void* deviceCount);
extern nvmlReturn_t nvmlDeviceGetHandleByIndex_v1(unsigned int index, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetHandleByPciBusId_v1(char* pciBusId, void* nvmlDevice);
extern nvmlReturn_t nvmlDeviceGetPciInfo_v1(void* nvmlDevice, void* pci);
extern nvmlReturn_t nvmlDeviceGetPciInfo_v2(void* nvmlDevice, void* pci);
extern nvmlReturn_t nvmlDeviceGetNvLinkRemotePciInfo_v1(void* nvmlDevice, unsigned int link, void* pci);
extern nvmlReturn_t nvmlDeviceGetGridLicensableFeatures_v1(void* nvmlDevice, void* pGridLicensableFeatures);
extern nvmlReturn_t nvmlDeviceGetGridLicensableFeatures_v2(void* nvmlDevice, void* pGridLicensableFeatures);
extern nvmlReturn_t nvmlDeviceGetGridLicensableFeatures_v3(void* nvmlDevice, void* pGridLicensableFeatures);
extern nvmlReturn_t nvmlDeviceRemoveGpu_v1(void* pciInfo);
extern nvmlReturn_t nvmlEventSetWait_v1(void* set, void* data, unsigned int timeoutms);
extern nvmlReturn_t nvmlDeviceGetAttributes_v1(void* nvmlDevice, void* attributes);
extern nvmlReturn_t nvmlComputeInstanceGetInfo_v1(void* nvmlComputeInstance, void* info);
extern nvmlReturn_t nvmlDeviceGetComputeRunningProcesses_v1(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetComputeRunningProcesses_v2(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetGraphicsRunningProcesses_v1(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetGraphicsRunningProcesses_v2(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetMPSComputeRunningProcesses_v1(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetMPSComputeRunningProcesses_v2(void* nvmlDevice, void* infoCount, void* infos);
extern nvmlReturn_t nvmlDeviceGetGpuInstancePossiblePlacements_v1(void* nvmlDevice, unsigned int profileId, void* placements, void* count);
extern nvmlReturn_t nvmlVgpuInstanceGetLicenseInfo_v1(void* nvmlVgpuInstance, void* licenseInfo);
extern nvmlReturn_t nvmlDeviceGetDriverModel_v1(void* nvmlDevice, void* current, void* pending);

#ifdef __cplusplus
}
#endif
