# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["**.go", "**.h", "**.yaml", "**.yml", "**.sh", "**.toml", "Makefile", "Dockerfile"]
SPDX-FileCopyrightText = "Copyright 2024-2026 NVIDIA CORPORATION"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["CODE_OF_CONDUCT.md"]
SPDX-FileCopyrightText = "Copyright Contributors to the Contributor Covenant project"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**.md"]
SPDX-FileCopyrightText = "Copyright 2024-2026 NVIDIA CORPORATION"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["go.sum", "vendor/**", ".gitignore", ".editorconfig"]
SPDX-FileCopyrightText = "Copyright 2024-2026 NVIDIA CORPORATION"
SPDX-License-Identifier = "Apache-2.0"
