# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
apiVersion: mokka.nvidia.com/v1alpha1
kind: SGPUInventory
metadata:
  name: example
spec:
  rackGroups:
    - id: compute
      count: 1
      profileRef:
        name: example-a100
      placement:
        nodeSelector:
          matchLabels:
            mokka.nvidia.com/pool: example
