// Code generated by cmd/generate-bridge. DO NOT EDIT.
// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.

package main

/*
#include <stdlib.h>
#include <string.h>

typedef int nvmlReturn_t;
typedef void* nvmlDevice_t;

typedef struct nvmlPciInfo_st {
    char busIdLegacy[16];
    unsigned int domain;
    unsigned int bus;
    unsigned int device;
    unsigned int pciDeviceId;
    unsigned int pciSubSystemId;
    char busId[32];
} nvmlPciInfo_t;

typedef struct nvmlMemory_st {
    unsigned long long total;
    unsigned long long free;
    unsigned long long used;
} nvmlMemory_t;

typedef struct nvmlProcessInfo_st {
    unsigned int pid;
    unsigned long long usedGpuMemory;
} nvmlProcessInfo_t;

#define NVML_SUCCESS                    0
#define NVML_ERROR_UNINITIALIZED        1
#define NVML_ERROR_INVALID_ARGUMENT     2
#define NVML_ERROR_NOT_SUPPORTED        3
#define NVML_ERROR_INSUFFICIENT_SIZE    7
#define NVML_ERROR_UNKNOWN              999
*/
import "C"
import (
	"sync"
	"unsafe"

	"github.com/NVIDIA/go-nvml/pkg/nvml"
	"github.com/NVIDIA/k8s-test-infra/pkg/gpu/mocknvml/engine"
)

// errorStringCache caches C strings for nvmlErrorString to avoid memory leaks.
// Real NVML returns static strings, so caching matches expected behavior.
var (
	errorStringCache   = make(map[nvml.Return]*C.char)
	errorStringCacheMu sync.Mutex
)

func main() {
	// Required for buildmode=c-shared
}

func toReturn(ret nvml.Return) C.nvmlReturn_t {
	return C.nvmlReturn_t(ret)
}

func goStringToC(s string, buf *C.char, length C.uint) C.nvmlReturn_t {
	if buf == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	if len(s)+1 > int(length) {
		return C.NVML_ERROR_INSUFFICIENT_SIZE
	}
	cStr := C.CString(s)
	defer C.free(unsafe.Pointer(cStr))
	C.strcpy(buf, cStr)
	return C.NVML_SUCCESS
}

//export nvmlInit_v2
func nvmlInit_v2() C.nvmlReturn_t {
	ret := engine.GetEngine().Init()
	return toReturn(ret)
}

//export nvmlInitWithFlags
func nvmlInitWithFlags(flags C.uint) C.nvmlReturn_t {
	ret := engine.GetEngine().Init()
	return toReturn(ret)
}

//export nvmlShutdown
func nvmlShutdown() C.nvmlReturn_t {
	ret := engine.GetEngine().Shutdown()
	return toReturn(ret)
}

//export nvmlErrorString
func nvmlErrorString(result C.nvmlReturn_t) *C.char {
	ret := nvml.Return(result)

	errorStringCacheMu.Lock()
	defer errorStringCacheMu.Unlock()

	if cached, ok := errorStringCache[ret]; ok {
		return cached
	}

	str := nvml.ErrorString(ret)
	cStr := C.CString(str)
	errorStringCache[ret] = cStr
	return cStr
}

//export nvmlSystemGetDriverVersion
func nvmlSystemGetDriverVersion(version unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	if version == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	driverVersion, ret := engine.GetEngine().SystemGetDriverVersion()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(driverVersion, (*C.char)(version), length)
}

//export nvmlSystemGetNVMLVersion
func nvmlSystemGetNVMLVersion(version unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetCudaDriverVersion
func nvmlSystemGetCudaDriverVersion(cudaDriverVersion unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetCudaDriverVersion_v2
func nvmlSystemGetCudaDriverVersion_v2(cudaDriverVersion unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetProcessName
func nvmlSystemGetProcessName(pid C.uint, name unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetHicVersion
func nvmlSystemGetHicVersion(hwbcCount unsafe.Pointer, hwbcEntries unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetTopologyGpuSet
func nvmlSystemGetTopologyGpuSet(cpuNumber C.uint, count unsafe.Pointer, deviceArray unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetDriverBranch
func nvmlSystemGetDriverBranch(branchInfo unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetCount
func nvmlUnitGetCount(unitCount unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetHandleByIndex
func nvmlUnitGetHandleByIndex(index C.uint, nvmlUnit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetUnitInfo
func nvmlUnitGetUnitInfo(nvmlUnit unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetLedState
func nvmlUnitGetLedState(nvmlUnit unsafe.Pointer, state unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetPsuInfo
func nvmlUnitGetPsuInfo(nvmlUnit unsafe.Pointer, psu unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetTemperature
func nvmlUnitGetTemperature(nvmlUnit unsafe.Pointer, _type C.uint, temp unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetFanSpeedInfo
func nvmlUnitGetFanSpeedInfo(nvmlUnit unsafe.Pointer, fanSpeeds unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitGetDevices
func nvmlUnitGetDevices(nvmlUnit unsafe.Pointer, deviceCount unsafe.Pointer, devices unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCount_v2
func nvmlDeviceGetCount_v2(deviceCount unsafe.Pointer) C.nvmlReturn_t {
	if deviceCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	count, ret := engine.GetEngine().DeviceGetCount()
	if ret == nvml.SUCCESS {
		*(*C.uint)(deviceCount) = C.uint(count)
	}
	return toReturn(ret)
}

//export nvmlDeviceGetAttributes_v2
func nvmlDeviceGetAttributes_v2(nvmlDevice unsafe.Pointer, attributes unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetHandleByIndex_v2
func nvmlDeviceGetHandleByIndex_v2(index C.uint, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	handle, ret := engine.GetEngine().DeviceGetHandleByIndex(int(index))
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
	}
	return toReturn(ret)
}

//export nvmlDeviceGetHandleBySerial
func nvmlDeviceGetHandleBySerial(serial *C.char, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetHandleByUUID
func nvmlDeviceGetHandleByUUID(uuid *C.char, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	goUUID := C.GoString(uuid)
	handle, ret := engine.GetEngine().DeviceGetHandleByUUID(goUUID)
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
	}
	return toReturn(ret)
}

//export nvmlDeviceGetHandleByUUIDV
func nvmlDeviceGetHandleByUUIDV(uuid unsafe.Pointer, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetHandleByPciBusId_v2
func nvmlDeviceGetHandleByPciBusId_v2(pciBusId *C.char, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	goPciBusId := C.GoString(pciBusId)
	handle, ret := engine.GetEngine().DeviceGetHandleByPciBusId(goPciBusId)
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
	}
	return toReturn(ret)
}

//export nvmlDeviceGetName
func nvmlDeviceGetName(nvmlDevice unsafe.Pointer, name unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	devName, ret := dev.GetName()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(devName, (*C.char)(name), length)
}

//export nvmlDeviceGetBrand
func nvmlDeviceGetBrand(nvmlDevice unsafe.Pointer, _type unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetIndex
func nvmlDeviceGetIndex(nvmlDevice unsafe.Pointer, index unsafe.Pointer) C.nvmlReturn_t {
	if index == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	idx, ret := dev.GetIndex()
	if ret == nvml.SUCCESS {
		*(*C.uint)(index) = C.uint(idx)
	}
	return toReturn(ret)
}

//export nvmlDeviceGetSerial
func nvmlDeviceGetSerial(nvmlDevice unsafe.Pointer, serial unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetModuleId
func nvmlDeviceGetModuleId(nvmlDevice unsafe.Pointer, moduleId unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetC2cModeInfoV
func nvmlDeviceGetC2cModeInfoV(nvmlDevice unsafe.Pointer, c2cModeInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMemoryAffinity
func nvmlDeviceGetMemoryAffinity(nvmlDevice unsafe.Pointer, nodeSetSize C.uint, nodeSet unsafe.Pointer, scope unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCpuAffinityWithinScope
func nvmlDeviceGetCpuAffinityWithinScope(nvmlDevice unsafe.Pointer, cpuSetSize C.uint, cpuSet unsafe.Pointer, scope unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCpuAffinity
func nvmlDeviceGetCpuAffinity(nvmlDevice unsafe.Pointer, cpuSetSize C.uint, cpuSet unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetCpuAffinity
func nvmlDeviceSetCpuAffinity(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceClearCpuAffinity
func nvmlDeviceClearCpuAffinity(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNumaNodeId
func nvmlDeviceGetNumaNodeId(nvmlDevice unsafe.Pointer, node unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAddressingMode
func nvmlDeviceGetAddressingMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRepairStatus
func nvmlDeviceGetRepairStatus(nvmlDevice unsafe.Pointer, repairStatus unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTopologyCommonAncestor
func nvmlDeviceGetTopologyCommonAncestor(device1 unsafe.Pointer, device2 unsafe.Pointer, pathInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTopologyNearestGpus
func nvmlDeviceGetTopologyNearestGpus(nvmlDevice unsafe.Pointer, level unsafe.Pointer, count unsafe.Pointer, deviceArray unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetP2PStatus
func nvmlDeviceGetP2PStatus(device1 unsafe.Pointer, device2 unsafe.Pointer, p2pIndex unsafe.Pointer, p2pStatus unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetUUID
func nvmlDeviceGetUUID(nvmlDevice unsafe.Pointer, uuid unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	devUUID, ret := dev.GetUUID()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(devUUID, (*C.char)(uuid), length)
}

//export nvmlDeviceGetMinorNumber
func nvmlDeviceGetMinorNumber(nvmlDevice unsafe.Pointer, minorNumber unsafe.Pointer) C.nvmlReturn_t {
	if minorNumber == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	minor, ret := dev.GetMinorNumber()
	if ret == nvml.SUCCESS {
		*(*C.uint)(minorNumber) = C.uint(minor)
	}
	return toReturn(ret)
}

//export nvmlDeviceGetBoardPartNumber
func nvmlDeviceGetBoardPartNumber(nvmlDevice unsafe.Pointer, partNumber unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetInforomVersion
func nvmlDeviceGetInforomVersion(nvmlDevice unsafe.Pointer, object unsafe.Pointer, version unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetInforomImageVersion
func nvmlDeviceGetInforomImageVersion(nvmlDevice unsafe.Pointer, version unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetInforomConfigurationChecksum
func nvmlDeviceGetInforomConfigurationChecksum(nvmlDevice unsafe.Pointer, checksum unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceValidateInforom
func nvmlDeviceValidateInforom(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetLastBBXFlushTime
func nvmlDeviceGetLastBBXFlushTime(nvmlDevice unsafe.Pointer, timestamp unsafe.Pointer, durationUs unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDisplayMode
func nvmlDeviceGetDisplayMode(nvmlDevice unsafe.Pointer, display unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDisplayActive
func nvmlDeviceGetDisplayActive(nvmlDevice unsafe.Pointer, isActive unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPersistenceMode
func nvmlDeviceGetPersistenceMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPciInfoExt
func nvmlDeviceGetPciInfoExt(nvmlDevice unsafe.Pointer, pci unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPciInfo_v3
func nvmlDeviceGetPciInfo_v3(nvmlDevice unsafe.Pointer, pci unsafe.Pointer) C.nvmlReturn_t {
	if pci == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	info, ret := dev.GetPciInfo()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	// Copy busId bytes directly
	cPci := (*C.nvmlPciInfo_t)(pci)
	for i := 0; i < 32 && i < len(info.BusId); i++ {
		cPci.busId[i] = C.char(info.BusId[i])
	}
	cPci.domain = C.uint(info.Domain)
	cPci.bus = C.uint(info.Bus)
	cPci.device = C.uint(info.Device)
	cPci.pciDeviceId = C.uint(info.PciDeviceId)
	cPci.pciSubSystemId = C.uint(info.PciSubSystemId)
	return C.NVML_SUCCESS
}

//export nvmlDeviceGetMaxPcieLinkGeneration
func nvmlDeviceGetMaxPcieLinkGeneration(nvmlDevice unsafe.Pointer, maxLinkGen unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuMaxPcieLinkGeneration
func nvmlDeviceGetGpuMaxPcieLinkGeneration(nvmlDevice unsafe.Pointer, maxLinkGenDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMaxPcieLinkWidth
func nvmlDeviceGetMaxPcieLinkWidth(nvmlDevice unsafe.Pointer, maxLinkWidth unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCurrPcieLinkGeneration
func nvmlDeviceGetCurrPcieLinkGeneration(nvmlDevice unsafe.Pointer, currLinkGen unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCurrPcieLinkWidth
func nvmlDeviceGetCurrPcieLinkWidth(nvmlDevice unsafe.Pointer, currLinkWidth unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPcieThroughput
func nvmlDeviceGetPcieThroughput(nvmlDevice unsafe.Pointer, counter unsafe.Pointer, value unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPcieReplayCounter
func nvmlDeviceGetPcieReplayCounter(nvmlDevice unsafe.Pointer, value unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetClockInfo
func nvmlDeviceGetClockInfo(nvmlDevice unsafe.Pointer, _type unsafe.Pointer, clock unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMaxClockInfo
func nvmlDeviceGetMaxClockInfo(nvmlDevice unsafe.Pointer, _type unsafe.Pointer, clock unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpcClkVfOffset
func nvmlDeviceGetGpcClkVfOffset(nvmlDevice unsafe.Pointer, offset unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetApplicationsClock
func nvmlDeviceGetApplicationsClock(nvmlDevice unsafe.Pointer, clockType unsafe.Pointer, clockMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDefaultApplicationsClock
func nvmlDeviceGetDefaultApplicationsClock(nvmlDevice unsafe.Pointer, clockType unsafe.Pointer, clockMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetClock
func nvmlDeviceGetClock(nvmlDevice unsafe.Pointer, clockType unsafe.Pointer, clockId unsafe.Pointer, clockMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMaxCustomerBoostClock
func nvmlDeviceGetMaxCustomerBoostClock(nvmlDevice unsafe.Pointer, clockType unsafe.Pointer, clockMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedMemoryClocks
func nvmlDeviceGetSupportedMemoryClocks(nvmlDevice unsafe.Pointer, count unsafe.Pointer, clocksMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedGraphicsClocks
func nvmlDeviceGetSupportedGraphicsClocks(nvmlDevice unsafe.Pointer, memoryClockMHz C.uint, count unsafe.Pointer, clocksMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAutoBoostedClocksEnabled
func nvmlDeviceGetAutoBoostedClocksEnabled(nvmlDevice unsafe.Pointer, isEnabled unsafe.Pointer, defaultIsEnabled unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFanSpeed
func nvmlDeviceGetFanSpeed(nvmlDevice unsafe.Pointer, speed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFanSpeed_v2
func nvmlDeviceGetFanSpeed_v2(nvmlDevice unsafe.Pointer, fan C.uint, speed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFanSpeedRPM
func nvmlDeviceGetFanSpeedRPM(nvmlDevice unsafe.Pointer, fanSpeed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTargetFanSpeed
func nvmlDeviceGetTargetFanSpeed(nvmlDevice unsafe.Pointer, fan C.uint, targetSpeed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMinMaxFanSpeed
func nvmlDeviceGetMinMaxFanSpeed(nvmlDevice unsafe.Pointer, minSpeed unsafe.Pointer, maxSpeed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFanControlPolicy_v2
func nvmlDeviceGetFanControlPolicy_v2(nvmlDevice unsafe.Pointer, fan C.uint, policy unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNumFans
func nvmlDeviceGetNumFans(nvmlDevice unsafe.Pointer, numFans unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTemperature
func nvmlDeviceGetTemperature(nvmlDevice unsafe.Pointer, sensorType unsafe.Pointer, temp unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCoolerInfo
func nvmlDeviceGetCoolerInfo(nvmlDevice unsafe.Pointer, coolerInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTemperatureV
func nvmlDeviceGetTemperatureV(nvmlDevice unsafe.Pointer, temperature unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTemperatureThreshold
func nvmlDeviceGetTemperatureThreshold(nvmlDevice unsafe.Pointer, thresholdType unsafe.Pointer, temp unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMarginTemperature
func nvmlDeviceGetMarginTemperature(nvmlDevice unsafe.Pointer, marginTempInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetThermalSettings
func nvmlDeviceGetThermalSettings(nvmlDevice unsafe.Pointer, sensorIndex C.uint, pThermalSettings unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPerformanceState
func nvmlDeviceGetPerformanceState(nvmlDevice unsafe.Pointer, pState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCurrentClocksEventReasons
func nvmlDeviceGetCurrentClocksEventReasons(nvmlDevice unsafe.Pointer, clocksEventReasons unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCurrentClocksThrottleReasons
func nvmlDeviceGetCurrentClocksThrottleReasons(nvmlDevice unsafe.Pointer, clocksThrottleReasons unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedClocksEventReasons
func nvmlDeviceGetSupportedClocksEventReasons(nvmlDevice unsafe.Pointer, supportedClocksEventReasons unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedClocksThrottleReasons
func nvmlDeviceGetSupportedClocksThrottleReasons(nvmlDevice unsafe.Pointer, supportedClocksThrottleReasons unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerState
func nvmlDeviceGetPowerState(nvmlDevice unsafe.Pointer, pState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDynamicPstatesInfo
func nvmlDeviceGetDynamicPstatesInfo(nvmlDevice unsafe.Pointer, pDynamicPstatesInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMemClkVfOffset
func nvmlDeviceGetMemClkVfOffset(nvmlDevice unsafe.Pointer, offset unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMinMaxClockOfPState
func nvmlDeviceGetMinMaxClockOfPState(nvmlDevice unsafe.Pointer, _type unsafe.Pointer, pstate unsafe.Pointer, minClockMHz unsafe.Pointer, maxClockMHz unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedPerformanceStates
func nvmlDeviceGetSupportedPerformanceStates(nvmlDevice unsafe.Pointer, pstates unsafe.Pointer, size C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpcClkMinMaxVfOffset
func nvmlDeviceGetGpcClkMinMaxVfOffset(nvmlDevice unsafe.Pointer, minOffset unsafe.Pointer, maxOffset unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMemClkMinMaxVfOffset
func nvmlDeviceGetMemClkMinMaxVfOffset(nvmlDevice unsafe.Pointer, minOffset unsafe.Pointer, maxOffset unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetClockOffsets
func nvmlDeviceGetClockOffsets(nvmlDevice unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetClockOffsets
func nvmlDeviceSetClockOffsets(nvmlDevice unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPerformanceModes
func nvmlDeviceGetPerformanceModes(nvmlDevice unsafe.Pointer, perfModes unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCurrentClockFreqs
func nvmlDeviceGetCurrentClockFreqs(nvmlDevice unsafe.Pointer, currentClockFreqs unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerManagementMode
func nvmlDeviceGetPowerManagementMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerManagementLimit
func nvmlDeviceGetPowerManagementLimit(nvmlDevice unsafe.Pointer, limit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerManagementLimitConstraints
func nvmlDeviceGetPowerManagementLimitConstraints(nvmlDevice unsafe.Pointer, minLimit unsafe.Pointer, maxLimit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerManagementDefaultLimit
func nvmlDeviceGetPowerManagementDefaultLimit(nvmlDevice unsafe.Pointer, defaultLimit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerUsage
func nvmlDeviceGetPowerUsage(nvmlDevice unsafe.Pointer, power unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerMizerMode_v1
func nvmlDeviceGetPowerMizerMode_v1(nvmlDevice unsafe.Pointer, powerMizerMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetPowerMizerMode_v1
func nvmlDeviceSetPowerMizerMode_v1(nvmlDevice unsafe.Pointer, powerMizerMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTotalEnergyConsumption
func nvmlDeviceGetTotalEnergyConsumption(nvmlDevice unsafe.Pointer, energy unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetEnforcedPowerLimit
func nvmlDeviceGetEnforcedPowerLimit(nvmlDevice unsafe.Pointer, limit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuOperationMode
func nvmlDeviceGetGpuOperationMode(nvmlDevice unsafe.Pointer, current unsafe.Pointer, pending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMemoryInfo
func nvmlDeviceGetMemoryInfo(nvmlDevice unsafe.Pointer, memory unsafe.Pointer) C.nvmlReturn_t {
	if memory == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	info, ret := dev.GetMemoryInfo()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	cMemory := (*C.nvmlMemory_t)(memory)
	cMemory.total = C.ulonglong(info.Total)
	cMemory.free = C.ulonglong(info.Free)
	cMemory.used = C.ulonglong(info.Used)
	return C.NVML_SUCCESS
}

//export nvmlDeviceGetMemoryInfo_v2
func nvmlDeviceGetMemoryInfo_v2(nvmlDevice unsafe.Pointer, memory unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetComputeMode
func nvmlDeviceGetComputeMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCudaComputeCapability
func nvmlDeviceGetCudaComputeCapability(nvmlDevice unsafe.Pointer, major unsafe.Pointer, minor unsafe.Pointer) C.nvmlReturn_t {
	if major == nil || minor == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	maj, min, ret := dev.GetCudaComputeCapability()
	if ret == nvml.SUCCESS {
		*(*C.int)(major) = C.int(maj)
		*(*C.int)(minor) = C.int(min)
	}
	return toReturn(ret)
}

//export nvmlDeviceGetDramEncryptionMode
func nvmlDeviceGetDramEncryptionMode(nvmlDevice unsafe.Pointer, current unsafe.Pointer, pending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetDramEncryptionMode
func nvmlDeviceSetDramEncryptionMode(nvmlDevice unsafe.Pointer, dramEncryption unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetEccMode
func nvmlDeviceGetEccMode(nvmlDevice unsafe.Pointer, current unsafe.Pointer, pending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDefaultEccMode
func nvmlDeviceGetDefaultEccMode(nvmlDevice unsafe.Pointer, defaultMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetBoardId
func nvmlDeviceGetBoardId(nvmlDevice unsafe.Pointer, boardId unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMultiGpuBoard
func nvmlDeviceGetMultiGpuBoard(nvmlDevice unsafe.Pointer, multiGpuBool unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetTotalEccErrors
func nvmlDeviceGetTotalEccErrors(nvmlDevice unsafe.Pointer, errorType unsafe.Pointer, counterType unsafe.Pointer, eccCounts unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDetailedEccErrors
func nvmlDeviceGetDetailedEccErrors(nvmlDevice unsafe.Pointer, errorType unsafe.Pointer, counterType unsafe.Pointer, eccCounts unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMemoryErrorCounter
func nvmlDeviceGetMemoryErrorCounter(nvmlDevice unsafe.Pointer, errorType unsafe.Pointer, counterType unsafe.Pointer, locationType unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetUtilizationRates
func nvmlDeviceGetUtilizationRates(nvmlDevice unsafe.Pointer, utilization unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetEncoderUtilization
func nvmlDeviceGetEncoderUtilization(nvmlDevice unsafe.Pointer, utilization unsafe.Pointer, samplingPeriodUs unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetEncoderCapacity
func nvmlDeviceGetEncoderCapacity(nvmlDevice unsafe.Pointer, encoderQueryType unsafe.Pointer, encoderCapacity unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetEncoderStats
func nvmlDeviceGetEncoderStats(nvmlDevice unsafe.Pointer, sessionCount unsafe.Pointer, averageFps unsafe.Pointer, averageLatency unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetEncoderSessions
func nvmlDeviceGetEncoderSessions(nvmlDevice unsafe.Pointer, sessionCount unsafe.Pointer, sessionInfos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDecoderUtilization
func nvmlDeviceGetDecoderUtilization(nvmlDevice unsafe.Pointer, utilization unsafe.Pointer, samplingPeriodUs unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetJpgUtilization
func nvmlDeviceGetJpgUtilization(nvmlDevice unsafe.Pointer, utilization unsafe.Pointer, samplingPeriodUs unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetOfaUtilization
func nvmlDeviceGetOfaUtilization(nvmlDevice unsafe.Pointer, utilization unsafe.Pointer, samplingPeriodUs unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFBCStats
func nvmlDeviceGetFBCStats(nvmlDevice unsafe.Pointer, fbcStats unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFBCSessions
func nvmlDeviceGetFBCSessions(nvmlDevice unsafe.Pointer, sessionCount unsafe.Pointer, sessionInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDriverModel_v2
func nvmlDeviceGetDriverModel_v2(nvmlDevice unsafe.Pointer, current unsafe.Pointer, pending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVbiosVersion
func nvmlDeviceGetVbiosVersion(nvmlDevice unsafe.Pointer, version unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetBridgeChipInfo
func nvmlDeviceGetBridgeChipInfo(nvmlDevice unsafe.Pointer, bridgeHierarchy unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetComputeRunningProcesses_v3
func nvmlDeviceGetComputeRunningProcesses_v3(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	if infoCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	processes, ret := dev.GetComputeRunningProcesses()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*uint32)(infoCount) = uint32(len(processes))
	return toReturn(nvml.SUCCESS)
}

//export nvmlDeviceGetGraphicsRunningProcesses_v3
func nvmlDeviceGetGraphicsRunningProcesses_v3(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	if infoCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	processes, ret := dev.GetGraphicsRunningProcesses()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*uint32)(infoCount) = uint32(len(processes))
	return toReturn(nvml.SUCCESS)
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v3
func nvmlDeviceGetMPSComputeRunningProcesses_v3(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRunningProcessDetailList
func nvmlDeviceGetRunningProcessDetailList(nvmlDevice unsafe.Pointer, plist unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceOnSameBoard
func nvmlDeviceOnSameBoard(device1 unsafe.Pointer, device2 unsafe.Pointer, onSameBoard unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAPIRestriction
func nvmlDeviceGetAPIRestriction(nvmlDevice unsafe.Pointer, apiType unsafe.Pointer, isRestricted unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSamples
func nvmlDeviceGetSamples(nvmlDevice unsafe.Pointer, _type unsafe.Pointer, lastSeenTimeStamp C.ulonglong, sampleValType unsafe.Pointer, sampleCount unsafe.Pointer, samples unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetBAR1MemoryInfo
func nvmlDeviceGetBAR1MemoryInfo(nvmlDevice unsafe.Pointer, bar1Memory unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetViolationStatus
func nvmlDeviceGetViolationStatus(nvmlDevice unsafe.Pointer, perfPolicyType unsafe.Pointer, violTime unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetIrqNum
func nvmlDeviceGetIrqNum(nvmlDevice unsafe.Pointer, irqNum unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNumGpuCores
func nvmlDeviceGetNumGpuCores(nvmlDevice unsafe.Pointer, numCores unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPowerSource
func nvmlDeviceGetPowerSource(nvmlDevice unsafe.Pointer, powerSource unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMemoryBusWidth
func nvmlDeviceGetMemoryBusWidth(nvmlDevice unsafe.Pointer, busWidth unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPcieLinkMaxSpeed
func nvmlDeviceGetPcieLinkMaxSpeed(nvmlDevice unsafe.Pointer, maxSpeed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPcieSpeed
func nvmlDeviceGetPcieSpeed(nvmlDevice unsafe.Pointer, pcieSpeed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAdaptiveClockInfoStatus
func nvmlDeviceGetAdaptiveClockInfoStatus(nvmlDevice unsafe.Pointer, adaptiveClockStatus unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetBusType
func nvmlDeviceGetBusType(nvmlDevice unsafe.Pointer, _type unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuFabricInfo
func nvmlDeviceGetGpuFabricInfo(nvmlDevice unsafe.Pointer, gpuFabricInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuFabricInfoV
func nvmlDeviceGetGpuFabricInfoV(nvmlDevice unsafe.Pointer, gpuFabricInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetConfComputeCapabilities
func nvmlSystemGetConfComputeCapabilities(capabilities unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetConfComputeState
func nvmlSystemGetConfComputeState(state unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetConfComputeMemSizeInfo
func nvmlDeviceGetConfComputeMemSizeInfo(nvmlDevice unsafe.Pointer, memInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetConfComputeGpusReadyState
func nvmlSystemGetConfComputeGpusReadyState(isAcceptingWork unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetConfComputeProtectedMemoryUsage
func nvmlDeviceGetConfComputeProtectedMemoryUsage(nvmlDevice unsafe.Pointer, memory unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetConfComputeGpuCertificate
func nvmlDeviceGetConfComputeGpuCertificate(nvmlDevice unsafe.Pointer, gpuCert unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetConfComputeGpuAttestationReport
func nvmlDeviceGetConfComputeGpuAttestationReport(nvmlDevice unsafe.Pointer, gpuAtstReport unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetConfComputeKeyRotationThresholdInfo
func nvmlSystemGetConfComputeKeyRotationThresholdInfo(pKeyRotationThrInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetConfComputeUnprotectedMemSize
func nvmlDeviceSetConfComputeUnprotectedMemSize(nvmlDevice unsafe.Pointer, sizeKiB C.ulonglong) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemSetConfComputeGpusReadyState
func nvmlSystemSetConfComputeGpusReadyState(isAcceptingWork C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemSetConfComputeKeyRotationThresholdInfo
func nvmlSystemSetConfComputeKeyRotationThresholdInfo(pKeyRotationThrInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetConfComputeSettings
func nvmlSystemGetConfComputeSettings(settings unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGspFirmwareVersion
func nvmlDeviceGetGspFirmwareVersion(nvmlDevice unsafe.Pointer, version unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGspFirmwareMode
func nvmlDeviceGetGspFirmwareMode(nvmlDevice unsafe.Pointer, isEnabled unsafe.Pointer, defaultMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSramEccErrorStatus
func nvmlDeviceGetSramEccErrorStatus(nvmlDevice unsafe.Pointer, status unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetPowerManagementLimit_v2
func nvmlDeviceSetPowerManagementLimit_v2(nvmlDevice unsafe.Pointer, powerValue unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAccountingMode
func nvmlDeviceGetAccountingMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAccountingStats
func nvmlDeviceGetAccountingStats(nvmlDevice unsafe.Pointer, pid C.uint, stats unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAccountingPids
func nvmlDeviceGetAccountingPids(nvmlDevice unsafe.Pointer, count unsafe.Pointer, pids unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAccountingBufferSize
func nvmlDeviceGetAccountingBufferSize(nvmlDevice unsafe.Pointer, bufferSize unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRetiredPages
func nvmlDeviceGetRetiredPages(nvmlDevice unsafe.Pointer, cause unsafe.Pointer, pageCount unsafe.Pointer, addresses unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRetiredPages_v2
func nvmlDeviceGetRetiredPages_v2(nvmlDevice unsafe.Pointer, cause unsafe.Pointer, pageCount unsafe.Pointer, addresses unsafe.Pointer, timestamps unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRetiredPagesPendingStatus
func nvmlDeviceGetRetiredPagesPendingStatus(nvmlDevice unsafe.Pointer, isPending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRemappedRows
func nvmlDeviceGetRemappedRows(nvmlDevice unsafe.Pointer, corrRows unsafe.Pointer, uncRows unsafe.Pointer, isPending unsafe.Pointer, failureOccurred unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetRowRemapperHistogram
func nvmlDeviceGetRowRemapperHistogram(nvmlDevice unsafe.Pointer, values unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetArchitecture
func nvmlDeviceGetArchitecture(nvmlDevice unsafe.Pointer, arch unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetClkMonStatus
func nvmlDeviceGetClkMonStatus(nvmlDevice unsafe.Pointer, status unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetProcessUtilization
func nvmlDeviceGetProcessUtilization(nvmlDevice unsafe.Pointer, utilization unsafe.Pointer, processSamplesCount unsafe.Pointer, lastSeenTimeStamp C.ulonglong) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetProcessesUtilizationInfo
func nvmlDeviceGetProcessesUtilizationInfo(nvmlDevice unsafe.Pointer, procesesUtilInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPlatformInfo
func nvmlDeviceGetPlatformInfo(nvmlDevice unsafe.Pointer, platformInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPdi
func nvmlDeviceGetPdi(nvmlDevice unsafe.Pointer, pdi unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlUnitSetLedState
func nvmlUnitSetLedState(nvmlUnit unsafe.Pointer, color unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetPersistenceMode
func nvmlDeviceSetPersistenceMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetComputeMode
func nvmlDeviceSetComputeMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetEccMode
func nvmlDeviceSetEccMode(nvmlDevice unsafe.Pointer, ecc unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceClearEccErrorCounts
func nvmlDeviceClearEccErrorCounts(nvmlDevice unsafe.Pointer, counterType unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetDriverModel
func nvmlDeviceSetDriverModel(nvmlDevice unsafe.Pointer, driverModel unsafe.Pointer, flags C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetGpuLockedClocks
func nvmlDeviceSetGpuLockedClocks(nvmlDevice unsafe.Pointer, minGpuClockMHz C.uint, maxGpuClockMHz C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceResetGpuLockedClocks
func nvmlDeviceResetGpuLockedClocks(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetMemoryLockedClocks
func nvmlDeviceSetMemoryLockedClocks(nvmlDevice unsafe.Pointer, minMemClockMHz C.uint, maxMemClockMHz C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceResetMemoryLockedClocks
func nvmlDeviceResetMemoryLockedClocks(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetApplicationsClocks
func nvmlDeviceSetApplicationsClocks(nvmlDevice unsafe.Pointer, memClockMHz C.uint, graphicsClockMHz C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceResetApplicationsClocks
func nvmlDeviceResetApplicationsClocks(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetAutoBoostedClocksEnabled
func nvmlDeviceSetAutoBoostedClocksEnabled(nvmlDevice unsafe.Pointer, enabled unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetDefaultAutoBoostedClocksEnabled
func nvmlDeviceSetDefaultAutoBoostedClocksEnabled(nvmlDevice unsafe.Pointer, enabled unsafe.Pointer, flags C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetDefaultFanSpeed_v2
func nvmlDeviceSetDefaultFanSpeed_v2(nvmlDevice unsafe.Pointer, fan C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetFanControlPolicy
func nvmlDeviceSetFanControlPolicy(nvmlDevice unsafe.Pointer, fan C.uint, policy unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetTemperatureThreshold
func nvmlDeviceSetTemperatureThreshold(nvmlDevice unsafe.Pointer, thresholdType unsafe.Pointer, temp unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetPowerManagementLimit
func nvmlDeviceSetPowerManagementLimit(nvmlDevice unsafe.Pointer, limit C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetGpuOperationMode
func nvmlDeviceSetGpuOperationMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetAPIRestriction
func nvmlDeviceSetAPIRestriction(nvmlDevice unsafe.Pointer, apiType unsafe.Pointer, isRestricted unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetFanSpeed_v2
func nvmlDeviceSetFanSpeed_v2(nvmlDevice unsafe.Pointer, fan C.uint, speed C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetGpcClkVfOffset
func nvmlDeviceSetGpcClkVfOffset(nvmlDevice unsafe.Pointer, offset C.int) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetMemClkVfOffset
func nvmlDeviceSetMemClkVfOffset(nvmlDevice unsafe.Pointer, offset C.int) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetAccountingMode
func nvmlDeviceSetAccountingMode(nvmlDevice unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceClearAccountingPids
func nvmlDeviceClearAccountingPids(nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkState
func nvmlDeviceGetNvLinkState(nvmlDevice unsafe.Pointer, link C.uint, isActive unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkVersion
func nvmlDeviceGetNvLinkVersion(nvmlDevice unsafe.Pointer, link C.uint, version unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkCapability
func nvmlDeviceGetNvLinkCapability(nvmlDevice unsafe.Pointer, link C.uint, capability unsafe.Pointer, capResult unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkRemotePciInfo_v2
func nvmlDeviceGetNvLinkRemotePciInfo_v2(nvmlDevice unsafe.Pointer, link C.uint, pci unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkErrorCounter
func nvmlDeviceGetNvLinkErrorCounter(nvmlDevice unsafe.Pointer, link C.uint, counter unsafe.Pointer, counterValue unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceResetNvLinkErrorCounters
func nvmlDeviceResetNvLinkErrorCounters(nvmlDevice unsafe.Pointer, link C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetNvLinkUtilizationControl
func nvmlDeviceSetNvLinkUtilizationControl(nvmlDevice unsafe.Pointer, link C.uint, counter C.uint, control unsafe.Pointer, reset C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkUtilizationControl
func nvmlDeviceGetNvLinkUtilizationControl(nvmlDevice unsafe.Pointer, link C.uint, counter C.uint, control unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkUtilizationCounter
func nvmlDeviceGetNvLinkUtilizationCounter(nvmlDevice unsafe.Pointer, link C.uint, counter C.uint, rxcounter unsafe.Pointer, txcounter unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceFreezeNvLinkUtilizationCounter
func nvmlDeviceFreezeNvLinkUtilizationCounter(nvmlDevice unsafe.Pointer, link C.uint, counter C.uint, freeze unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceResetNvLinkUtilizationCounter
func nvmlDeviceResetNvLinkUtilizationCounter(nvmlDevice unsafe.Pointer, link C.uint, counter C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkRemoteDeviceType
func nvmlDeviceGetNvLinkRemoteDeviceType(nvmlDevice unsafe.Pointer, link C.uint, pNvLinkDeviceType unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetNvLinkDeviceLowPowerThreshold
func nvmlDeviceSetNvLinkDeviceLowPowerThreshold(nvmlDevice unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemSetNvlinkBwMode
func nvmlSystemSetNvlinkBwMode(nvlinkBwMode C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemGetNvlinkBwMode
func nvmlSystemGetNvlinkBwMode(nvlinkBwMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvlinkSupportedBwModes
func nvmlDeviceGetNvlinkSupportedBwModes(nvmlDevice unsafe.Pointer, supportedBwMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvlinkBwMode
func nvmlDeviceGetNvlinkBwMode(nvmlDevice unsafe.Pointer, getBwMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetNvlinkBwMode
func nvmlDeviceSetNvlinkBwMode(nvmlDevice unsafe.Pointer, setBwMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkInfo
func nvmlDeviceGetNvLinkInfo(nvmlDevice unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlEventSetCreate
func nvmlEventSetCreate(set unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceRegisterEvents
func nvmlDeviceRegisterEvents(nvmlDevice unsafe.Pointer, eventTypes C.ulonglong, set unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedEventTypes
func nvmlDeviceGetSupportedEventTypes(nvmlDevice unsafe.Pointer, eventTypes unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlEventSetWait_v2
func nvmlEventSetWait_v2(set unsafe.Pointer, data unsafe.Pointer, timeoutms C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlEventSetFree
func nvmlEventSetFree(set unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemEventSetCreate
func nvmlSystemEventSetCreate(request unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemEventSetFree
func nvmlSystemEventSetFree(request unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemRegisterEvents
func nvmlSystemRegisterEvents(request unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSystemEventSetWait
func nvmlSystemEventSetWait(request unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceModifyDrainState
func nvmlDeviceModifyDrainState(pciInfo unsafe.Pointer, newState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceQueryDrainState
func nvmlDeviceQueryDrainState(pciInfo unsafe.Pointer, currentState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceRemoveGpu_v2
func nvmlDeviceRemoveGpu_v2(pciInfo unsafe.Pointer, gpuState unsafe.Pointer, linkState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceDiscoverGpus
func nvmlDeviceDiscoverGpus(pciInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetFieldValues
func nvmlDeviceGetFieldValues(nvmlDevice unsafe.Pointer, valuesCount C.int, values unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceClearFieldValues
func nvmlDeviceClearFieldValues(nvmlDevice unsafe.Pointer, valuesCount C.int, values unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVirtualizationMode
func nvmlDeviceGetVirtualizationMode(nvmlDevice unsafe.Pointer, pVirtualMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetHostVgpuMode
func nvmlDeviceGetHostVgpuMode(nvmlDevice unsafe.Pointer, pHostVgpuMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetVirtualizationMode
func nvmlDeviceSetVirtualizationMode(nvmlDevice unsafe.Pointer, virtualMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuHeterogeneousMode
func nvmlDeviceGetVgpuHeterogeneousMode(nvmlDevice unsafe.Pointer, pHeterogeneousMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetVgpuHeterogeneousMode
func nvmlDeviceSetVgpuHeterogeneousMode(nvmlDevice unsafe.Pointer, pHeterogeneousMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetPlacementId
func nvmlVgpuInstanceGetPlacementId(nvmlVgpuInstance unsafe.Pointer, pPlacement unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuTypeSupportedPlacements
func nvmlDeviceGetVgpuTypeSupportedPlacements(nvmlDevice unsafe.Pointer, nvmlVgpuTypeId unsafe.Pointer, pPlacementList unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuTypeCreatablePlacements
func nvmlDeviceGetVgpuTypeCreatablePlacements(nvmlDevice unsafe.Pointer, nvmlVgpuTypeId unsafe.Pointer, pPlacementList unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetGspHeapSize
func nvmlVgpuTypeGetGspHeapSize(nvmlVgpuTypeId unsafe.Pointer, gspHeapSize unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetFbReservation
func nvmlVgpuTypeGetFbReservation(nvmlVgpuTypeId unsafe.Pointer, fbReservation unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetRuntimeStateSize
func nvmlVgpuInstanceGetRuntimeStateSize(nvmlVgpuInstance unsafe.Pointer, pState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetVgpuCapabilities
func nvmlDeviceSetVgpuCapabilities(nvmlDevice unsafe.Pointer, capability unsafe.Pointer, state unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGridLicensableFeatures_v4
func nvmlDeviceGetGridLicensableFeatures_v4(nvmlDevice unsafe.Pointer, pGridLicensableFeatures unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGetVgpuDriverCapabilities
func nvmlGetVgpuDriverCapabilities(capability unsafe.Pointer, capResult unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuCapabilities
func nvmlDeviceGetVgpuCapabilities(nvmlDevice unsafe.Pointer, capability unsafe.Pointer, capResult unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSupportedVgpus
func nvmlDeviceGetSupportedVgpus(nvmlDevice unsafe.Pointer, vgpuCount unsafe.Pointer, vgpuTypeIds unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCreatableVgpus
func nvmlDeviceGetCreatableVgpus(nvmlDevice unsafe.Pointer, vgpuCount unsafe.Pointer, vgpuTypeIds unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetClass
func nvmlVgpuTypeGetClass(nvmlVgpuTypeId unsafe.Pointer, vgpuTypeClass unsafe.Pointer, size unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetName
func nvmlVgpuTypeGetName(nvmlVgpuTypeId unsafe.Pointer, vgpuTypeName unsafe.Pointer, size unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetGpuInstanceProfileId
func nvmlVgpuTypeGetGpuInstanceProfileId(nvmlVgpuTypeId unsafe.Pointer, gpuInstanceProfileId unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetDeviceID
func nvmlVgpuTypeGetDeviceID(nvmlVgpuTypeId unsafe.Pointer, deviceID unsafe.Pointer, subsystemID unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetFramebufferSize
func nvmlVgpuTypeGetFramebufferSize(nvmlVgpuTypeId unsafe.Pointer, fbSize unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetNumDisplayHeads
func nvmlVgpuTypeGetNumDisplayHeads(nvmlVgpuTypeId unsafe.Pointer, numDisplayHeads unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetResolution
func nvmlVgpuTypeGetResolution(nvmlVgpuTypeId unsafe.Pointer, displayIndex C.uint, xdim unsafe.Pointer, ydim unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetLicense
func nvmlVgpuTypeGetLicense(nvmlVgpuTypeId unsafe.Pointer, vgpuTypeLicenseString unsafe.Pointer, size C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetFrameRateLimit
func nvmlVgpuTypeGetFrameRateLimit(nvmlVgpuTypeId unsafe.Pointer, frameRateLimit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetMaxInstances
func nvmlVgpuTypeGetMaxInstances(nvmlDevice unsafe.Pointer, nvmlVgpuTypeId unsafe.Pointer, vgpuInstanceCount unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetMaxInstancesPerVm
func nvmlVgpuTypeGetMaxInstancesPerVm(nvmlVgpuTypeId unsafe.Pointer, vgpuInstanceCountPerVm unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetBAR1Info
func nvmlVgpuTypeGetBAR1Info(nvmlVgpuTypeId unsafe.Pointer, bar1Info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetActiveVgpus
func nvmlDeviceGetActiveVgpus(nvmlDevice unsafe.Pointer, vgpuCount unsafe.Pointer, vgpuInstances unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetVmID
func nvmlVgpuInstanceGetVmID(nvmlVgpuInstance unsafe.Pointer, vmId unsafe.Pointer, size C.uint, vmIdType unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetUUID
func nvmlVgpuInstanceGetUUID(nvmlVgpuInstance unsafe.Pointer, uuid unsafe.Pointer, size C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetVmDriverVersion
func nvmlVgpuInstanceGetVmDriverVersion(nvmlVgpuInstance unsafe.Pointer, version unsafe.Pointer, length C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetFbUsage
func nvmlVgpuInstanceGetFbUsage(nvmlVgpuInstance unsafe.Pointer, fbUsage unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetLicenseStatus
func nvmlVgpuInstanceGetLicenseStatus(nvmlVgpuInstance unsafe.Pointer, licensed unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetType
func nvmlVgpuInstanceGetType(nvmlVgpuInstance unsafe.Pointer, nvmlVgpuTypeId unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetFrameRateLimit
func nvmlVgpuInstanceGetFrameRateLimit(nvmlVgpuInstance unsafe.Pointer, frameRateLimit unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetEccMode
func nvmlVgpuInstanceGetEccMode(nvmlVgpuInstance unsafe.Pointer, eccMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetEncoderCapacity
func nvmlVgpuInstanceGetEncoderCapacity(nvmlVgpuInstance unsafe.Pointer, encoderCapacity unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceSetEncoderCapacity
func nvmlVgpuInstanceSetEncoderCapacity(nvmlVgpuInstance unsafe.Pointer, encoderCapacity C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetEncoderStats
func nvmlVgpuInstanceGetEncoderStats(nvmlVgpuInstance unsafe.Pointer, sessionCount unsafe.Pointer, averageFps unsafe.Pointer, averageLatency unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetEncoderSessions
func nvmlVgpuInstanceGetEncoderSessions(nvmlVgpuInstance unsafe.Pointer, sessionCount unsafe.Pointer, sessionInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetFBCStats
func nvmlVgpuInstanceGetFBCStats(nvmlVgpuInstance unsafe.Pointer, fbcStats unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetFBCSessions
func nvmlVgpuInstanceGetFBCSessions(nvmlVgpuInstance unsafe.Pointer, sessionCount unsafe.Pointer, sessionInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetGpuInstanceId
func nvmlVgpuInstanceGetGpuInstanceId(nvmlVgpuInstance unsafe.Pointer, gpuInstanceId unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetGpuPciId
func nvmlVgpuInstanceGetGpuPciId(nvmlVgpuInstance unsafe.Pointer, vgpuPciId unsafe.Pointer, length unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetCapabilities
func nvmlVgpuTypeGetCapabilities(nvmlVgpuTypeId unsafe.Pointer, capability unsafe.Pointer, capResult unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetMdevUUID
func nvmlVgpuInstanceGetMdevUUID(nvmlVgpuInstance unsafe.Pointer, mdevUuid unsafe.Pointer, size C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetCreatableVgpus
func nvmlGpuInstanceGetCreatableVgpus(nvmlGpuInstance unsafe.Pointer, pVgpus unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuTypeGetMaxInstancesPerGpuInstance
func nvmlVgpuTypeGetMaxInstancesPerGpuInstance(pMaxInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetActiveVgpus
func nvmlGpuInstanceGetActiveVgpus(nvmlGpuInstance unsafe.Pointer, pVgpuInstanceInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceSetVgpuSchedulerState
func nvmlGpuInstanceSetVgpuSchedulerState(nvmlGpuInstance unsafe.Pointer, pScheduler unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetVgpuSchedulerState
func nvmlGpuInstanceGetVgpuSchedulerState(nvmlGpuInstance unsafe.Pointer, pSchedulerStateInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetVgpuSchedulerLog
func nvmlGpuInstanceGetVgpuSchedulerLog(nvmlGpuInstance unsafe.Pointer, pSchedulerLogInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetVgpuTypeCreatablePlacements
func nvmlGpuInstanceGetVgpuTypeCreatablePlacements(nvmlGpuInstance unsafe.Pointer, pCreatablePlacementInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetVgpuHeterogeneousMode
func nvmlGpuInstanceGetVgpuHeterogeneousMode(nvmlGpuInstance unsafe.Pointer, pHeterogeneousMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceSetVgpuHeterogeneousMode
func nvmlGpuInstanceSetVgpuHeterogeneousMode(nvmlGpuInstance unsafe.Pointer, pHeterogeneousMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetMetadata
func nvmlVgpuInstanceGetMetadata(nvmlVgpuInstance unsafe.Pointer, nvmlVgpuMetadata unsafe.Pointer, bufferSize unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuMetadata
func nvmlDeviceGetVgpuMetadata(nvmlDevice unsafe.Pointer, pgpuMetadata unsafe.Pointer, bufferSize unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGetVgpuCompatibility
func nvmlGetVgpuCompatibility(nvmlVgpuMetadata unsafe.Pointer, pgpuMetadata unsafe.Pointer, compatibilityInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPgpuMetadataString
func nvmlDeviceGetPgpuMetadataString(nvmlDevice unsafe.Pointer, pgpuMetadata unsafe.Pointer, bufferSize unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuSchedulerLog
func nvmlDeviceGetVgpuSchedulerLog(nvmlDevice unsafe.Pointer, pSchedulerLog unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuSchedulerState
func nvmlDeviceGetVgpuSchedulerState(nvmlDevice unsafe.Pointer, pSchedulerState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuSchedulerCapabilities
func nvmlDeviceGetVgpuSchedulerCapabilities(nvmlDevice unsafe.Pointer, pCapabilities unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetVgpuSchedulerState
func nvmlDeviceSetVgpuSchedulerState(nvmlDevice unsafe.Pointer, pSchedulerState unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGetVgpuVersion
func nvmlGetVgpuVersion(supported unsafe.Pointer, current unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlSetVgpuVersion
func nvmlSetVgpuVersion(vgpuVersion unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuUtilization
func nvmlDeviceGetVgpuUtilization(nvmlDevice unsafe.Pointer, lastSeenTimeStamp C.ulonglong, sampleValType unsafe.Pointer, vgpuInstanceSamplesCount unsafe.Pointer, utilizationSamples unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuInstancesUtilizationInfo
func nvmlDeviceGetVgpuInstancesUtilizationInfo(nvmlDevice unsafe.Pointer, vgpuUtilInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuProcessUtilization
func nvmlDeviceGetVgpuProcessUtilization(nvmlDevice unsafe.Pointer, lastSeenTimeStamp C.ulonglong, vgpuProcessSamplesCount unsafe.Pointer, utilizationSamples unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetVgpuProcessesUtilizationInfo
func nvmlDeviceGetVgpuProcessesUtilizationInfo(nvmlDevice unsafe.Pointer, vgpuProcUtilInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetAccountingMode
func nvmlVgpuInstanceGetAccountingMode(nvmlVgpuInstance unsafe.Pointer, mode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetAccountingPids
func nvmlVgpuInstanceGetAccountingPids(nvmlVgpuInstance unsafe.Pointer, count unsafe.Pointer, pids unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetAccountingStats
func nvmlVgpuInstanceGetAccountingStats(nvmlVgpuInstance unsafe.Pointer, pid C.uint, stats unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceClearAccountingPids
func nvmlVgpuInstanceClearAccountingPids(nvmlVgpuInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetLicenseInfo_v2
func nvmlVgpuInstanceGetLicenseInfo_v2(nvmlVgpuInstance unsafe.Pointer, licenseInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGetExcludedDeviceCount
func nvmlGetExcludedDeviceCount(deviceCount unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGetExcludedDeviceInfoByIndex
func nvmlGetExcludedDeviceInfoByIndex(index C.uint, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceReadWritePRM_v1
func nvmlDeviceReadWritePRM_v1(nvmlDevice unsafe.Pointer, buffer unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceSetMigMode
func nvmlDeviceSetMigMode(nvmlDevice unsafe.Pointer, mode C.uint, activationStatus unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMigMode
func nvmlDeviceGetMigMode(nvmlDevice unsafe.Pointer, currentMode unsafe.Pointer, pendingMode unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstanceProfileInfo
func nvmlDeviceGetGpuInstanceProfileInfo(nvmlDevice unsafe.Pointer, profile C.uint, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstanceProfileInfoV
func nvmlDeviceGetGpuInstanceProfileInfoV(nvmlDevice unsafe.Pointer, profile C.uint, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstanceProfileInfoByIdV
func nvmlDeviceGetGpuInstanceProfileInfoByIdV(nvmlDevice unsafe.Pointer, profileId C.uint, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstancePossiblePlacements_v2
func nvmlDeviceGetGpuInstancePossiblePlacements_v2(nvmlDevice unsafe.Pointer, profileId C.uint, placements unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstanceRemainingCapacity
func nvmlDeviceGetGpuInstanceRemainingCapacity(nvmlDevice unsafe.Pointer, profileId C.uint, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceCreateGpuInstance
func nvmlDeviceCreateGpuInstance(nvmlDevice unsafe.Pointer, profileId C.uint, nvmlGpuInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceCreateGpuInstanceWithPlacement
func nvmlDeviceCreateGpuInstanceWithPlacement(nvmlDevice unsafe.Pointer, profileId C.uint, placement unsafe.Pointer, nvmlGpuInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceDestroy
func nvmlGpuInstanceDestroy(nvmlGpuInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstances
func nvmlDeviceGetGpuInstances(nvmlDevice unsafe.Pointer, profileId C.uint, gpuInstances unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstanceById
func nvmlDeviceGetGpuInstanceById(nvmlDevice unsafe.Pointer, id C.uint, nvmlGpuInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetInfo
func nvmlGpuInstanceGetInfo(nvmlGpuInstance unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetComputeInstanceProfileInfo
func nvmlGpuInstanceGetComputeInstanceProfileInfo(nvmlGpuInstance unsafe.Pointer, profile C.uint, engProfile C.uint, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetComputeInstanceProfileInfoV
func nvmlGpuInstanceGetComputeInstanceProfileInfoV(nvmlGpuInstance unsafe.Pointer, profile C.uint, engProfile C.uint, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetComputeInstanceRemainingCapacity
func nvmlGpuInstanceGetComputeInstanceRemainingCapacity(nvmlGpuInstance unsafe.Pointer, profileId C.uint, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetComputeInstancePossiblePlacements
func nvmlGpuInstanceGetComputeInstancePossiblePlacements(nvmlGpuInstance unsafe.Pointer, profileId C.uint, placements unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceCreateComputeInstance
func nvmlGpuInstanceCreateComputeInstance(nvmlGpuInstance unsafe.Pointer, profileId C.uint, nvmlComputeInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceCreateComputeInstanceWithPlacement
func nvmlGpuInstanceCreateComputeInstanceWithPlacement(nvmlGpuInstance unsafe.Pointer, profileId C.uint, placement unsafe.Pointer, nvmlComputeInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlComputeInstanceDestroy
func nvmlComputeInstanceDestroy(nvmlComputeInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetComputeInstances
func nvmlGpuInstanceGetComputeInstances(nvmlGpuInstance unsafe.Pointer, profileId C.uint, computeInstances unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpuInstanceGetComputeInstanceById
func nvmlGpuInstanceGetComputeInstanceById(nvmlGpuInstance unsafe.Pointer, id C.uint, nvmlComputeInstance unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlComputeInstanceGetInfo_v2
func nvmlComputeInstanceGetInfo_v2(nvmlComputeInstance unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceIsMigDeviceHandle
func nvmlDeviceIsMigDeviceHandle(nvmlDevice unsafe.Pointer, isMigDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstanceId
func nvmlDeviceGetGpuInstanceId(nvmlDevice unsafe.Pointer, id unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetComputeInstanceId
func nvmlDeviceGetComputeInstanceId(nvmlDevice unsafe.Pointer, id unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMaxMigDeviceCount
func nvmlDeviceGetMaxMigDeviceCount(nvmlDevice unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMigDeviceHandleByIndex
func nvmlDeviceGetMigDeviceHandleByIndex(nvmlDevice unsafe.Pointer, index C.uint, migDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDeviceHandleFromMigDeviceHandle
func nvmlDeviceGetDeviceHandleFromMigDeviceHandle(migDevice unsafe.Pointer, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmMetricsGet
func nvmlGpmMetricsGet(metricsGet unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmSampleFree
func nvmlGpmSampleFree(nvmlGpmSample unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmSampleAlloc
func nvmlGpmSampleAlloc(nvmlGpmSample unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmSampleGet
func nvmlGpmSampleGet(nvmlDevice unsafe.Pointer, nvmlGpmSample unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmMigSampleGet
func nvmlGpmMigSampleGet(nvmlDevice unsafe.Pointer, gpuInstanceId C.uint, nvmlGpmSample unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmQueryDeviceSupport
func nvmlGpmQueryDeviceSupport(nvmlDevice unsafe.Pointer, gpmSupport unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmQueryIfStreamingEnabled
func nvmlGpmQueryIfStreamingEnabled(nvmlDevice unsafe.Pointer, state unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlGpmSetStreamingEnabled
func nvmlGpmSetStreamingEnabled(nvmlDevice unsafe.Pointer, state C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCapabilities
func nvmlDeviceGetCapabilities(nvmlDevice unsafe.Pointer, caps unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceWorkloadPowerProfileGetProfilesInfo
func nvmlDeviceWorkloadPowerProfileGetProfilesInfo(nvmlDevice unsafe.Pointer, profilesInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceWorkloadPowerProfileGetCurrentProfiles
func nvmlDeviceWorkloadPowerProfileGetCurrentProfiles(nvmlDevice unsafe.Pointer, currentProfiles unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceWorkloadPowerProfileSetRequestedProfiles
func nvmlDeviceWorkloadPowerProfileSetRequestedProfiles(nvmlDevice unsafe.Pointer, requestedProfiles unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceWorkloadPowerProfileClearRequestedProfiles
func nvmlDeviceWorkloadPowerProfileClearRequestedProfiles(nvmlDevice unsafe.Pointer, requestedProfiles unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDevicePowerSmoothingActivatePresetProfile
func nvmlDevicePowerSmoothingActivatePresetProfile(nvmlDevice unsafe.Pointer, profile unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDevicePowerSmoothingUpdatePresetProfileParam
func nvmlDevicePowerSmoothingUpdatePresetProfileParam(nvmlDevice unsafe.Pointer, profile unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDevicePowerSmoothingSetState
func nvmlDevicePowerSmoothingSetState(nvmlDevice unsafe.Pointer, state unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts
func nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts(nvmlDevice unsafe.Pointer, errorCounts unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlInit_v1
func nvmlInit_v1() C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetCount_v1
func nvmlDeviceGetCount_v1(deviceCount unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetHandleByIndex_v1
func nvmlDeviceGetHandleByIndex_v1(index C.uint, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetHandleByPciBusId_v1
func nvmlDeviceGetHandleByPciBusId_v1(pciBusId *C.char, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	goPciBusId := C.GoString(pciBusId)
	handle, ret := engine.GetEngine().DeviceGetHandleByPciBusId(goPciBusId)
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
	}
	return toReturn(ret)
}

//export nvmlDeviceGetPciInfo_v1
func nvmlDeviceGetPciInfo_v1(nvmlDevice unsafe.Pointer, pci unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetPciInfo_v2
func nvmlDeviceGetPciInfo_v2(nvmlDevice unsafe.Pointer, pci unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetNvLinkRemotePciInfo_v1
func nvmlDeviceGetNvLinkRemotePciInfo_v1(nvmlDevice unsafe.Pointer, link C.uint, pci unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGridLicensableFeatures_v1
func nvmlDeviceGetGridLicensableFeatures_v1(nvmlDevice unsafe.Pointer, pGridLicensableFeatures unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGridLicensableFeatures_v2
func nvmlDeviceGetGridLicensableFeatures_v2(nvmlDevice unsafe.Pointer, pGridLicensableFeatures unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGridLicensableFeatures_v3
func nvmlDeviceGetGridLicensableFeatures_v3(nvmlDevice unsafe.Pointer, pGridLicensableFeatures unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceRemoveGpu_v1
func nvmlDeviceRemoveGpu_v1(pciInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlEventSetWait_v1
func nvmlEventSetWait_v1(set unsafe.Pointer, data unsafe.Pointer, timeoutms C.uint) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetAttributes_v1
func nvmlDeviceGetAttributes_v1(nvmlDevice unsafe.Pointer, attributes unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlComputeInstanceGetInfo_v1
func nvmlComputeInstanceGetInfo_v1(nvmlComputeInstance unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetComputeRunningProcesses_v1
func nvmlDeviceGetComputeRunningProcesses_v1(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetComputeRunningProcesses_v2
func nvmlDeviceGetComputeRunningProcesses_v2(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGraphicsRunningProcesses_v1
func nvmlDeviceGetGraphicsRunningProcesses_v1(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGraphicsRunningProcesses_v2
func nvmlDeviceGetGraphicsRunningProcesses_v2(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v1
func nvmlDeviceGetMPSComputeRunningProcesses_v1(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v2
func nvmlDeviceGetMPSComputeRunningProcesses_v2(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstancePossiblePlacements_v1
func nvmlDeviceGetGpuInstancePossiblePlacements_v1(nvmlDevice unsafe.Pointer, profileId C.uint, placements unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlVgpuInstanceGetLicenseInfo_v1
func nvmlVgpuInstanceGetLicenseInfo_v1(nvmlVgpuInstance unsafe.Pointer, licenseInfo unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetDriverModel_v1
func nvmlDeviceGetDriverModel_v1(nvmlDevice unsafe.Pointer, current unsafe.Pointer, pending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}
