// Code generated by cmd/generate-bridge. DO NOT EDIT.
// Copyright (c) 2025-2026, NVIDIA CORPORATION.  All rights reserved.
//
// This file contains stub implementations for NVML functions that are
// not yet implemented in hand-written files.
//
// To implement a function, add it to one of the implementation files
// (init.go, device.go, device_info.go, system.go) and regenerate this file.
// The generator will automatically detect the new implementation and
// remove the stub.

package main

/*
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// Include NVML type definitions for strict ABI compatibility.
#include "nvml_types.h"
*/
import "C"

// 366 stub functions for unimplemented NVML functions.
// These return NVML_ERROR_NOT_SUPPORTED (3).

//export nvmlComputeInstanceDestroy
func nvmlComputeInstanceDestroy(computeInstance C.nvmlComputeInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlComputeInstanceDestroy")
}

//export nvmlComputeInstanceGetInfo_v1
func nvmlComputeInstanceGetInfo_v1(computeInstance C.nvmlComputeInstance_t, info *C.nvmlComputeInstanceInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlComputeInstanceGetInfo_v1")
}

//export nvmlComputeInstanceGetInfo_v2
func nvmlComputeInstanceGetInfo_v2(computeInstance C.nvmlComputeInstance_t, info *C.nvmlComputeInstanceInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlComputeInstanceGetInfo_v2")
}

//export nvmlDeviceClearAccountingPids
func nvmlDeviceClearAccountingPids(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearAccountingPids")
}

//export nvmlDeviceClearCpuAffinity
func nvmlDeviceClearCpuAffinity(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearCpuAffinity")
}

//export nvmlDeviceClearEccErrorCounts
func nvmlDeviceClearEccErrorCounts(device C.nvmlDevice_t, counterType C.nvmlEccCounterType_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearEccErrorCounts")
}

//export nvmlDeviceClearFieldValues
func nvmlDeviceClearFieldValues(device C.nvmlDevice_t, valuesCount C.int, values *C.nvmlFieldValue_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearFieldValues")
}

//export nvmlDeviceCreateGpuInstance
func nvmlDeviceCreateGpuInstance(device C.nvmlDevice_t, profileId C.uint, gpuInstance *C.nvmlGpuInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceCreateGpuInstance")
}

//export nvmlDeviceCreateGpuInstanceWithPlacement
func nvmlDeviceCreateGpuInstanceWithPlacement(device C.nvmlDevice_t, profileId C.uint, placement *C.nvmlGpuInstancePlacement_t, gpuInstance *C.nvmlGpuInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceCreateGpuInstanceWithPlacement")
}

//export nvmlDeviceDiscoverGpus
func nvmlDeviceDiscoverGpus(pciInfo *C.nvmlPciInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceDiscoverGpus")
}

//export nvmlDeviceFreezeNvLinkUtilizationCounter
func nvmlDeviceFreezeNvLinkUtilizationCounter(device C.nvmlDevice_t, link C.uint, counter C.uint, freeze C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceFreezeNvLinkUtilizationCounter")
}

//export nvmlDeviceGetAPIRestriction
func nvmlDeviceGetAPIRestriction(device C.nvmlDevice_t, apiType C.nvmlRestrictedAPI_t, isRestricted *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAPIRestriction")
}

//export nvmlDeviceGetAccountingBufferSize
func nvmlDeviceGetAccountingBufferSize(device C.nvmlDevice_t, bufferSize *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingBufferSize")
}

//export nvmlDeviceGetAccountingMode
func nvmlDeviceGetAccountingMode(device C.nvmlDevice_t, mode *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingMode")
}

//export nvmlDeviceGetAccountingPids
func nvmlDeviceGetAccountingPids(device C.nvmlDevice_t, count *C.uint, pids *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingPids")
}

//export nvmlDeviceGetAccountingStats
func nvmlDeviceGetAccountingStats(device C.nvmlDevice_t, pid C.uint, stats *C.nvmlAccountingStats_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingStats")
}

//export nvmlDeviceGetActiveVgpus
func nvmlDeviceGetActiveVgpus(device C.nvmlDevice_t, vgpuCount *C.uint, vgpuInstances *C.nvmlVgpuInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetActiveVgpus")
}

//export nvmlDeviceGetAdaptiveClockInfoStatus
func nvmlDeviceGetAdaptiveClockInfoStatus(device C.nvmlDevice_t, adaptiveClockStatus *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAdaptiveClockInfoStatus")
}

//export nvmlDeviceGetAddressingMode
func nvmlDeviceGetAddressingMode(device C.nvmlDevice_t, mode *C.nvmlDeviceAddressingMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAddressingMode")
}

//export nvmlDeviceGetApplicationsClock
func nvmlDeviceGetApplicationsClock(device C.nvmlDevice_t, clockType C.nvmlClockType_t, clockMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetApplicationsClock")
}

//export nvmlDeviceGetAttributes_v1
func nvmlDeviceGetAttributes_v1(device C.nvmlDevice_t, attributes *C.nvmlDeviceAttributes_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAttributes_v1")
}

//export nvmlDeviceGetAttributes_v2
func nvmlDeviceGetAttributes_v2(device C.nvmlDevice_t, attributes *C.nvmlDeviceAttributes_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAttributes_v2")
}

//export nvmlDeviceGetAutoBoostedClocksEnabled
func nvmlDeviceGetAutoBoostedClocksEnabled(device C.nvmlDevice_t, isEnabled *C.nvmlEnableState_t, defaultIsEnabled *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAutoBoostedClocksEnabled")
}

//export nvmlDeviceGetBAR1MemoryInfo
func nvmlDeviceGetBAR1MemoryInfo(device C.nvmlDevice_t, bar1Memory *C.nvmlBAR1Memory_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBAR1MemoryInfo")
}

//export nvmlDeviceGetBoardId
func nvmlDeviceGetBoardId(device C.nvmlDevice_t, boardId *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBoardId")
}

//export nvmlDeviceGetBoardPartNumber
func nvmlDeviceGetBoardPartNumber(device C.nvmlDevice_t, partNumber *C.char, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBoardPartNumber")
}

//export nvmlDeviceGetBridgeChipInfo
func nvmlDeviceGetBridgeChipInfo(device C.nvmlDevice_t, bridgeHierarchy *C.nvmlBridgeChipHierarchy_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBridgeChipInfo")
}

//export nvmlDeviceGetBusType
func nvmlDeviceGetBusType(device C.nvmlDevice_t, _type *C.nvmlBusType_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBusType")
}

//export nvmlDeviceGetC2cModeInfoV
func nvmlDeviceGetC2cModeInfoV(device C.nvmlDevice_t, c2cModeInfo *C.nvmlC2cModeInfo_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetC2cModeInfoV")
}

//export nvmlDeviceGetCapabilities
func nvmlDeviceGetCapabilities(device C.nvmlDevice_t, caps *C.nvmlDeviceCapabilities_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCapabilities")
}

//export nvmlDeviceGetClkMonStatus
func nvmlDeviceGetClkMonStatus(device C.nvmlDevice_t, status *C.nvmlClkMonStatus_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClkMonStatus")
}

//export nvmlDeviceGetClock
func nvmlDeviceGetClock(device C.nvmlDevice_t, clockType C.nvmlClockType_t, clockId C.nvmlClockId_t, clockMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClock")
}

//export nvmlDeviceGetClockInfo
func nvmlDeviceGetClockInfo(device C.nvmlDevice_t, _type C.nvmlClockType_t, clock *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClockInfo")
}

//export nvmlDeviceGetClockOffsets
func nvmlDeviceGetClockOffsets(device C.nvmlDevice_t, info *C.nvmlClockOffset_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClockOffsets")
}

//export nvmlDeviceGetComputeInstanceId
func nvmlDeviceGetComputeInstanceId(device C.nvmlDevice_t, id *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeInstanceId")
}

//export nvmlDeviceGetComputeMode
func nvmlDeviceGetComputeMode(device C.nvmlDevice_t, mode *C.nvmlComputeMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeMode")
}

//export nvmlDeviceGetComputeRunningProcesses_v1
func nvmlDeviceGetComputeRunningProcesses_v1(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeRunningProcesses_v1")
}

//export nvmlDeviceGetComputeRunningProcesses_v2
func nvmlDeviceGetComputeRunningProcesses_v2(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeRunningProcesses_v2")
}

//export nvmlDeviceGetComputeRunningProcesses_v3
func nvmlDeviceGetComputeRunningProcesses_v3(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeRunningProcesses_v3")
}

//export nvmlDeviceGetConfComputeGpuAttestationReport
func nvmlDeviceGetConfComputeGpuAttestationReport(device C.nvmlDevice_t, gpuAtstReport *C.nvmlConfComputeGpuAttestationReport_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeGpuAttestationReport")
}

//export nvmlDeviceGetConfComputeGpuCertificate
func nvmlDeviceGetConfComputeGpuCertificate(device C.nvmlDevice_t, gpuCert *C.nvmlConfComputeGpuCertificate_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeGpuCertificate")
}

//export nvmlDeviceGetConfComputeMemSizeInfo
func nvmlDeviceGetConfComputeMemSizeInfo(device C.nvmlDevice_t, memInfo *C.nvmlConfComputeMemSizeInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeMemSizeInfo")
}

//export nvmlDeviceGetConfComputeProtectedMemoryUsage
func nvmlDeviceGetConfComputeProtectedMemoryUsage(device C.nvmlDevice_t, memory *C.nvmlMemory_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeProtectedMemoryUsage")
}

//export nvmlDeviceGetCoolerInfo
func nvmlDeviceGetCoolerInfo(device C.nvmlDevice_t, coolerInfo *C.nvmlCoolerInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCoolerInfo")
}

//export nvmlDeviceGetCpuAffinity
func nvmlDeviceGetCpuAffinity(device C.nvmlDevice_t, cpuSetSize C.uint, cpuSet *C.ulong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCpuAffinity")
}

//export nvmlDeviceGetCpuAffinityWithinScope
func nvmlDeviceGetCpuAffinityWithinScope(device C.nvmlDevice_t, cpuSetSize C.uint, cpuSet *C.ulong, scope C.nvmlAffinityScope_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCpuAffinityWithinScope")
}

//export nvmlDeviceGetCreatableVgpus
func nvmlDeviceGetCreatableVgpus(device C.nvmlDevice_t, vgpuCount *C.uint, vgpuTypeIds *C.nvmlVgpuTypeId_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCreatableVgpus")
}

//export nvmlDeviceGetCurrPcieLinkGeneration
func nvmlDeviceGetCurrPcieLinkGeneration(device C.nvmlDevice_t, currLinkGen *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrPcieLinkGeneration")
}

//export nvmlDeviceGetCurrPcieLinkWidth
func nvmlDeviceGetCurrPcieLinkWidth(device C.nvmlDevice_t, currLinkWidth *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrPcieLinkWidth")
}

//export nvmlDeviceGetCurrentClockFreqs
func nvmlDeviceGetCurrentClockFreqs(device C.nvmlDevice_t, currentClockFreqs *C.nvmlDeviceCurrentClockFreqs_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrentClockFreqs")
}

//export nvmlDeviceGetCurrentClocksEventReasons
func nvmlDeviceGetCurrentClocksEventReasons(device C.nvmlDevice_t, clocksEventReasons *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrentClocksEventReasons")
}

//export nvmlDeviceGetCurrentClocksThrottleReasons
func nvmlDeviceGetCurrentClocksThrottleReasons(device C.nvmlDevice_t, clocksThrottleReasons *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrentClocksThrottleReasons")
}

//export nvmlDeviceGetDecoderUtilization
func nvmlDeviceGetDecoderUtilization(device C.nvmlDevice_t, utilization *C.uint, samplingPeriodUs *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDecoderUtilization")
}

//export nvmlDeviceGetDefaultApplicationsClock
func nvmlDeviceGetDefaultApplicationsClock(device C.nvmlDevice_t, clockType C.nvmlClockType_t, clockMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDefaultApplicationsClock")
}

//export nvmlDeviceGetDefaultEccMode
func nvmlDeviceGetDefaultEccMode(device C.nvmlDevice_t, defaultMode *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDefaultEccMode")
}

//export nvmlDeviceGetDetailedEccErrors
func nvmlDeviceGetDetailedEccErrors(device C.nvmlDevice_t, errorType C.nvmlMemoryErrorType_t, counterType C.nvmlEccCounterType_t, eccCounts *C.nvmlEccErrorCounts_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDetailedEccErrors")
}

//export nvmlDeviceGetDeviceHandleFromMigDeviceHandle
func nvmlDeviceGetDeviceHandleFromMigDeviceHandle(migDevice C.nvmlDevice_t, device *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDeviceHandleFromMigDeviceHandle")
}

//export nvmlDeviceGetDisplayActive
func nvmlDeviceGetDisplayActive(device C.nvmlDevice_t, isActive *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDisplayActive")
}

//export nvmlDeviceGetDisplayMode
func nvmlDeviceGetDisplayMode(device C.nvmlDevice_t, display *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDisplayMode")
}

//export nvmlDeviceGetDramEncryptionMode
func nvmlDeviceGetDramEncryptionMode(device C.nvmlDevice_t, current *C.nvmlDramEncryptionInfo_t, pending *C.nvmlDramEncryptionInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDramEncryptionMode")
}

//export nvmlDeviceGetDriverModel_v1
func nvmlDeviceGetDriverModel_v1(device C.nvmlDevice_t, current *C.nvmlDriverModel_t, pending *C.nvmlDriverModel_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDriverModel_v1")
}

//export nvmlDeviceGetDriverModel_v2
func nvmlDeviceGetDriverModel_v2(device C.nvmlDevice_t, current *C.nvmlDriverModel_t, pending *C.nvmlDriverModel_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDriverModel_v2")
}

//export nvmlDeviceGetDynamicPstatesInfo
func nvmlDeviceGetDynamicPstatesInfo(device C.nvmlDevice_t, pDynamicPstatesInfo *C.nvmlGpuDynamicPstatesInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDynamicPstatesInfo")
}

//export nvmlDeviceGetEccMode
func nvmlDeviceGetEccMode(device C.nvmlDevice_t, current *C.nvmlEnableState_t, pending *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEccMode")
}

//export nvmlDeviceGetEncoderCapacity
func nvmlDeviceGetEncoderCapacity(device C.nvmlDevice_t, encoderQueryType C.nvmlEncoderType_t, encoderCapacity *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderCapacity")
}

//export nvmlDeviceGetEncoderSessions
func nvmlDeviceGetEncoderSessions(device C.nvmlDevice_t, sessionCount *C.uint, sessionInfos *C.nvmlEncoderSessionInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderSessions")
}

//export nvmlDeviceGetEncoderStats
func nvmlDeviceGetEncoderStats(device C.nvmlDevice_t, sessionCount *C.uint, averageFps *C.uint, averageLatency *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderStats")
}

//export nvmlDeviceGetEncoderUtilization
func nvmlDeviceGetEncoderUtilization(device C.nvmlDevice_t, utilization *C.uint, samplingPeriodUs *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderUtilization")
}

//export nvmlDeviceGetEnforcedPowerLimit
func nvmlDeviceGetEnforcedPowerLimit(device C.nvmlDevice_t, limit *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEnforcedPowerLimit")
}

//export nvmlDeviceGetFBCSessions
func nvmlDeviceGetFBCSessions(device C.nvmlDevice_t, sessionCount *C.uint, sessionInfo *C.nvmlFBCSessionInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFBCSessions")
}

//export nvmlDeviceGetFBCStats
func nvmlDeviceGetFBCStats(device C.nvmlDevice_t, fbcStats *C.nvmlFBCStats_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFBCStats")
}

//export nvmlDeviceGetFanControlPolicy_v2
func nvmlDeviceGetFanControlPolicy_v2(device C.nvmlDevice_t, fan C.uint, policy *C.nvmlFanControlPolicy_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanControlPolicy_v2")
}

//export nvmlDeviceGetFanSpeed
func nvmlDeviceGetFanSpeed(device C.nvmlDevice_t, speed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanSpeed")
}

//export nvmlDeviceGetFanSpeedRPM
func nvmlDeviceGetFanSpeedRPM(device C.nvmlDevice_t, fanSpeed *C.nvmlFanSpeedInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanSpeedRPM")
}

//export nvmlDeviceGetFanSpeed_v2
func nvmlDeviceGetFanSpeed_v2(device C.nvmlDevice_t, fan C.uint, speed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanSpeed_v2")
}

//export nvmlDeviceGetFieldValues
func nvmlDeviceGetFieldValues(device C.nvmlDevice_t, valuesCount C.int, values *C.nvmlFieldValue_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFieldValues")
}

//export nvmlDeviceGetGpcClkMinMaxVfOffset
func nvmlDeviceGetGpcClkMinMaxVfOffset(device C.nvmlDevice_t, minOffset *C.int, maxOffset *C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpcClkMinMaxVfOffset")
}

//export nvmlDeviceGetGpcClkVfOffset
func nvmlDeviceGetGpcClkVfOffset(device C.nvmlDevice_t, offset *C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpcClkVfOffset")
}

//export nvmlDeviceGetGpuFabricInfo
func nvmlDeviceGetGpuFabricInfo(device C.nvmlDevice_t, gpuFabricInfo *C.nvmlGpuFabricInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuFabricInfo")
}

//export nvmlDeviceGetGpuFabricInfoV
func nvmlDeviceGetGpuFabricInfoV(device C.nvmlDevice_t, gpuFabricInfo *C.nvmlGpuFabricInfoV_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuFabricInfoV")
}

//export nvmlDeviceGetGpuInstanceById
func nvmlDeviceGetGpuInstanceById(device C.nvmlDevice_t, id C.uint, gpuInstance *C.nvmlGpuInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceById")
}

//export nvmlDeviceGetGpuInstanceId
func nvmlDeviceGetGpuInstanceId(device C.nvmlDevice_t, id *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceId")
}

//export nvmlDeviceGetGpuInstancePossiblePlacements_v1
func nvmlDeviceGetGpuInstancePossiblePlacements_v1(device C.nvmlDevice_t, profileId C.uint, placements *C.nvmlGpuInstancePlacement_t, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstancePossiblePlacements_v1")
}

//export nvmlDeviceGetGpuInstancePossiblePlacements_v2
func nvmlDeviceGetGpuInstancePossiblePlacements_v2(device C.nvmlDevice_t, profileId C.uint, placements *C.nvmlGpuInstancePlacement_t, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstancePossiblePlacements_v2")
}

//export nvmlDeviceGetGpuInstanceProfileInfo
func nvmlDeviceGetGpuInstanceProfileInfo(device C.nvmlDevice_t, profile C.uint, info *C.nvmlGpuInstanceProfileInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceProfileInfo")
}

//export nvmlDeviceGetGpuInstanceProfileInfoByIdV
func nvmlDeviceGetGpuInstanceProfileInfoByIdV(device C.nvmlDevice_t, profileId C.uint, info *C.nvmlGpuInstanceProfileInfo_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceProfileInfoByIdV")
}

//export nvmlDeviceGetGpuInstanceProfileInfoV
func nvmlDeviceGetGpuInstanceProfileInfoV(device C.nvmlDevice_t, profile C.uint, info *C.nvmlGpuInstanceProfileInfo_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceProfileInfoV")
}

//export nvmlDeviceGetGpuInstanceRemainingCapacity
func nvmlDeviceGetGpuInstanceRemainingCapacity(device C.nvmlDevice_t, profileId C.uint, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceRemainingCapacity")
}

//export nvmlDeviceGetGpuInstances
func nvmlDeviceGetGpuInstances(device C.nvmlDevice_t, profileId C.uint, gpuInstances *C.nvmlGpuInstance_t, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstances")
}

//export nvmlDeviceGetGpuMaxPcieLinkGeneration
func nvmlDeviceGetGpuMaxPcieLinkGeneration(device C.nvmlDevice_t, maxLinkGenDevice *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuMaxPcieLinkGeneration")
}

//export nvmlDeviceGetGpuOperationMode
func nvmlDeviceGetGpuOperationMode(device C.nvmlDevice_t, current *C.nvmlGpuOperationMode_t, pending *C.nvmlGpuOperationMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuOperationMode")
}

//export nvmlDeviceGetGraphicsRunningProcesses_v1
func nvmlDeviceGetGraphicsRunningProcesses_v1(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGraphicsRunningProcesses_v1")
}

//export nvmlDeviceGetGraphicsRunningProcesses_v2
func nvmlDeviceGetGraphicsRunningProcesses_v2(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGraphicsRunningProcesses_v2")
}

//export nvmlDeviceGetGraphicsRunningProcesses_v3
func nvmlDeviceGetGraphicsRunningProcesses_v3(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGraphicsRunningProcesses_v3")
}

//export nvmlDeviceGetGridLicensableFeatures_v1
func nvmlDeviceGetGridLicensableFeatures_v1(device C.nvmlDevice_t, pGridLicensableFeatures *C.nvmlGridLicensableFeatures_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v1")
}

//export nvmlDeviceGetGridLicensableFeatures_v2
func nvmlDeviceGetGridLicensableFeatures_v2(device C.nvmlDevice_t, pGridLicensableFeatures *C.nvmlGridLicensableFeatures_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v2")
}

//export nvmlDeviceGetGridLicensableFeatures_v3
func nvmlDeviceGetGridLicensableFeatures_v3(device C.nvmlDevice_t, pGridLicensableFeatures *C.nvmlGridLicensableFeatures_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v3")
}

//export nvmlDeviceGetGridLicensableFeatures_v4
func nvmlDeviceGetGridLicensableFeatures_v4(device C.nvmlDevice_t, pGridLicensableFeatures *C.nvmlGridLicensableFeatures_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v4")
}

//export nvmlDeviceGetGspFirmwareMode
func nvmlDeviceGetGspFirmwareMode(device C.nvmlDevice_t, isEnabled *C.uint, defaultMode *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGspFirmwareMode")
}

//export nvmlDeviceGetGspFirmwareVersion
func nvmlDeviceGetGspFirmwareVersion(device C.nvmlDevice_t, version *C.char) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGspFirmwareVersion")
}

//export nvmlDeviceGetHandleBySerial
func nvmlDeviceGetHandleBySerial(serial *C.char, device *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetHandleBySerial")
}

//export nvmlDeviceGetHandleByUUIDV
func nvmlDeviceGetHandleByUUIDV(uuid *C.nvmlUUID_t, device *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetHandleByUUIDV")
}

//export nvmlDeviceGetHostVgpuMode
func nvmlDeviceGetHostVgpuMode(device C.nvmlDevice_t, pHostVgpuMode *C.nvmlHostVgpuMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetHostVgpuMode")
}

//export nvmlDeviceGetInforomConfigurationChecksum
func nvmlDeviceGetInforomConfigurationChecksum(device C.nvmlDevice_t, checksum *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetInforomConfigurationChecksum")
}

//export nvmlDeviceGetInforomImageVersion
func nvmlDeviceGetInforomImageVersion(device C.nvmlDevice_t, version *C.char, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetInforomImageVersion")
}

//export nvmlDeviceGetInforomVersion
func nvmlDeviceGetInforomVersion(device C.nvmlDevice_t, object C.nvmlInforomObject_t, version *C.char, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetInforomVersion")
}

//export nvmlDeviceGetIrqNum
func nvmlDeviceGetIrqNum(device C.nvmlDevice_t, irqNum *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetIrqNum")
}

//export nvmlDeviceGetJpgUtilization
func nvmlDeviceGetJpgUtilization(device C.nvmlDevice_t, utilization *C.uint, samplingPeriodUs *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetJpgUtilization")
}

//export nvmlDeviceGetLastBBXFlushTime
func nvmlDeviceGetLastBBXFlushTime(device C.nvmlDevice_t, timestamp *C.ulonglong, durationUs *C.ulong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetLastBBXFlushTime")
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v1
func nvmlDeviceGetMPSComputeRunningProcesses_v1(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMPSComputeRunningProcesses_v1")
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v2
func nvmlDeviceGetMPSComputeRunningProcesses_v2(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMPSComputeRunningProcesses_v2")
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v3
func nvmlDeviceGetMPSComputeRunningProcesses_v3(device C.nvmlDevice_t, infoCount *C.uint, infos *C.nvmlProcessInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMPSComputeRunningProcesses_v3")
}

//export nvmlDeviceGetMarginTemperature
func nvmlDeviceGetMarginTemperature(device C.nvmlDevice_t, marginTempInfo *C.nvmlMarginTemperature_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMarginTemperature")
}

//export nvmlDeviceGetMaxClockInfo
func nvmlDeviceGetMaxClockInfo(device C.nvmlDevice_t, _type C.nvmlClockType_t, clock *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxClockInfo")
}

//export nvmlDeviceGetMaxCustomerBoostClock
func nvmlDeviceGetMaxCustomerBoostClock(device C.nvmlDevice_t, clockType C.nvmlClockType_t, clockMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxCustomerBoostClock")
}

//export nvmlDeviceGetMaxMigDeviceCount
func nvmlDeviceGetMaxMigDeviceCount(device C.nvmlDevice_t, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxMigDeviceCount")
}

//export nvmlDeviceGetMaxPcieLinkGeneration
func nvmlDeviceGetMaxPcieLinkGeneration(device C.nvmlDevice_t, maxLinkGen *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxPcieLinkGeneration")
}

//export nvmlDeviceGetMaxPcieLinkWidth
func nvmlDeviceGetMaxPcieLinkWidth(device C.nvmlDevice_t, maxLinkWidth *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxPcieLinkWidth")
}

//export nvmlDeviceGetMemClkMinMaxVfOffset
func nvmlDeviceGetMemClkMinMaxVfOffset(device C.nvmlDevice_t, minOffset *C.int, maxOffset *C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemClkMinMaxVfOffset")
}

//export nvmlDeviceGetMemClkVfOffset
func nvmlDeviceGetMemClkVfOffset(device C.nvmlDevice_t, offset *C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemClkVfOffset")
}

//export nvmlDeviceGetMemoryAffinity
func nvmlDeviceGetMemoryAffinity(device C.nvmlDevice_t, nodeSetSize C.uint, nodeSet *C.ulong, scope C.nvmlAffinityScope_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemoryAffinity")
}

//export nvmlDeviceGetMemoryBusWidth
func nvmlDeviceGetMemoryBusWidth(device C.nvmlDevice_t, busWidth *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemoryBusWidth")
}

//export nvmlDeviceGetMemoryErrorCounter
func nvmlDeviceGetMemoryErrorCounter(device C.nvmlDevice_t, errorType C.nvmlMemoryErrorType_t, counterType C.nvmlEccCounterType_t, locationType C.nvmlMemoryLocation_t, count *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemoryErrorCounter")
}

//export nvmlDeviceGetMigDeviceHandleByIndex
func nvmlDeviceGetMigDeviceHandleByIndex(device C.nvmlDevice_t, index C.uint, migDevice *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMigDeviceHandleByIndex")
}

//export nvmlDeviceGetMinMaxClockOfPState
func nvmlDeviceGetMinMaxClockOfPState(device C.nvmlDevice_t, _type C.nvmlClockType_t, pstate C.nvmlPstates_t, minClockMHz *C.uint, maxClockMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMinMaxClockOfPState")
}

//export nvmlDeviceGetMinMaxFanSpeed
func nvmlDeviceGetMinMaxFanSpeed(device C.nvmlDevice_t, minSpeed *C.uint, maxSpeed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMinMaxFanSpeed")
}

//export nvmlDeviceGetModuleId
func nvmlDeviceGetModuleId(device C.nvmlDevice_t, moduleId *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetModuleId")
}

//export nvmlDeviceGetMultiGpuBoard
func nvmlDeviceGetMultiGpuBoard(device C.nvmlDevice_t, multiGpuBool *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMultiGpuBoard")
}

//export nvmlDeviceGetNumFans
func nvmlDeviceGetNumFans(device C.nvmlDevice_t, numFans *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNumFans")
}

//export nvmlDeviceGetNumGpuCores
func nvmlDeviceGetNumGpuCores(device C.nvmlDevice_t, numCores *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNumGpuCores")
}

//export nvmlDeviceGetNumaNodeId
func nvmlDeviceGetNumaNodeId(device C.nvmlDevice_t, node *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNumaNodeId")
}

//export nvmlDeviceGetNvLinkCapability
func nvmlDeviceGetNvLinkCapability(device C.nvmlDevice_t, link C.uint, capability C.nvmlNvLinkCapability_t, capResult *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkCapability")
}

//export nvmlDeviceGetNvLinkErrorCounter
func nvmlDeviceGetNvLinkErrorCounter(device C.nvmlDevice_t, link C.uint, counter C.nvmlNvLinkErrorCounter_t, counterValue *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkErrorCounter")
}

//export nvmlDeviceGetNvLinkInfo
func nvmlDeviceGetNvLinkInfo(device C.nvmlDevice_t, info *C.nvmlNvLinkInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkInfo")
}

//export nvmlDeviceGetNvLinkRemoteDeviceType
func nvmlDeviceGetNvLinkRemoteDeviceType(device C.nvmlDevice_t, link C.uint, pNvLinkDeviceType *C.nvmlIntNvLinkDeviceType_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkRemoteDeviceType")
}

//export nvmlDeviceGetNvLinkRemotePciInfo_v1
func nvmlDeviceGetNvLinkRemotePciInfo_v1(device C.nvmlDevice_t, link C.uint, pci *C.nvmlPciInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkRemotePciInfo_v1")
}

//export nvmlDeviceGetNvLinkRemotePciInfo_v2
func nvmlDeviceGetNvLinkRemotePciInfo_v2(device C.nvmlDevice_t, link C.uint, pci *C.nvmlPciInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkRemotePciInfo_v2")
}

//export nvmlDeviceGetNvLinkState
func nvmlDeviceGetNvLinkState(device C.nvmlDevice_t, link C.uint, isActive *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkState")
}

//export nvmlDeviceGetNvLinkUtilizationControl
func nvmlDeviceGetNvLinkUtilizationControl(device C.nvmlDevice_t, link C.uint, counter C.uint, control *C.nvmlNvLinkUtilizationControl_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkUtilizationControl")
}

//export nvmlDeviceGetNvLinkUtilizationCounter
func nvmlDeviceGetNvLinkUtilizationCounter(device C.nvmlDevice_t, link C.uint, counter C.uint, rxcounter *C.ulonglong, txcounter *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkUtilizationCounter")
}

//export nvmlDeviceGetNvLinkVersion
func nvmlDeviceGetNvLinkVersion(device C.nvmlDevice_t, link C.uint, version *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkVersion")
}

//export nvmlDeviceGetNvlinkBwMode
func nvmlDeviceGetNvlinkBwMode(device C.nvmlDevice_t, getBwMode *C.nvmlNvlinkGetBwMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvlinkBwMode")
}

//export nvmlDeviceGetNvlinkSupportedBwModes
func nvmlDeviceGetNvlinkSupportedBwModes(device C.nvmlDevice_t, supportedBwMode *C.nvmlNvlinkSupportedBwModes_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvlinkSupportedBwModes")
}

//export nvmlDeviceGetOfaUtilization
func nvmlDeviceGetOfaUtilization(device C.nvmlDevice_t, utilization *C.uint, samplingPeriodUs *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetOfaUtilization")
}

//export nvmlDeviceGetP2PStatus
func nvmlDeviceGetP2PStatus(device1 C.nvmlDevice_t, device2 C.nvmlDevice_t, p2pIndex C.nvmlGpuP2PCapsIndex_t, p2pStatus *C.nvmlGpuP2PStatus_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetP2PStatus")
}

//export nvmlDeviceGetPciInfoExt
func nvmlDeviceGetPciInfoExt(device C.nvmlDevice_t, pci *C.nvmlPciInfoExt_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPciInfoExt")
}

//export nvmlDeviceGetPcieLinkMaxSpeed
func nvmlDeviceGetPcieLinkMaxSpeed(device C.nvmlDevice_t, maxSpeed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieLinkMaxSpeed")
}

//export nvmlDeviceGetPcieReplayCounter
func nvmlDeviceGetPcieReplayCounter(device C.nvmlDevice_t, value *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieReplayCounter")
}

//export nvmlDeviceGetPcieSpeed
func nvmlDeviceGetPcieSpeed(device C.nvmlDevice_t, pcieSpeed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieSpeed")
}

//export nvmlDeviceGetPcieThroughput
func nvmlDeviceGetPcieThroughput(device C.nvmlDevice_t, counter C.nvmlPcieUtilCounter_t, value *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieThroughput")
}

//export nvmlDeviceGetPdi
func nvmlDeviceGetPdi(device C.nvmlDevice_t, pdi *C.nvmlPdi_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPdi")
}

//export nvmlDeviceGetPerformanceModes
func nvmlDeviceGetPerformanceModes(device C.nvmlDevice_t, perfModes *C.nvmlDevicePerfModes_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPerformanceModes")
}

//export nvmlDeviceGetPerformanceState
func nvmlDeviceGetPerformanceState(device C.nvmlDevice_t, pState *C.nvmlPstates_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPerformanceState")
}

//export nvmlDeviceGetPersistenceMode
func nvmlDeviceGetPersistenceMode(device C.nvmlDevice_t, mode *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPersistenceMode")
}

//export nvmlDeviceGetPgpuMetadataString
func nvmlDeviceGetPgpuMetadataString(device C.nvmlDevice_t, pgpuMetadata *C.char, bufferSize *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPgpuMetadataString")
}

//export nvmlDeviceGetPlatformInfo
func nvmlDeviceGetPlatformInfo(device C.nvmlDevice_t, platformInfo *C.nvmlPlatformInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPlatformInfo")
}

//export nvmlDeviceGetPowerManagementDefaultLimit
func nvmlDeviceGetPowerManagementDefaultLimit(device C.nvmlDevice_t, defaultLimit *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementDefaultLimit")
}

//export nvmlDeviceGetPowerManagementLimit
func nvmlDeviceGetPowerManagementLimit(device C.nvmlDevice_t, limit *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementLimit")
}

//export nvmlDeviceGetPowerManagementLimitConstraints
func nvmlDeviceGetPowerManagementLimitConstraints(device C.nvmlDevice_t, minLimit *C.uint, maxLimit *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementLimitConstraints")
}

//export nvmlDeviceGetPowerManagementMode
func nvmlDeviceGetPowerManagementMode(device C.nvmlDevice_t, mode *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementMode")
}

//export nvmlDeviceGetPowerMizerMode_v1
func nvmlDeviceGetPowerMizerMode_v1(device C.nvmlDevice_t, powerMizerMode *C.nvmlDevicePowerMizerModes_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerMizerMode_v1")
}

//export nvmlDeviceGetPowerSource
func nvmlDeviceGetPowerSource(device C.nvmlDevice_t, powerSource *C.nvmlPowerSource_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerSource")
}

//export nvmlDeviceGetPowerState
func nvmlDeviceGetPowerState(device C.nvmlDevice_t, pState *C.nvmlPstates_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerState")
}

//export nvmlDeviceGetPowerUsage
func nvmlDeviceGetPowerUsage(device C.nvmlDevice_t, power *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerUsage")
}

//export nvmlDeviceGetProcessUtilization
func nvmlDeviceGetProcessUtilization(device C.nvmlDevice_t, utilization *C.nvmlProcessUtilizationSample_t, processSamplesCount *C.uint, lastSeenTimeStamp C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetProcessUtilization")
}

//export nvmlDeviceGetProcessesUtilizationInfo
func nvmlDeviceGetProcessesUtilizationInfo(device C.nvmlDevice_t, procesesUtilInfo *C.nvmlProcessesUtilizationInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetProcessesUtilizationInfo")
}

//export nvmlDeviceGetRemappedRows
func nvmlDeviceGetRemappedRows(device C.nvmlDevice_t, corrRows *C.uint, uncRows *C.uint, isPending *C.uint, failureOccurred *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRemappedRows")
}

//export nvmlDeviceGetRepairStatus
func nvmlDeviceGetRepairStatus(device C.nvmlDevice_t, repairStatus *C.nvmlRepairStatus_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRepairStatus")
}

//export nvmlDeviceGetRetiredPages
func nvmlDeviceGetRetiredPages(device C.nvmlDevice_t, cause C.nvmlPageRetirementCause_t, pageCount *C.uint, addresses *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRetiredPages")
}

//export nvmlDeviceGetRetiredPagesPendingStatus
func nvmlDeviceGetRetiredPagesPendingStatus(device C.nvmlDevice_t, isPending *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRetiredPagesPendingStatus")
}

//export nvmlDeviceGetRetiredPages_v2
func nvmlDeviceGetRetiredPages_v2(device C.nvmlDevice_t, cause C.nvmlPageRetirementCause_t, pageCount *C.uint, addresses *C.ulonglong, timestamps *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRetiredPages_v2")
}

//export nvmlDeviceGetRowRemapperHistogram
func nvmlDeviceGetRowRemapperHistogram(device C.nvmlDevice_t, values *C.nvmlRowRemapperHistogramValues_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRowRemapperHistogram")
}

//export nvmlDeviceGetRunningProcessDetailList
func nvmlDeviceGetRunningProcessDetailList(device C.nvmlDevice_t, plist *C.nvmlProcessDetailList_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRunningProcessDetailList")
}

//export nvmlDeviceGetSamples
func nvmlDeviceGetSamples(device C.nvmlDevice_t, _type C.nvmlSamplingType_t, lastSeenTimeStamp C.ulonglong, sampleValType *C.nvmlValueType_t, sampleCount *C.uint, samples *C.nvmlSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSamples")
}

//export nvmlDeviceGetSramEccErrorStatus
func nvmlDeviceGetSramEccErrorStatus(device C.nvmlDevice_t, status *C.nvmlEccSramErrorStatus_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSramEccErrorStatus")
}

//export nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts
func nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts(device C.nvmlDevice_t, errorCounts *C.nvmlEccSramUniqueUncorrectedErrorCounts_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts")
}

//export nvmlDeviceGetSupportedClocksEventReasons
func nvmlDeviceGetSupportedClocksEventReasons(device C.nvmlDevice_t, supportedClocksEventReasons *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedClocksEventReasons")
}

//export nvmlDeviceGetSupportedClocksThrottleReasons
func nvmlDeviceGetSupportedClocksThrottleReasons(device C.nvmlDevice_t, supportedClocksThrottleReasons *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedClocksThrottleReasons")
}

//export nvmlDeviceGetSupportedEventTypes
func nvmlDeviceGetSupportedEventTypes(device C.nvmlDevice_t, eventTypes *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedEventTypes")
}

//export nvmlDeviceGetSupportedGraphicsClocks
func nvmlDeviceGetSupportedGraphicsClocks(device C.nvmlDevice_t, memoryClockMHz C.uint, count *C.uint, clocksMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedGraphicsClocks")
}

//export nvmlDeviceGetSupportedMemoryClocks
func nvmlDeviceGetSupportedMemoryClocks(device C.nvmlDevice_t, count *C.uint, clocksMHz *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedMemoryClocks")
}

//export nvmlDeviceGetSupportedPerformanceStates
func nvmlDeviceGetSupportedPerformanceStates(device C.nvmlDevice_t, pstates *C.nvmlPstates_t, size C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedPerformanceStates")
}

//export nvmlDeviceGetSupportedVgpus
func nvmlDeviceGetSupportedVgpus(device C.nvmlDevice_t, vgpuCount *C.uint, vgpuTypeIds *C.nvmlVgpuTypeId_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedVgpus")
}

//export nvmlDeviceGetTargetFanSpeed
func nvmlDeviceGetTargetFanSpeed(device C.nvmlDevice_t, fan C.uint, targetSpeed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTargetFanSpeed")
}

//export nvmlDeviceGetTemperature
func nvmlDeviceGetTemperature(device C.nvmlDevice_t, sensorType C.nvmlTemperatureSensors_t, temp *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTemperature")
}

//export nvmlDeviceGetTemperatureThreshold
func nvmlDeviceGetTemperatureThreshold(device C.nvmlDevice_t, thresholdType C.nvmlTemperatureThresholds_t, temp *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTemperatureThreshold")
}

//export nvmlDeviceGetTemperatureV
func nvmlDeviceGetTemperatureV(device C.nvmlDevice_t, temperature *C.nvmlTemperature_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTemperatureV")
}

//export nvmlDeviceGetThermalSettings
func nvmlDeviceGetThermalSettings(device C.nvmlDevice_t, sensorIndex C.uint, pThermalSettings *C.nvmlGpuThermalSettings_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetThermalSettings")
}

//export nvmlDeviceGetTopologyCommonAncestor
func nvmlDeviceGetTopologyCommonAncestor(device1 C.nvmlDevice_t, device2 C.nvmlDevice_t, pathInfo *C.nvmlGpuTopologyLevel_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTopologyCommonAncestor")
}

//export nvmlDeviceGetTopologyNearestGpus
func nvmlDeviceGetTopologyNearestGpus(device C.nvmlDevice_t, level C.nvmlGpuTopologyLevel_t, count *C.uint, deviceArray *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTopologyNearestGpus")
}

//export nvmlDeviceGetTotalEccErrors
func nvmlDeviceGetTotalEccErrors(device C.nvmlDevice_t, errorType C.nvmlMemoryErrorType_t, counterType C.nvmlEccCounterType_t, eccCounts *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTotalEccErrors")
}

//export nvmlDeviceGetTotalEnergyConsumption
func nvmlDeviceGetTotalEnergyConsumption(device C.nvmlDevice_t, energy *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTotalEnergyConsumption")
}

//export nvmlDeviceGetUtilizationRates
func nvmlDeviceGetUtilizationRates(device C.nvmlDevice_t, utilization *C.nvmlUtilization_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetUtilizationRates")
}

//export nvmlDeviceGetVbiosVersion
func nvmlDeviceGetVbiosVersion(device C.nvmlDevice_t, version *C.char, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVbiosVersion")
}

//export nvmlDeviceGetVgpuCapabilities
func nvmlDeviceGetVgpuCapabilities(device C.nvmlDevice_t, capability C.nvmlDeviceVgpuCapability_t, capResult *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuCapabilities")
}

//export nvmlDeviceGetVgpuHeterogeneousMode
func nvmlDeviceGetVgpuHeterogeneousMode(device C.nvmlDevice_t, pHeterogeneousMode *C.nvmlVgpuHeterogeneousMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuHeterogeneousMode")
}

//export nvmlDeviceGetVgpuInstancesUtilizationInfo
func nvmlDeviceGetVgpuInstancesUtilizationInfo(device C.nvmlDevice_t, vgpuUtilInfo *C.nvmlVgpuInstancesUtilizationInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuInstancesUtilizationInfo")
}

//export nvmlDeviceGetVgpuMetadata
func nvmlDeviceGetVgpuMetadata(device C.nvmlDevice_t, pgpuMetadata *C.nvmlVgpuPgpuMetadata_t, bufferSize *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuMetadata")
}

//export nvmlDeviceGetVgpuProcessUtilization
func nvmlDeviceGetVgpuProcessUtilization(device C.nvmlDevice_t, lastSeenTimeStamp C.ulonglong, vgpuProcessSamplesCount *C.uint, utilizationSamples *C.nvmlVgpuProcessUtilizationSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuProcessUtilization")
}

//export nvmlDeviceGetVgpuProcessesUtilizationInfo
func nvmlDeviceGetVgpuProcessesUtilizationInfo(device C.nvmlDevice_t, vgpuProcUtilInfo *C.nvmlVgpuProcessesUtilizationInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuProcessesUtilizationInfo")
}

//export nvmlDeviceGetVgpuSchedulerCapabilities
func nvmlDeviceGetVgpuSchedulerCapabilities(device C.nvmlDevice_t, pCapabilities *C.nvmlVgpuSchedulerCapabilities_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuSchedulerCapabilities")
}

//export nvmlDeviceGetVgpuSchedulerLog
func nvmlDeviceGetVgpuSchedulerLog(device C.nvmlDevice_t, pSchedulerLog *C.nvmlVgpuSchedulerLog_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuSchedulerLog")
}

//export nvmlDeviceGetVgpuSchedulerState
func nvmlDeviceGetVgpuSchedulerState(device C.nvmlDevice_t, pSchedulerState *C.nvmlVgpuSchedulerGetState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuSchedulerState")
}

//export nvmlDeviceGetVgpuTypeCreatablePlacements
func nvmlDeviceGetVgpuTypeCreatablePlacements(device C.nvmlDevice_t, vgpuTypeId C.nvmlVgpuTypeId_t, pPlacementList *C.nvmlVgpuPlacementList_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuTypeCreatablePlacements")
}

//export nvmlDeviceGetVgpuTypeSupportedPlacements
func nvmlDeviceGetVgpuTypeSupportedPlacements(device C.nvmlDevice_t, vgpuTypeId C.nvmlVgpuTypeId_t, pPlacementList *C.nvmlVgpuPlacementList_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuTypeSupportedPlacements")
}

//export nvmlDeviceGetVgpuUtilization
func nvmlDeviceGetVgpuUtilization(device C.nvmlDevice_t, lastSeenTimeStamp C.ulonglong, sampleValType *C.nvmlValueType_t, vgpuInstanceSamplesCount *C.uint, utilizationSamples *C.nvmlVgpuInstanceUtilizationSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuUtilization")
}

//export nvmlDeviceGetViolationStatus
func nvmlDeviceGetViolationStatus(device C.nvmlDevice_t, perfPolicyType C.nvmlPerfPolicyType_t, violTime *C.nvmlViolationTime_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetViolationStatus")
}

//export nvmlDeviceGetVirtualizationMode
func nvmlDeviceGetVirtualizationMode(device C.nvmlDevice_t, pVirtualMode *C.nvmlGpuVirtualizationMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVirtualizationMode")
}

//export nvmlDeviceIsMigDeviceHandle
func nvmlDeviceIsMigDeviceHandle(device C.nvmlDevice_t, isMigDevice *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceIsMigDeviceHandle")
}

//export nvmlDeviceModifyDrainState
func nvmlDeviceModifyDrainState(pciInfo *C.nvmlPciInfo_t, newState C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceModifyDrainState")
}

//export nvmlDeviceOnSameBoard
func nvmlDeviceOnSameBoard(device1 C.nvmlDevice_t, device2 C.nvmlDevice_t, onSameBoard *C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceOnSameBoard")
}

//export nvmlDevicePowerSmoothingActivatePresetProfile
func nvmlDevicePowerSmoothingActivatePresetProfile(device C.nvmlDevice_t, profile *C.nvmlPowerSmoothingProfile_t) C.nvmlReturn_t {
	return stubReturn("nvmlDevicePowerSmoothingActivatePresetProfile")
}

//export nvmlDevicePowerSmoothingSetState
func nvmlDevicePowerSmoothingSetState(device C.nvmlDevice_t, state *C.nvmlPowerSmoothingState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDevicePowerSmoothingSetState")
}

//export nvmlDevicePowerSmoothingUpdatePresetProfileParam
func nvmlDevicePowerSmoothingUpdatePresetProfileParam(device C.nvmlDevice_t, profile *C.nvmlPowerSmoothingProfile_t) C.nvmlReturn_t {
	return stubReturn("nvmlDevicePowerSmoothingUpdatePresetProfileParam")
}

//export nvmlDeviceQueryDrainState
func nvmlDeviceQueryDrainState(pciInfo *C.nvmlPciInfo_t, currentState *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceQueryDrainState")
}

//export nvmlDeviceReadWritePRM_v1
func nvmlDeviceReadWritePRM_v1(device C.nvmlDevice_t, buffer *C.nvmlPRMTLV_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceReadWritePRM_v1")
}

//export nvmlDeviceRegisterEvents
func nvmlDeviceRegisterEvents(device C.nvmlDevice_t, eventTypes C.ulonglong, set C.nvmlEventSet_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceRegisterEvents")
}

//export nvmlDeviceRemoveGpu_v1
func nvmlDeviceRemoveGpu_v1(pciInfo *C.nvmlPciInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceRemoveGpu_v1")
}

//export nvmlDeviceRemoveGpu_v2
func nvmlDeviceRemoveGpu_v2(pciInfo *C.nvmlPciInfo_t, gpuState C.nvmlDetachGpuState_t, linkState C.nvmlPcieLinkState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceRemoveGpu_v2")
}

//export nvmlDeviceResetApplicationsClocks
func nvmlDeviceResetApplicationsClocks(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetApplicationsClocks")
}

//export nvmlDeviceResetGpuLockedClocks
func nvmlDeviceResetGpuLockedClocks(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetGpuLockedClocks")
}

//export nvmlDeviceResetMemoryLockedClocks
func nvmlDeviceResetMemoryLockedClocks(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetMemoryLockedClocks")
}

//export nvmlDeviceResetNvLinkErrorCounters
func nvmlDeviceResetNvLinkErrorCounters(device C.nvmlDevice_t, link C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetNvLinkErrorCounters")
}

//export nvmlDeviceResetNvLinkUtilizationCounter
func nvmlDeviceResetNvLinkUtilizationCounter(device C.nvmlDevice_t, link C.uint, counter C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetNvLinkUtilizationCounter")
}

//export nvmlDeviceSetAPIRestriction
func nvmlDeviceSetAPIRestriction(device C.nvmlDevice_t, apiType C.nvmlRestrictedAPI_t, isRestricted C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetAPIRestriction")
}

//export nvmlDeviceSetAccountingMode
func nvmlDeviceSetAccountingMode(device C.nvmlDevice_t, mode C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetAccountingMode")
}

//export nvmlDeviceSetApplicationsClocks
func nvmlDeviceSetApplicationsClocks(device C.nvmlDevice_t, memClockMHz C.uint, graphicsClockMHz C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetApplicationsClocks")
}

//export nvmlDeviceSetAutoBoostedClocksEnabled
func nvmlDeviceSetAutoBoostedClocksEnabled(device C.nvmlDevice_t, enabled C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetAutoBoostedClocksEnabled")
}

//export nvmlDeviceSetClockOffsets
func nvmlDeviceSetClockOffsets(device C.nvmlDevice_t, info *C.nvmlClockOffset_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetClockOffsets")
}

//export nvmlDeviceSetComputeMode
func nvmlDeviceSetComputeMode(device C.nvmlDevice_t, mode C.nvmlComputeMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetComputeMode")
}

//export nvmlDeviceSetConfComputeUnprotectedMemSize
func nvmlDeviceSetConfComputeUnprotectedMemSize(device C.nvmlDevice_t, sizeKiB C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetConfComputeUnprotectedMemSize")
}

//export nvmlDeviceSetCpuAffinity
func nvmlDeviceSetCpuAffinity(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetCpuAffinity")
}

//export nvmlDeviceSetDefaultAutoBoostedClocksEnabled
func nvmlDeviceSetDefaultAutoBoostedClocksEnabled(device C.nvmlDevice_t, enabled C.nvmlEnableState_t, flags C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDefaultAutoBoostedClocksEnabled")
}

//export nvmlDeviceSetDefaultFanSpeed_v2
func nvmlDeviceSetDefaultFanSpeed_v2(device C.nvmlDevice_t, fan C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDefaultFanSpeed_v2")
}

//export nvmlDeviceSetDramEncryptionMode
func nvmlDeviceSetDramEncryptionMode(device C.nvmlDevice_t, dramEncryption *C.nvmlDramEncryptionInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDramEncryptionMode")
}

//export nvmlDeviceSetDriverModel
func nvmlDeviceSetDriverModel(device C.nvmlDevice_t, driverModel C.nvmlDriverModel_t, flags C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDriverModel")
}

//export nvmlDeviceSetEccMode
func nvmlDeviceSetEccMode(device C.nvmlDevice_t, ecc C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetEccMode")
}

//export nvmlDeviceSetFanControlPolicy
func nvmlDeviceSetFanControlPolicy(device C.nvmlDevice_t, fan C.uint, policy C.nvmlFanControlPolicy_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetFanControlPolicy")
}

//export nvmlDeviceSetFanSpeed_v2
func nvmlDeviceSetFanSpeed_v2(device C.nvmlDevice_t, fan C.uint, speed C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetFanSpeed_v2")
}

//export nvmlDeviceSetGpcClkVfOffset
func nvmlDeviceSetGpcClkVfOffset(device C.nvmlDevice_t, offset C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetGpcClkVfOffset")
}

//export nvmlDeviceSetGpuLockedClocks
func nvmlDeviceSetGpuLockedClocks(device C.nvmlDevice_t, minGpuClockMHz C.uint, maxGpuClockMHz C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetGpuLockedClocks")
}

//export nvmlDeviceSetGpuOperationMode
func nvmlDeviceSetGpuOperationMode(device C.nvmlDevice_t, mode C.nvmlGpuOperationMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetGpuOperationMode")
}

//export nvmlDeviceSetMemClkVfOffset
func nvmlDeviceSetMemClkVfOffset(device C.nvmlDevice_t, offset C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetMemClkVfOffset")
}

//export nvmlDeviceSetMemoryLockedClocks
func nvmlDeviceSetMemoryLockedClocks(device C.nvmlDevice_t, minMemClockMHz C.uint, maxMemClockMHz C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetMemoryLockedClocks")
}

//export nvmlDeviceSetMigMode
func nvmlDeviceSetMigMode(device C.nvmlDevice_t, mode C.uint, activationStatus *C.nvmlReturn_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetMigMode")
}

//export nvmlDeviceSetNvLinkDeviceLowPowerThreshold
func nvmlDeviceSetNvLinkDeviceLowPowerThreshold(device C.nvmlDevice_t, info *C.nvmlNvLinkPowerThres_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetNvLinkDeviceLowPowerThreshold")
}

//export nvmlDeviceSetNvLinkUtilizationControl
func nvmlDeviceSetNvLinkUtilizationControl(device C.nvmlDevice_t, link C.uint, counter C.uint, control *C.nvmlNvLinkUtilizationControl_t, reset C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetNvLinkUtilizationControl")
}

//export nvmlDeviceSetNvlinkBwMode
func nvmlDeviceSetNvlinkBwMode(device C.nvmlDevice_t, setBwMode *C.nvmlNvlinkSetBwMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetNvlinkBwMode")
}

//export nvmlDeviceSetPersistenceMode
func nvmlDeviceSetPersistenceMode(device C.nvmlDevice_t, mode C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPersistenceMode")
}

//export nvmlDeviceSetPowerManagementLimit
func nvmlDeviceSetPowerManagementLimit(device C.nvmlDevice_t, limit C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPowerManagementLimit")
}

//export nvmlDeviceSetPowerManagementLimit_v2
func nvmlDeviceSetPowerManagementLimit_v2(device C.nvmlDevice_t, powerValue *C.nvmlPowerValue_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPowerManagementLimit_v2")
}

//export nvmlDeviceSetPowerMizerMode_v1
func nvmlDeviceSetPowerMizerMode_v1(device C.nvmlDevice_t, powerMizerMode *C.nvmlDevicePowerMizerModes_v1_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPowerMizerMode_v1")
}

//export nvmlDeviceSetTemperatureThreshold
func nvmlDeviceSetTemperatureThreshold(device C.nvmlDevice_t, thresholdType C.nvmlTemperatureThresholds_t, temp *C.int) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetTemperatureThreshold")
}

//export nvmlDeviceSetVgpuCapabilities
func nvmlDeviceSetVgpuCapabilities(device C.nvmlDevice_t, capability C.nvmlDeviceVgpuCapability_t, state C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVgpuCapabilities")
}

//export nvmlDeviceSetVgpuHeterogeneousMode
func nvmlDeviceSetVgpuHeterogeneousMode(device C.nvmlDevice_t, pHeterogeneousMode *C.nvmlVgpuHeterogeneousMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVgpuHeterogeneousMode")
}

//export nvmlDeviceSetVgpuSchedulerState
func nvmlDeviceSetVgpuSchedulerState(device C.nvmlDevice_t, pSchedulerState *C.nvmlVgpuSchedulerSetState_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVgpuSchedulerState")
}

//export nvmlDeviceSetVirtualizationMode
func nvmlDeviceSetVirtualizationMode(device C.nvmlDevice_t, virtualMode C.nvmlGpuVirtualizationMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVirtualizationMode")
}

//export nvmlDeviceValidateInforom
func nvmlDeviceValidateInforom(device C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceValidateInforom")
}

//export nvmlDeviceWorkloadPowerProfileClearRequestedProfiles
func nvmlDeviceWorkloadPowerProfileClearRequestedProfiles(device C.nvmlDevice_t, requestedProfiles *C.nvmlWorkloadPowerProfileRequestedProfiles_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileClearRequestedProfiles")
}

//export nvmlDeviceWorkloadPowerProfileGetCurrentProfiles
func nvmlDeviceWorkloadPowerProfileGetCurrentProfiles(device C.nvmlDevice_t, currentProfiles *C.nvmlWorkloadPowerProfileCurrentProfiles_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileGetCurrentProfiles")
}

//export nvmlDeviceWorkloadPowerProfileGetProfilesInfo
func nvmlDeviceWorkloadPowerProfileGetProfilesInfo(device C.nvmlDevice_t, profilesInfo *C.nvmlWorkloadPowerProfileProfilesInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileGetProfilesInfo")
}

//export nvmlDeviceWorkloadPowerProfileSetRequestedProfiles
func nvmlDeviceWorkloadPowerProfileSetRequestedProfiles(device C.nvmlDevice_t, requestedProfiles *C.nvmlWorkloadPowerProfileRequestedProfiles_t) C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileSetRequestedProfiles")
}

//export nvmlEventSetCreate
func nvmlEventSetCreate(set *C.nvmlEventSet_t) C.nvmlReturn_t {
	return stubReturn("nvmlEventSetCreate")
}

//export nvmlEventSetFree
func nvmlEventSetFree(set C.nvmlEventSet_t) C.nvmlReturn_t {
	return stubReturn("nvmlEventSetFree")
}

//export nvmlEventSetWait_v1
func nvmlEventSetWait_v1(set C.nvmlEventSet_t, data *C.nvmlEventData_t, timeoutms C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlEventSetWait_v1")
}

//export nvmlEventSetWait_v2
func nvmlEventSetWait_v2(set C.nvmlEventSet_t, data *C.nvmlEventData_t, timeoutms C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlEventSetWait_v2")
}

//export nvmlGetExcludedDeviceCount
func nvmlGetExcludedDeviceCount(deviceCount *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGetExcludedDeviceCount")
}

//export nvmlGetExcludedDeviceInfoByIndex
func nvmlGetExcludedDeviceInfoByIndex(index C.uint, info *C.nvmlExcludedDeviceInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGetExcludedDeviceInfoByIndex")
}

//export nvmlGetVgpuCompatibility
func nvmlGetVgpuCompatibility(vgpuMetadata *C.nvmlVgpuMetadata_t, pgpuMetadata *C.nvmlVgpuPgpuMetadata_t, compatibilityInfo *C.nvmlVgpuPgpuCompatibility_t) C.nvmlReturn_t {
	return stubReturn("nvmlGetVgpuCompatibility")
}

//export nvmlGetVgpuDriverCapabilities
func nvmlGetVgpuDriverCapabilities(capability C.nvmlVgpuDriverCapability_t, capResult *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGetVgpuDriverCapabilities")
}

//export nvmlGetVgpuVersion
func nvmlGetVgpuVersion(supported *C.nvmlVgpuVersion_t, current *C.nvmlVgpuVersion_t) C.nvmlReturn_t {
	return stubReturn("nvmlGetVgpuVersion")
}

//export nvmlGpmMetricsGet
func nvmlGpmMetricsGet(metricsGet *C.nvmlGpmMetricsGet_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpmMetricsGet")
}

//export nvmlGpmMigSampleGet
func nvmlGpmMigSampleGet(device C.nvmlDevice_t, gpuInstanceId C.uint, gpmSample C.nvmlGpmSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpmMigSampleGet")
}

//export nvmlGpmQueryDeviceSupport
func nvmlGpmQueryDeviceSupport(device C.nvmlDevice_t, gpmSupport *C.nvmlGpmSupport_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpmQueryDeviceSupport")
}

//export nvmlGpmQueryIfStreamingEnabled
func nvmlGpmQueryIfStreamingEnabled(device C.nvmlDevice_t, state *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGpmQueryIfStreamingEnabled")
}

//export nvmlGpmSampleAlloc
func nvmlGpmSampleAlloc(gpmSample *C.nvmlGpmSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpmSampleAlloc")
}

//export nvmlGpmSampleFree
func nvmlGpmSampleFree(gpmSample C.nvmlGpmSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpmSampleFree")
}

//export nvmlGpmSampleGet
func nvmlGpmSampleGet(device C.nvmlDevice_t, gpmSample C.nvmlGpmSample_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpmSampleGet")
}

//export nvmlGpmSetStreamingEnabled
func nvmlGpmSetStreamingEnabled(device C.nvmlDevice_t, state C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGpmSetStreamingEnabled")
}

//export nvmlGpuInstanceCreateComputeInstance
func nvmlGpuInstanceCreateComputeInstance(gpuInstance C.nvmlGpuInstance_t, profileId C.uint, computeInstance *C.nvmlComputeInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceCreateComputeInstance")
}

//export nvmlGpuInstanceCreateComputeInstanceWithPlacement
func nvmlGpuInstanceCreateComputeInstanceWithPlacement(gpuInstance C.nvmlGpuInstance_t, profileId C.uint, placement *C.nvmlComputeInstancePlacement_t, computeInstance *C.nvmlComputeInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceCreateComputeInstanceWithPlacement")
}

//export nvmlGpuInstanceDestroy
func nvmlGpuInstanceDestroy(gpuInstance C.nvmlGpuInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceDestroy")
}

//export nvmlGpuInstanceGetActiveVgpus
func nvmlGpuInstanceGetActiveVgpus(gpuInstance C.nvmlGpuInstance_t, pVgpuInstanceInfo *C.nvmlActiveVgpuInstanceInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetActiveVgpus")
}

//export nvmlGpuInstanceGetComputeInstanceById
func nvmlGpuInstanceGetComputeInstanceById(gpuInstance C.nvmlGpuInstance_t, id C.uint, computeInstance *C.nvmlComputeInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceById")
}

//export nvmlGpuInstanceGetComputeInstancePossiblePlacements
func nvmlGpuInstanceGetComputeInstancePossiblePlacements(gpuInstance C.nvmlGpuInstance_t, profileId C.uint, placements *C.nvmlComputeInstancePlacement_t, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstancePossiblePlacements")
}

//export nvmlGpuInstanceGetComputeInstanceProfileInfo
func nvmlGpuInstanceGetComputeInstanceProfileInfo(gpuInstance C.nvmlGpuInstance_t, profile C.uint, engProfile C.uint, info *C.nvmlComputeInstanceProfileInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceProfileInfo")
}

//export nvmlGpuInstanceGetComputeInstanceProfileInfoV
func nvmlGpuInstanceGetComputeInstanceProfileInfoV(gpuInstance C.nvmlGpuInstance_t, profile C.uint, engProfile C.uint, info *C.nvmlComputeInstanceProfileInfo_v2_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceProfileInfoV")
}

//export nvmlGpuInstanceGetComputeInstanceRemainingCapacity
func nvmlGpuInstanceGetComputeInstanceRemainingCapacity(gpuInstance C.nvmlGpuInstance_t, profileId C.uint, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceRemainingCapacity")
}

//export nvmlGpuInstanceGetComputeInstances
func nvmlGpuInstanceGetComputeInstances(gpuInstance C.nvmlGpuInstance_t, profileId C.uint, computeInstances *C.nvmlComputeInstance_t, count *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstances")
}

//export nvmlGpuInstanceGetCreatableVgpus
func nvmlGpuInstanceGetCreatableVgpus(gpuInstance C.nvmlGpuInstance_t, pVgpus *C.nvmlVgpuTypeIdInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetCreatableVgpus")
}

//export nvmlGpuInstanceGetInfo
func nvmlGpuInstanceGetInfo(gpuInstance C.nvmlGpuInstance_t, info *C.nvmlGpuInstanceInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetInfo")
}

//export nvmlGpuInstanceGetVgpuHeterogeneousMode
func nvmlGpuInstanceGetVgpuHeterogeneousMode(gpuInstance C.nvmlGpuInstance_t, pHeterogeneousMode *C.nvmlVgpuHeterogeneousMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuHeterogeneousMode")
}

//export nvmlGpuInstanceGetVgpuSchedulerLog
func nvmlGpuInstanceGetVgpuSchedulerLog(gpuInstance C.nvmlGpuInstance_t, pSchedulerLogInfo *C.nvmlVgpuSchedulerLogInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuSchedulerLog")
}

//export nvmlGpuInstanceGetVgpuSchedulerState
func nvmlGpuInstanceGetVgpuSchedulerState(gpuInstance C.nvmlGpuInstance_t, pSchedulerStateInfo *C.nvmlVgpuSchedulerStateInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuSchedulerState")
}

//export nvmlGpuInstanceGetVgpuTypeCreatablePlacements
func nvmlGpuInstanceGetVgpuTypeCreatablePlacements(gpuInstance C.nvmlGpuInstance_t, pCreatablePlacementInfo *C.nvmlVgpuCreatablePlacementInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuTypeCreatablePlacements")
}

//export nvmlGpuInstanceSetVgpuHeterogeneousMode
func nvmlGpuInstanceSetVgpuHeterogeneousMode(gpuInstance C.nvmlGpuInstance_t, pHeterogeneousMode *C.nvmlVgpuHeterogeneousMode_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceSetVgpuHeterogeneousMode")
}

//export nvmlGpuInstanceSetVgpuSchedulerState
func nvmlGpuInstanceSetVgpuSchedulerState(gpuInstance C.nvmlGpuInstance_t, pScheduler *C.nvmlVgpuSchedulerState_t) C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceSetVgpuSchedulerState")
}

//export nvmlSetVgpuVersion
func nvmlSetVgpuVersion(vgpuVersion *C.nvmlVgpuVersion_t) C.nvmlReturn_t {
	return stubReturn("nvmlSetVgpuVersion")
}

//export nvmlSystemEventSetCreate
func nvmlSystemEventSetCreate(request *C.nvmlSystemEventSetCreateRequest_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemEventSetCreate")
}

//export nvmlSystemEventSetFree
func nvmlSystemEventSetFree(request *C.nvmlSystemEventSetFreeRequest_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemEventSetFree")
}

//export nvmlSystemEventSetWait
func nvmlSystemEventSetWait(request *C.nvmlSystemEventSetWaitRequest_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemEventSetWait")
}

//export nvmlSystemGetConfComputeCapabilities
func nvmlSystemGetConfComputeCapabilities(capabilities *C.nvmlConfComputeSystemCaps_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeCapabilities")
}

//export nvmlSystemGetConfComputeGpusReadyState
func nvmlSystemGetConfComputeGpusReadyState(isAcceptingWork *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeGpusReadyState")
}

//export nvmlSystemGetConfComputeKeyRotationThresholdInfo
func nvmlSystemGetConfComputeKeyRotationThresholdInfo(pKeyRotationThrInfo *C.nvmlConfComputeGetKeyRotationThresholdInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeKeyRotationThresholdInfo")
}

//export nvmlSystemGetConfComputeSettings
func nvmlSystemGetConfComputeSettings(settings *C.nvmlSystemConfComputeSettings_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeSettings")
}

//export nvmlSystemGetConfComputeState
func nvmlSystemGetConfComputeState(state *C.nvmlConfComputeSystemState_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeState")
}

//export nvmlSystemGetDriverBranch
func nvmlSystemGetDriverBranch(branchInfo *C.nvmlSystemDriverBranchInfo_t, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetDriverBranch")
}

//export nvmlSystemGetHicVersion
func nvmlSystemGetHicVersion(hwbcCount *C.uint, hwbcEntries *C.nvmlHwbcEntry_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetHicVersion")
}

//export nvmlSystemGetNvlinkBwMode
func nvmlSystemGetNvlinkBwMode(nvlinkBwMode *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetNvlinkBwMode")
}

//export nvmlSystemGetProcessName
func nvmlSystemGetProcessName(pid C.uint, name *C.char, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetProcessName")
}

//export nvmlSystemGetTopologyGpuSet
func nvmlSystemGetTopologyGpuSet(cpuNumber C.uint, count *C.uint, deviceArray *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetTopologyGpuSet")
}

//export nvmlSystemRegisterEvents
func nvmlSystemRegisterEvents(request *C.nvmlSystemRegisterEventRequest_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemRegisterEvents")
}

//export nvmlSystemSetConfComputeGpusReadyState
func nvmlSystemSetConfComputeGpusReadyState(isAcceptingWork C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlSystemSetConfComputeGpusReadyState")
}

//export nvmlSystemSetConfComputeKeyRotationThresholdInfo
func nvmlSystemSetConfComputeKeyRotationThresholdInfo(pKeyRotationThrInfo *C.nvmlConfComputeSetKeyRotationThresholdInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlSystemSetConfComputeKeyRotationThresholdInfo")
}

//export nvmlSystemSetNvlinkBwMode
func nvmlSystemSetNvlinkBwMode(nvlinkBwMode C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlSystemSetNvlinkBwMode")
}

//export nvmlUnitGetCount
func nvmlUnitGetCount(unitCount *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetCount")
}

//export nvmlUnitGetDevices
func nvmlUnitGetDevices(unit C.nvmlUnit_t, deviceCount *C.uint, devices *C.nvmlDevice_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetDevices")
}

//export nvmlUnitGetFanSpeedInfo
func nvmlUnitGetFanSpeedInfo(unit C.nvmlUnit_t, fanSpeeds *C.nvmlUnitFanSpeeds_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetFanSpeedInfo")
}

//export nvmlUnitGetHandleByIndex
func nvmlUnitGetHandleByIndex(index C.uint, unit *C.nvmlUnit_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetHandleByIndex")
}

//export nvmlUnitGetLedState
func nvmlUnitGetLedState(unit C.nvmlUnit_t, state *C.nvmlLedState_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetLedState")
}

//export nvmlUnitGetPsuInfo
func nvmlUnitGetPsuInfo(unit C.nvmlUnit_t, psu *C.nvmlPSUInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetPsuInfo")
}

//export nvmlUnitGetTemperature
func nvmlUnitGetTemperature(unit C.nvmlUnit_t, _type C.uint, temp *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetTemperature")
}

//export nvmlUnitGetUnitInfo
func nvmlUnitGetUnitInfo(unit C.nvmlUnit_t, info *C.nvmlUnitInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetUnitInfo")
}

//export nvmlUnitSetLedState
func nvmlUnitSetLedState(unit C.nvmlUnit_t, color C.nvmlLedColor_t) C.nvmlReturn_t {
	return stubReturn("nvmlUnitSetLedState")
}

//export nvmlVgpuInstanceClearAccountingPids
func nvmlVgpuInstanceClearAccountingPids(vgpuInstance C.nvmlVgpuInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceClearAccountingPids")
}

//export nvmlVgpuInstanceGetAccountingMode
func nvmlVgpuInstanceGetAccountingMode(vgpuInstance C.nvmlVgpuInstance_t, mode *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetAccountingMode")
}

//export nvmlVgpuInstanceGetAccountingPids
func nvmlVgpuInstanceGetAccountingPids(vgpuInstance C.nvmlVgpuInstance_t, count *C.uint, pids *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetAccountingPids")
}

//export nvmlVgpuInstanceGetAccountingStats
func nvmlVgpuInstanceGetAccountingStats(vgpuInstance C.nvmlVgpuInstance_t, pid C.uint, stats *C.nvmlAccountingStats_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetAccountingStats")
}

//export nvmlVgpuInstanceGetEccMode
func nvmlVgpuInstanceGetEccMode(vgpuInstance C.nvmlVgpuInstance_t, eccMode *C.nvmlEnableState_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEccMode")
}

//export nvmlVgpuInstanceGetEncoderCapacity
func nvmlVgpuInstanceGetEncoderCapacity(vgpuInstance C.nvmlVgpuInstance_t, encoderCapacity *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEncoderCapacity")
}

//export nvmlVgpuInstanceGetEncoderSessions
func nvmlVgpuInstanceGetEncoderSessions(vgpuInstance C.nvmlVgpuInstance_t, sessionCount *C.uint, sessionInfo *C.nvmlEncoderSessionInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEncoderSessions")
}

//export nvmlVgpuInstanceGetEncoderStats
func nvmlVgpuInstanceGetEncoderStats(vgpuInstance C.nvmlVgpuInstance_t, sessionCount *C.uint, averageFps *C.uint, averageLatency *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEncoderStats")
}

//export nvmlVgpuInstanceGetFBCSessions
func nvmlVgpuInstanceGetFBCSessions(vgpuInstance C.nvmlVgpuInstance_t, sessionCount *C.uint, sessionInfo *C.nvmlFBCSessionInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFBCSessions")
}

//export nvmlVgpuInstanceGetFBCStats
func nvmlVgpuInstanceGetFBCStats(vgpuInstance C.nvmlVgpuInstance_t, fbcStats *C.nvmlFBCStats_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFBCStats")
}

//export nvmlVgpuInstanceGetFbUsage
func nvmlVgpuInstanceGetFbUsage(vgpuInstance C.nvmlVgpuInstance_t, fbUsage *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFbUsage")
}

//export nvmlVgpuInstanceGetFrameRateLimit
func nvmlVgpuInstanceGetFrameRateLimit(vgpuInstance C.nvmlVgpuInstance_t, frameRateLimit *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFrameRateLimit")
}

//export nvmlVgpuInstanceGetGpuInstanceId
func nvmlVgpuInstanceGetGpuInstanceId(vgpuInstance C.nvmlVgpuInstance_t, gpuInstanceId *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetGpuInstanceId")
}

//export nvmlVgpuInstanceGetGpuPciId
func nvmlVgpuInstanceGetGpuPciId(vgpuInstance C.nvmlVgpuInstance_t, vgpuPciId *C.char, length *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetGpuPciId")
}

//export nvmlVgpuInstanceGetLicenseInfo_v1
func nvmlVgpuInstanceGetLicenseInfo_v1(vgpuInstance C.nvmlVgpuInstance_t, licenseInfo *C.nvmlVgpuLicenseInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetLicenseInfo_v1")
}

//export nvmlVgpuInstanceGetLicenseInfo_v2
func nvmlVgpuInstanceGetLicenseInfo_v2(vgpuInstance C.nvmlVgpuInstance_t, licenseInfo *C.nvmlVgpuLicenseInfo_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetLicenseInfo_v2")
}

//export nvmlVgpuInstanceGetLicenseStatus
func nvmlVgpuInstanceGetLicenseStatus(vgpuInstance C.nvmlVgpuInstance_t, licensed *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetLicenseStatus")
}

//export nvmlVgpuInstanceGetMdevUUID
func nvmlVgpuInstanceGetMdevUUID(vgpuInstance C.nvmlVgpuInstance_t, mdevUuid *C.char, size C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetMdevUUID")
}

//export nvmlVgpuInstanceGetMetadata
func nvmlVgpuInstanceGetMetadata(vgpuInstance C.nvmlVgpuInstance_t, vgpuMetadata *C.nvmlVgpuMetadata_t, bufferSize *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetMetadata")
}

//export nvmlVgpuInstanceGetPlacementId
func nvmlVgpuInstanceGetPlacementId(vgpuInstance C.nvmlVgpuInstance_t, pPlacement *C.nvmlVgpuPlacementId_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetPlacementId")
}

//export nvmlVgpuInstanceGetRuntimeStateSize
func nvmlVgpuInstanceGetRuntimeStateSize(vgpuInstance C.nvmlVgpuInstance_t, pState *C.nvmlVgpuRuntimeState_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetRuntimeStateSize")
}

//export nvmlVgpuInstanceGetType
func nvmlVgpuInstanceGetType(vgpuInstance C.nvmlVgpuInstance_t, vgpuTypeId *C.nvmlVgpuTypeId_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetType")
}

//export nvmlVgpuInstanceGetUUID
func nvmlVgpuInstanceGetUUID(vgpuInstance C.nvmlVgpuInstance_t, uuid *C.char, size C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetUUID")
}

//export nvmlVgpuInstanceGetVmDriverVersion
func nvmlVgpuInstanceGetVmDriverVersion(vgpuInstance C.nvmlVgpuInstance_t, version *C.char, length C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetVmDriverVersion")
}

//export nvmlVgpuInstanceGetVmID
func nvmlVgpuInstanceGetVmID(vgpuInstance C.nvmlVgpuInstance_t, vmId *C.char, size C.uint, vmIdType *C.nvmlVgpuVmIdType_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetVmID")
}

//export nvmlVgpuInstanceSetEncoderCapacity
func nvmlVgpuInstanceSetEncoderCapacity(vgpuInstance C.nvmlVgpuInstance_t, encoderCapacity C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceSetEncoderCapacity")
}

//export nvmlVgpuTypeGetBAR1Info
func nvmlVgpuTypeGetBAR1Info(vgpuTypeId C.nvmlVgpuTypeId_t, bar1Info *C.nvmlVgpuTypeBar1Info_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetBAR1Info")
}

//export nvmlVgpuTypeGetCapabilities
func nvmlVgpuTypeGetCapabilities(vgpuTypeId C.nvmlVgpuTypeId_t, capability C.nvmlVgpuCapability_t, capResult *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetCapabilities")
}

//export nvmlVgpuTypeGetClass
func nvmlVgpuTypeGetClass(vgpuTypeId C.nvmlVgpuTypeId_t, vgpuTypeClass *C.char, size *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetClass")
}

//export nvmlVgpuTypeGetDeviceID
func nvmlVgpuTypeGetDeviceID(vgpuTypeId C.nvmlVgpuTypeId_t, deviceID *C.ulonglong, subsystemID *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetDeviceID")
}

//export nvmlVgpuTypeGetFbReservation
func nvmlVgpuTypeGetFbReservation(vgpuTypeId C.nvmlVgpuTypeId_t, fbReservation *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetFbReservation")
}

//export nvmlVgpuTypeGetFrameRateLimit
func nvmlVgpuTypeGetFrameRateLimit(vgpuTypeId C.nvmlVgpuTypeId_t, frameRateLimit *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetFrameRateLimit")
}

//export nvmlVgpuTypeGetFramebufferSize
func nvmlVgpuTypeGetFramebufferSize(vgpuTypeId C.nvmlVgpuTypeId_t, fbSize *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetFramebufferSize")
}

//export nvmlVgpuTypeGetGpuInstanceProfileId
func nvmlVgpuTypeGetGpuInstanceProfileId(vgpuTypeId C.nvmlVgpuTypeId_t, gpuInstanceProfileId *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetGpuInstanceProfileId")
}

//export nvmlVgpuTypeGetGspHeapSize
func nvmlVgpuTypeGetGspHeapSize(vgpuTypeId C.nvmlVgpuTypeId_t, gspHeapSize *C.ulonglong) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetGspHeapSize")
}

//export nvmlVgpuTypeGetLicense
func nvmlVgpuTypeGetLicense(vgpuTypeId C.nvmlVgpuTypeId_t, vgpuTypeLicenseString *C.char, size C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetLicense")
}

//export nvmlVgpuTypeGetMaxInstances
func nvmlVgpuTypeGetMaxInstances(device C.nvmlDevice_t, vgpuTypeId C.nvmlVgpuTypeId_t, vgpuInstanceCount *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetMaxInstances")
}

//export nvmlVgpuTypeGetMaxInstancesPerGpuInstance
func nvmlVgpuTypeGetMaxInstancesPerGpuInstance(pMaxInstance *C.nvmlVgpuTypeMaxInstance_t) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetMaxInstancesPerGpuInstance")
}

//export nvmlVgpuTypeGetMaxInstancesPerVm
func nvmlVgpuTypeGetMaxInstancesPerVm(vgpuTypeId C.nvmlVgpuTypeId_t, vgpuInstanceCountPerVm *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetMaxInstancesPerVm")
}

//export nvmlVgpuTypeGetName
func nvmlVgpuTypeGetName(vgpuTypeId C.nvmlVgpuTypeId_t, vgpuTypeName *C.char, size *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetName")
}

//export nvmlVgpuTypeGetNumDisplayHeads
func nvmlVgpuTypeGetNumDisplayHeads(vgpuTypeId C.nvmlVgpuTypeId_t, numDisplayHeads *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetNumDisplayHeads")
}

//export nvmlVgpuTypeGetResolution
func nvmlVgpuTypeGetResolution(vgpuTypeId C.nvmlVgpuTypeId_t, displayIndex C.uint, xdim *C.uint, ydim *C.uint) C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetResolution")
}
