// Code generated by cmd/generate-bridge. DO NOT EDIT.
// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// This file contains stub implementations for NVML functions that are
// not yet implemented in hand-written files.
//
// To implement a function, add it to one of the implementation files
// (init.go, device.go, device_info.go, system.go) and regenerate this file.
// The generator will automatically detect the new implementation and
// remove the stub.

package main

/*
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// Include NVML type definitions for strict ABI compatibility.
#include "nvml_types.h"
*/
import "C"

// 375 stub functions for unimplemented NVML functions.
// These return NVML_ERROR_NOT_SUPPORTED (3).

//export nvmlComputeInstanceDestroy
func nvmlComputeInstanceDestroy() C.nvmlReturn_t {
	return stubReturn("nvmlComputeInstanceDestroy")
}

//export nvmlComputeInstanceGetInfo_v1
func nvmlComputeInstanceGetInfo_v1() C.nvmlReturn_t {
	return stubReturn("nvmlComputeInstanceGetInfo_v1")
}

//export nvmlComputeInstanceGetInfo_v2
func nvmlComputeInstanceGetInfo_v2() C.nvmlReturn_t {
	return stubReturn("nvmlComputeInstanceGetInfo_v2")
}

//export nvmlDeviceClearAccountingPids
func nvmlDeviceClearAccountingPids() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearAccountingPids")
}

//export nvmlDeviceClearCpuAffinity
func nvmlDeviceClearCpuAffinity() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearCpuAffinity")
}

//export nvmlDeviceClearEccErrorCounts
func nvmlDeviceClearEccErrorCounts() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearEccErrorCounts")
}

//export nvmlDeviceClearFieldValues
func nvmlDeviceClearFieldValues() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceClearFieldValues")
}

//export nvmlDeviceCreateGpuInstance
func nvmlDeviceCreateGpuInstance() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceCreateGpuInstance")
}

//export nvmlDeviceCreateGpuInstanceWithPlacement
func nvmlDeviceCreateGpuInstanceWithPlacement() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceCreateGpuInstanceWithPlacement")
}

//export nvmlDeviceDiscoverGpus
func nvmlDeviceDiscoverGpus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceDiscoverGpus")
}

//export nvmlDeviceFreezeNvLinkUtilizationCounter
func nvmlDeviceFreezeNvLinkUtilizationCounter() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceFreezeNvLinkUtilizationCounter")
}

//export nvmlDeviceGetAPIRestriction
func nvmlDeviceGetAPIRestriction() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAPIRestriction")
}

//export nvmlDeviceGetAccountingBufferSize
func nvmlDeviceGetAccountingBufferSize() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingBufferSize")
}

//export nvmlDeviceGetAccountingMode
func nvmlDeviceGetAccountingMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingMode")
}

//export nvmlDeviceGetAccountingPids
func nvmlDeviceGetAccountingPids() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingPids")
}

//export nvmlDeviceGetAccountingStats
func nvmlDeviceGetAccountingStats() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAccountingStats")
}

//export nvmlDeviceGetActiveVgpus
func nvmlDeviceGetActiveVgpus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetActiveVgpus")
}

//export nvmlDeviceGetAdaptiveClockInfoStatus
func nvmlDeviceGetAdaptiveClockInfoStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAdaptiveClockInfoStatus")
}

//export nvmlDeviceGetAddressingMode
func nvmlDeviceGetAddressingMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAddressingMode")
}

//export nvmlDeviceGetApplicationsClock
func nvmlDeviceGetApplicationsClock() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetApplicationsClock")
}

//export nvmlDeviceGetAttributes_v1
func nvmlDeviceGetAttributes_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAttributes_v1")
}

//export nvmlDeviceGetAttributes_v2
func nvmlDeviceGetAttributes_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAttributes_v2")
}

//export nvmlDeviceGetAutoBoostedClocksEnabled
func nvmlDeviceGetAutoBoostedClocksEnabled() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetAutoBoostedClocksEnabled")
}

//export nvmlDeviceGetBAR1MemoryInfo
func nvmlDeviceGetBAR1MemoryInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBAR1MemoryInfo")
}

//export nvmlDeviceGetBoardId
func nvmlDeviceGetBoardId() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBoardId")
}

//export nvmlDeviceGetBoardPartNumber
func nvmlDeviceGetBoardPartNumber() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBoardPartNumber")
}

//export nvmlDeviceGetBridgeChipInfo
func nvmlDeviceGetBridgeChipInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBridgeChipInfo")
}

//export nvmlDeviceGetBusType
func nvmlDeviceGetBusType() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetBusType")
}

//export nvmlDeviceGetC2cModeInfoV
func nvmlDeviceGetC2cModeInfoV() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetC2cModeInfoV")
}

//export nvmlDeviceGetCapabilities
func nvmlDeviceGetCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCapabilities")
}

//export nvmlDeviceGetClkMonStatus
func nvmlDeviceGetClkMonStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClkMonStatus")
}

//export nvmlDeviceGetClock
func nvmlDeviceGetClock() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClock")
}

//export nvmlDeviceGetClockInfo
func nvmlDeviceGetClockInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClockInfo")
}

//export nvmlDeviceGetClockOffsets
func nvmlDeviceGetClockOffsets() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetClockOffsets")
}

//export nvmlDeviceGetComputeInstanceId
func nvmlDeviceGetComputeInstanceId() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeInstanceId")
}

//export nvmlDeviceGetComputeMode
func nvmlDeviceGetComputeMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeMode")
}

//export nvmlDeviceGetComputeRunningProcesses_v1
func nvmlDeviceGetComputeRunningProcesses_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeRunningProcesses_v1")
}

//export nvmlDeviceGetComputeRunningProcesses_v2
func nvmlDeviceGetComputeRunningProcesses_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeRunningProcesses_v2")
}

//export nvmlDeviceGetComputeRunningProcesses_v3
func nvmlDeviceGetComputeRunningProcesses_v3() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetComputeRunningProcesses_v3")
}

//export nvmlDeviceGetConfComputeGpuAttestationReport
func nvmlDeviceGetConfComputeGpuAttestationReport() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeGpuAttestationReport")
}

//export nvmlDeviceGetConfComputeGpuCertificate
func nvmlDeviceGetConfComputeGpuCertificate() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeGpuCertificate")
}

//export nvmlDeviceGetConfComputeMemSizeInfo
func nvmlDeviceGetConfComputeMemSizeInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeMemSizeInfo")
}

//export nvmlDeviceGetConfComputeProtectedMemoryUsage
func nvmlDeviceGetConfComputeProtectedMemoryUsage() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetConfComputeProtectedMemoryUsage")
}

//export nvmlDeviceGetCoolerInfo
func nvmlDeviceGetCoolerInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCoolerInfo")
}

//export nvmlDeviceGetCpuAffinity
func nvmlDeviceGetCpuAffinity() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCpuAffinity")
}

//export nvmlDeviceGetCpuAffinityWithinScope
func nvmlDeviceGetCpuAffinityWithinScope() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCpuAffinityWithinScope")
}

//export nvmlDeviceGetCreatableVgpus
func nvmlDeviceGetCreatableVgpus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCreatableVgpus")
}

//export nvmlDeviceGetCurrPcieLinkGeneration
func nvmlDeviceGetCurrPcieLinkGeneration() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrPcieLinkGeneration")
}

//export nvmlDeviceGetCurrPcieLinkWidth
func nvmlDeviceGetCurrPcieLinkWidth() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrPcieLinkWidth")
}

//export nvmlDeviceGetCurrentClockFreqs
func nvmlDeviceGetCurrentClockFreqs() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrentClockFreqs")
}

//export nvmlDeviceGetCurrentClocksEventReasons
func nvmlDeviceGetCurrentClocksEventReasons() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrentClocksEventReasons")
}

//export nvmlDeviceGetCurrentClocksThrottleReasons
func nvmlDeviceGetCurrentClocksThrottleReasons() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetCurrentClocksThrottleReasons")
}

//export nvmlDeviceGetDecoderUtilization
func nvmlDeviceGetDecoderUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDecoderUtilization")
}

//export nvmlDeviceGetDefaultApplicationsClock
func nvmlDeviceGetDefaultApplicationsClock() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDefaultApplicationsClock")
}

//export nvmlDeviceGetDefaultEccMode
func nvmlDeviceGetDefaultEccMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDefaultEccMode")
}

//export nvmlDeviceGetDetailedEccErrors
func nvmlDeviceGetDetailedEccErrors() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDetailedEccErrors")
}

//export nvmlDeviceGetDeviceHandleFromMigDeviceHandle
func nvmlDeviceGetDeviceHandleFromMigDeviceHandle() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDeviceHandleFromMigDeviceHandle")
}

//export nvmlDeviceGetDisplayActive
func nvmlDeviceGetDisplayActive() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDisplayActive")
}

//export nvmlDeviceGetDisplayMode
func nvmlDeviceGetDisplayMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDisplayMode")
}

//export nvmlDeviceGetDramEncryptionMode
func nvmlDeviceGetDramEncryptionMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDramEncryptionMode")
}

//export nvmlDeviceGetDriverModel_v1
func nvmlDeviceGetDriverModel_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDriverModel_v1")
}

//export nvmlDeviceGetDriverModel_v2
func nvmlDeviceGetDriverModel_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDriverModel_v2")
}

//export nvmlDeviceGetDynamicPstatesInfo
func nvmlDeviceGetDynamicPstatesInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetDynamicPstatesInfo")
}

//export nvmlDeviceGetEccMode
func nvmlDeviceGetEccMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEccMode")
}

//export nvmlDeviceGetEncoderCapacity
func nvmlDeviceGetEncoderCapacity() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderCapacity")
}

//export nvmlDeviceGetEncoderSessions
func nvmlDeviceGetEncoderSessions() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderSessions")
}

//export nvmlDeviceGetEncoderStats
func nvmlDeviceGetEncoderStats() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderStats")
}

//export nvmlDeviceGetEncoderUtilization
func nvmlDeviceGetEncoderUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEncoderUtilization")
}

//export nvmlDeviceGetEnforcedPowerLimit
func nvmlDeviceGetEnforcedPowerLimit() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetEnforcedPowerLimit")
}

//export nvmlDeviceGetFBCSessions
func nvmlDeviceGetFBCSessions() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFBCSessions")
}

//export nvmlDeviceGetFBCStats
func nvmlDeviceGetFBCStats() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFBCStats")
}

//export nvmlDeviceGetFanControlPolicy_v2
func nvmlDeviceGetFanControlPolicy_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanControlPolicy_v2")
}

//export nvmlDeviceGetFanSpeed
func nvmlDeviceGetFanSpeed() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanSpeed")
}

//export nvmlDeviceGetFanSpeedRPM
func nvmlDeviceGetFanSpeedRPM() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanSpeedRPM")
}

//export nvmlDeviceGetFanSpeed_v2
func nvmlDeviceGetFanSpeed_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFanSpeed_v2")
}

//export nvmlDeviceGetFieldValues
func nvmlDeviceGetFieldValues() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetFieldValues")
}

//export nvmlDeviceGetGpcClkMinMaxVfOffset
func nvmlDeviceGetGpcClkMinMaxVfOffset() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpcClkMinMaxVfOffset")
}

//export nvmlDeviceGetGpcClkVfOffset
func nvmlDeviceGetGpcClkVfOffset() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpcClkVfOffset")
}

//export nvmlDeviceGetGpuFabricInfo
func nvmlDeviceGetGpuFabricInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuFabricInfo")
}

//export nvmlDeviceGetGpuFabricInfoV
func nvmlDeviceGetGpuFabricInfoV() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuFabricInfoV")
}

//export nvmlDeviceGetGpuInstanceById
func nvmlDeviceGetGpuInstanceById() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceById")
}

//export nvmlDeviceGetGpuInstanceId
func nvmlDeviceGetGpuInstanceId() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceId")
}

//export nvmlDeviceGetGpuInstancePossiblePlacements_v1
func nvmlDeviceGetGpuInstancePossiblePlacements_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstancePossiblePlacements_v1")
}

//export nvmlDeviceGetGpuInstancePossiblePlacements_v2
func nvmlDeviceGetGpuInstancePossiblePlacements_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstancePossiblePlacements_v2")
}

//export nvmlDeviceGetGpuInstanceProfileInfo
func nvmlDeviceGetGpuInstanceProfileInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceProfileInfo")
}

//export nvmlDeviceGetGpuInstanceProfileInfoByIdV
func nvmlDeviceGetGpuInstanceProfileInfoByIdV() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceProfileInfoByIdV")
}

//export nvmlDeviceGetGpuInstanceProfileInfoV
func nvmlDeviceGetGpuInstanceProfileInfoV() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceProfileInfoV")
}

//export nvmlDeviceGetGpuInstanceRemainingCapacity
func nvmlDeviceGetGpuInstanceRemainingCapacity() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstanceRemainingCapacity")
}

//export nvmlDeviceGetGpuInstances
func nvmlDeviceGetGpuInstances() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuInstances")
}

//export nvmlDeviceGetGpuMaxPcieLinkGeneration
func nvmlDeviceGetGpuMaxPcieLinkGeneration() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuMaxPcieLinkGeneration")
}

//export nvmlDeviceGetGpuOperationMode
func nvmlDeviceGetGpuOperationMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGpuOperationMode")
}

//export nvmlDeviceGetGraphicsRunningProcesses_v1
func nvmlDeviceGetGraphicsRunningProcesses_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGraphicsRunningProcesses_v1")
}

//export nvmlDeviceGetGraphicsRunningProcesses_v2
func nvmlDeviceGetGraphicsRunningProcesses_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGraphicsRunningProcesses_v2")
}

//export nvmlDeviceGetGraphicsRunningProcesses_v3
func nvmlDeviceGetGraphicsRunningProcesses_v3() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGraphicsRunningProcesses_v3")
}

//export nvmlDeviceGetGridLicensableFeatures_v1
func nvmlDeviceGetGridLicensableFeatures_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v1")
}

//export nvmlDeviceGetGridLicensableFeatures_v2
func nvmlDeviceGetGridLicensableFeatures_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v2")
}

//export nvmlDeviceGetGridLicensableFeatures_v3
func nvmlDeviceGetGridLicensableFeatures_v3() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v3")
}

//export nvmlDeviceGetGridLicensableFeatures_v4
func nvmlDeviceGetGridLicensableFeatures_v4() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGridLicensableFeatures_v4")
}

//export nvmlDeviceGetGspFirmwareMode
func nvmlDeviceGetGspFirmwareMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGspFirmwareMode")
}

//export nvmlDeviceGetGspFirmwareVersion
func nvmlDeviceGetGspFirmwareVersion() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetGspFirmwareVersion")
}

//export nvmlDeviceGetHandleBySerial
func nvmlDeviceGetHandleBySerial() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetHandleBySerial")
}

//export nvmlDeviceGetHandleByUUIDV
func nvmlDeviceGetHandleByUUIDV() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetHandleByUUIDV")
}

//export nvmlDeviceGetHostVgpuMode
func nvmlDeviceGetHostVgpuMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetHostVgpuMode")
}

//export nvmlDeviceGetInforomConfigurationChecksum
func nvmlDeviceGetInforomConfigurationChecksum() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetInforomConfigurationChecksum")
}

//export nvmlDeviceGetInforomImageVersion
func nvmlDeviceGetInforomImageVersion() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetInforomImageVersion")
}

//export nvmlDeviceGetInforomVersion
func nvmlDeviceGetInforomVersion() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetInforomVersion")
}

//export nvmlDeviceGetIrqNum
func nvmlDeviceGetIrqNum() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetIrqNum")
}

//export nvmlDeviceGetJpgUtilization
func nvmlDeviceGetJpgUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetJpgUtilization")
}

//export nvmlDeviceGetLastBBXFlushTime
func nvmlDeviceGetLastBBXFlushTime() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetLastBBXFlushTime")
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v1
func nvmlDeviceGetMPSComputeRunningProcesses_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMPSComputeRunningProcesses_v1")
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v2
func nvmlDeviceGetMPSComputeRunningProcesses_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMPSComputeRunningProcesses_v2")
}

//export nvmlDeviceGetMPSComputeRunningProcesses_v3
func nvmlDeviceGetMPSComputeRunningProcesses_v3() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMPSComputeRunningProcesses_v3")
}

//export nvmlDeviceGetMarginTemperature
func nvmlDeviceGetMarginTemperature() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMarginTemperature")
}

//export nvmlDeviceGetMaxClockInfo
func nvmlDeviceGetMaxClockInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxClockInfo")
}

//export nvmlDeviceGetMaxCustomerBoostClock
func nvmlDeviceGetMaxCustomerBoostClock() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxCustomerBoostClock")
}

//export nvmlDeviceGetMaxMigDeviceCount
func nvmlDeviceGetMaxMigDeviceCount() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxMigDeviceCount")
}

//export nvmlDeviceGetMaxPcieLinkGeneration
func nvmlDeviceGetMaxPcieLinkGeneration() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxPcieLinkGeneration")
}

//export nvmlDeviceGetMaxPcieLinkWidth
func nvmlDeviceGetMaxPcieLinkWidth() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMaxPcieLinkWidth")
}

//export nvmlDeviceGetMemClkMinMaxVfOffset
func nvmlDeviceGetMemClkMinMaxVfOffset() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemClkMinMaxVfOffset")
}

//export nvmlDeviceGetMemClkVfOffset
func nvmlDeviceGetMemClkVfOffset() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemClkVfOffset")
}

//export nvmlDeviceGetMemoryAffinity
func nvmlDeviceGetMemoryAffinity() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemoryAffinity")
}

//export nvmlDeviceGetMemoryBusWidth
func nvmlDeviceGetMemoryBusWidth() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemoryBusWidth")
}

//export nvmlDeviceGetMemoryErrorCounter
func nvmlDeviceGetMemoryErrorCounter() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMemoryErrorCounter")
}

//export nvmlDeviceGetMigDeviceHandleByIndex
func nvmlDeviceGetMigDeviceHandleByIndex() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMigDeviceHandleByIndex")
}

//export nvmlDeviceGetMinMaxClockOfPState
func nvmlDeviceGetMinMaxClockOfPState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMinMaxClockOfPState")
}

//export nvmlDeviceGetMinMaxFanSpeed
func nvmlDeviceGetMinMaxFanSpeed() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMinMaxFanSpeed")
}

//export nvmlDeviceGetModuleId
func nvmlDeviceGetModuleId() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetModuleId")
}

//export nvmlDeviceGetMultiGpuBoard
func nvmlDeviceGetMultiGpuBoard() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetMultiGpuBoard")
}

//export nvmlDeviceGetNumFans
func nvmlDeviceGetNumFans() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNumFans")
}

//export nvmlDeviceGetNumGpuCores
func nvmlDeviceGetNumGpuCores() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNumGpuCores")
}

//export nvmlDeviceGetNumaNodeId
func nvmlDeviceGetNumaNodeId() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNumaNodeId")
}

//export nvmlDeviceGetNvLinkCapability
func nvmlDeviceGetNvLinkCapability() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkCapability")
}

//export nvmlDeviceGetNvLinkErrorCounter
func nvmlDeviceGetNvLinkErrorCounter() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkErrorCounter")
}

//export nvmlDeviceGetNvLinkInfo
func nvmlDeviceGetNvLinkInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkInfo")
}

//export nvmlDeviceGetNvLinkRemoteDeviceType
func nvmlDeviceGetNvLinkRemoteDeviceType() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkRemoteDeviceType")
}

//export nvmlDeviceGetNvLinkRemotePciInfo_v1
func nvmlDeviceGetNvLinkRemotePciInfo_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkRemotePciInfo_v1")
}

//export nvmlDeviceGetNvLinkRemotePciInfo_v2
func nvmlDeviceGetNvLinkRemotePciInfo_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkRemotePciInfo_v2")
}

//export nvmlDeviceGetNvLinkState
func nvmlDeviceGetNvLinkState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkState")
}

//export nvmlDeviceGetNvLinkUtilizationControl
func nvmlDeviceGetNvLinkUtilizationControl() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkUtilizationControl")
}

//export nvmlDeviceGetNvLinkUtilizationCounter
func nvmlDeviceGetNvLinkUtilizationCounter() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkUtilizationCounter")
}

//export nvmlDeviceGetNvLinkVersion
func nvmlDeviceGetNvLinkVersion() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvLinkVersion")
}

//export nvmlDeviceGetNvlinkBwMode
func nvmlDeviceGetNvlinkBwMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvlinkBwMode")
}

//export nvmlDeviceGetNvlinkSupportedBwModes
func nvmlDeviceGetNvlinkSupportedBwModes() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetNvlinkSupportedBwModes")
}

//export nvmlDeviceGetOfaUtilization
func nvmlDeviceGetOfaUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetOfaUtilization")
}

//export nvmlDeviceGetP2PStatus
func nvmlDeviceGetP2PStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetP2PStatus")
}

//export nvmlDeviceGetPciInfoExt
func nvmlDeviceGetPciInfoExt() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPciInfoExt")
}

//export nvmlDeviceGetPcieLinkMaxSpeed
func nvmlDeviceGetPcieLinkMaxSpeed() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieLinkMaxSpeed")
}

//export nvmlDeviceGetPcieReplayCounter
func nvmlDeviceGetPcieReplayCounter() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieReplayCounter")
}

//export nvmlDeviceGetPcieSpeed
func nvmlDeviceGetPcieSpeed() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieSpeed")
}

//export nvmlDeviceGetPcieThroughput
func nvmlDeviceGetPcieThroughput() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPcieThroughput")
}

//export nvmlDeviceGetPdi
func nvmlDeviceGetPdi() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPdi")
}

//export nvmlDeviceGetPerformanceModes
func nvmlDeviceGetPerformanceModes() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPerformanceModes")
}

//export nvmlDeviceGetPerformanceState
func nvmlDeviceGetPerformanceState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPerformanceState")
}

//export nvmlDeviceGetPersistenceMode
func nvmlDeviceGetPersistenceMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPersistenceMode")
}

//export nvmlDeviceGetPgpuMetadataString
func nvmlDeviceGetPgpuMetadataString() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPgpuMetadataString")
}

//export nvmlDeviceGetPlatformInfo
func nvmlDeviceGetPlatformInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPlatformInfo")
}

//export nvmlDeviceGetPowerManagementDefaultLimit
func nvmlDeviceGetPowerManagementDefaultLimit() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementDefaultLimit")
}

//export nvmlDeviceGetPowerManagementLimit
func nvmlDeviceGetPowerManagementLimit() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementLimit")
}

//export nvmlDeviceGetPowerManagementLimitConstraints
func nvmlDeviceGetPowerManagementLimitConstraints() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementLimitConstraints")
}

//export nvmlDeviceGetPowerManagementMode
func nvmlDeviceGetPowerManagementMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerManagementMode")
}

//export nvmlDeviceGetPowerMizerMode_v1
func nvmlDeviceGetPowerMizerMode_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerMizerMode_v1")
}

//export nvmlDeviceGetPowerSource
func nvmlDeviceGetPowerSource() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerSource")
}

//export nvmlDeviceGetPowerState
func nvmlDeviceGetPowerState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerState")
}

//export nvmlDeviceGetPowerUsage
func nvmlDeviceGetPowerUsage() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetPowerUsage")
}

//export nvmlDeviceGetProcessUtilization
func nvmlDeviceGetProcessUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetProcessUtilization")
}

//export nvmlDeviceGetProcessesUtilizationInfo
func nvmlDeviceGetProcessesUtilizationInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetProcessesUtilizationInfo")
}

//export nvmlDeviceGetRemappedRows
func nvmlDeviceGetRemappedRows() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRemappedRows")
}

//export nvmlDeviceGetRepairStatus
func nvmlDeviceGetRepairStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRepairStatus")
}

//export nvmlDeviceGetRetiredPages
func nvmlDeviceGetRetiredPages() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRetiredPages")
}

//export nvmlDeviceGetRetiredPagesPendingStatus
func nvmlDeviceGetRetiredPagesPendingStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRetiredPagesPendingStatus")
}

//export nvmlDeviceGetRetiredPages_v2
func nvmlDeviceGetRetiredPages_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRetiredPages_v2")
}

//export nvmlDeviceGetRowRemapperHistogram
func nvmlDeviceGetRowRemapperHistogram() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRowRemapperHistogram")
}

//export nvmlDeviceGetRunningProcessDetailList
func nvmlDeviceGetRunningProcessDetailList() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetRunningProcessDetailList")
}

//export nvmlDeviceGetSamples
func nvmlDeviceGetSamples() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSamples")
}

//export nvmlDeviceGetSramEccErrorStatus
func nvmlDeviceGetSramEccErrorStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSramEccErrorStatus")
}

//export nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts
func nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSramUniqueUncorrectedEccErrorCounts")
}

//export nvmlDeviceGetSupportedClocksEventReasons
func nvmlDeviceGetSupportedClocksEventReasons() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedClocksEventReasons")
}

//export nvmlDeviceGetSupportedClocksThrottleReasons
func nvmlDeviceGetSupportedClocksThrottleReasons() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedClocksThrottleReasons")
}

//export nvmlDeviceGetSupportedEventTypes
func nvmlDeviceGetSupportedEventTypes() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedEventTypes")
}

//export nvmlDeviceGetSupportedGraphicsClocks
func nvmlDeviceGetSupportedGraphicsClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedGraphicsClocks")
}

//export nvmlDeviceGetSupportedMemoryClocks
func nvmlDeviceGetSupportedMemoryClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedMemoryClocks")
}

//export nvmlDeviceGetSupportedPerformanceStates
func nvmlDeviceGetSupportedPerformanceStates() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedPerformanceStates")
}

//export nvmlDeviceGetSupportedVgpus
func nvmlDeviceGetSupportedVgpus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetSupportedVgpus")
}

//export nvmlDeviceGetTargetFanSpeed
func nvmlDeviceGetTargetFanSpeed() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTargetFanSpeed")
}

//export nvmlDeviceGetTemperature
func nvmlDeviceGetTemperature() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTemperature")
}

//export nvmlDeviceGetTemperatureThreshold
func nvmlDeviceGetTemperatureThreshold() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTemperatureThreshold")
}

//export nvmlDeviceGetTemperatureV
func nvmlDeviceGetTemperatureV() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTemperatureV")
}

//export nvmlDeviceGetThermalSettings
func nvmlDeviceGetThermalSettings() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetThermalSettings")
}

//export nvmlDeviceGetTopologyCommonAncestor
func nvmlDeviceGetTopologyCommonAncestor() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTopologyCommonAncestor")
}

//export nvmlDeviceGetTopologyNearestGpus
func nvmlDeviceGetTopologyNearestGpus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTopologyNearestGpus")
}

//export nvmlDeviceGetTotalEccErrors
func nvmlDeviceGetTotalEccErrors() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTotalEccErrors")
}

//export nvmlDeviceGetTotalEnergyConsumption
func nvmlDeviceGetTotalEnergyConsumption() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetTotalEnergyConsumption")
}

//export nvmlDeviceGetUtilizationRates
func nvmlDeviceGetUtilizationRates() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetUtilizationRates")
}

//export nvmlDeviceGetVbiosVersion
func nvmlDeviceGetVbiosVersion() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVbiosVersion")
}

//export nvmlDeviceGetVgpuCapabilities
func nvmlDeviceGetVgpuCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuCapabilities")
}

//export nvmlDeviceGetVgpuHeterogeneousMode
func nvmlDeviceGetVgpuHeterogeneousMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuHeterogeneousMode")
}

//export nvmlDeviceGetVgpuInstancesUtilizationInfo
func nvmlDeviceGetVgpuInstancesUtilizationInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuInstancesUtilizationInfo")
}

//export nvmlDeviceGetVgpuMetadata
func nvmlDeviceGetVgpuMetadata() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuMetadata")
}

//export nvmlDeviceGetVgpuProcessUtilization
func nvmlDeviceGetVgpuProcessUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuProcessUtilization")
}

//export nvmlDeviceGetVgpuProcessesUtilizationInfo
func nvmlDeviceGetVgpuProcessesUtilizationInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuProcessesUtilizationInfo")
}

//export nvmlDeviceGetVgpuSchedulerCapabilities
func nvmlDeviceGetVgpuSchedulerCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuSchedulerCapabilities")
}

//export nvmlDeviceGetVgpuSchedulerLog
func nvmlDeviceGetVgpuSchedulerLog() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuSchedulerLog")
}

//export nvmlDeviceGetVgpuSchedulerState
func nvmlDeviceGetVgpuSchedulerState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuSchedulerState")
}

//export nvmlDeviceGetVgpuTypeCreatablePlacements
func nvmlDeviceGetVgpuTypeCreatablePlacements() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuTypeCreatablePlacements")
}

//export nvmlDeviceGetVgpuTypeSupportedPlacements
func nvmlDeviceGetVgpuTypeSupportedPlacements() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuTypeSupportedPlacements")
}

//export nvmlDeviceGetVgpuUtilization
func nvmlDeviceGetVgpuUtilization() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVgpuUtilization")
}

//export nvmlDeviceGetViolationStatus
func nvmlDeviceGetViolationStatus() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetViolationStatus")
}

//export nvmlDeviceGetVirtualizationMode
func nvmlDeviceGetVirtualizationMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceGetVirtualizationMode")
}

//export nvmlDeviceIsMigDeviceHandle
func nvmlDeviceIsMigDeviceHandle() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceIsMigDeviceHandle")
}

//export nvmlDeviceModifyDrainState
func nvmlDeviceModifyDrainState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceModifyDrainState")
}

//export nvmlDeviceOnSameBoard
func nvmlDeviceOnSameBoard() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceOnSameBoard")
}

//export nvmlDevicePowerSmoothingActivatePresetProfile
func nvmlDevicePowerSmoothingActivatePresetProfile() C.nvmlReturn_t {
	return stubReturn("nvmlDevicePowerSmoothingActivatePresetProfile")
}

//export nvmlDevicePowerSmoothingSetState
func nvmlDevicePowerSmoothingSetState() C.nvmlReturn_t {
	return stubReturn("nvmlDevicePowerSmoothingSetState")
}

//export nvmlDevicePowerSmoothingUpdatePresetProfileParam
func nvmlDevicePowerSmoothingUpdatePresetProfileParam() C.nvmlReturn_t {
	return stubReturn("nvmlDevicePowerSmoothingUpdatePresetProfileParam")
}

//export nvmlDeviceQueryDrainState
func nvmlDeviceQueryDrainState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceQueryDrainState")
}

//export nvmlDeviceReadWritePRM_v1
func nvmlDeviceReadWritePRM_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceReadWritePRM_v1")
}

//export nvmlDeviceRegisterEvents
func nvmlDeviceRegisterEvents() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceRegisterEvents")
}

//export nvmlDeviceRemoveGpu_v1
func nvmlDeviceRemoveGpu_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceRemoveGpu_v1")
}

//export nvmlDeviceRemoveGpu_v2
func nvmlDeviceRemoveGpu_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceRemoveGpu_v2")
}

//export nvmlDeviceResetApplicationsClocks
func nvmlDeviceResetApplicationsClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetApplicationsClocks")
}

//export nvmlDeviceResetGpuLockedClocks
func nvmlDeviceResetGpuLockedClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetGpuLockedClocks")
}

//export nvmlDeviceResetMemoryLockedClocks
func nvmlDeviceResetMemoryLockedClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetMemoryLockedClocks")
}

//export nvmlDeviceResetNvLinkErrorCounters
func nvmlDeviceResetNvLinkErrorCounters() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetNvLinkErrorCounters")
}

//export nvmlDeviceResetNvLinkUtilizationCounter
func nvmlDeviceResetNvLinkUtilizationCounter() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceResetNvLinkUtilizationCounter")
}

//export nvmlDeviceSetAPIRestriction
func nvmlDeviceSetAPIRestriction() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetAPIRestriction")
}

//export nvmlDeviceSetAccountingMode
func nvmlDeviceSetAccountingMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetAccountingMode")
}

//export nvmlDeviceSetApplicationsClocks
func nvmlDeviceSetApplicationsClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetApplicationsClocks")
}

//export nvmlDeviceSetAutoBoostedClocksEnabled
func nvmlDeviceSetAutoBoostedClocksEnabled() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetAutoBoostedClocksEnabled")
}

//export nvmlDeviceSetClockOffsets
func nvmlDeviceSetClockOffsets() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetClockOffsets")
}

//export nvmlDeviceSetComputeMode
func nvmlDeviceSetComputeMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetComputeMode")
}

//export nvmlDeviceSetConfComputeUnprotectedMemSize
func nvmlDeviceSetConfComputeUnprotectedMemSize() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetConfComputeUnprotectedMemSize")
}

//export nvmlDeviceSetCpuAffinity
func nvmlDeviceSetCpuAffinity() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetCpuAffinity")
}

//export nvmlDeviceSetDefaultAutoBoostedClocksEnabled
func nvmlDeviceSetDefaultAutoBoostedClocksEnabled() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDefaultAutoBoostedClocksEnabled")
}

//export nvmlDeviceSetDefaultFanSpeed_v2
func nvmlDeviceSetDefaultFanSpeed_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDefaultFanSpeed_v2")
}

//export nvmlDeviceSetDramEncryptionMode
func nvmlDeviceSetDramEncryptionMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDramEncryptionMode")
}

//export nvmlDeviceSetDriverModel
func nvmlDeviceSetDriverModel() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetDriverModel")
}

//export nvmlDeviceSetEccMode
func nvmlDeviceSetEccMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetEccMode")
}

//export nvmlDeviceSetFanControlPolicy
func nvmlDeviceSetFanControlPolicy() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetFanControlPolicy")
}

//export nvmlDeviceSetFanSpeed_v2
func nvmlDeviceSetFanSpeed_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetFanSpeed_v2")
}

//export nvmlDeviceSetGpcClkVfOffset
func nvmlDeviceSetGpcClkVfOffset() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetGpcClkVfOffset")
}

//export nvmlDeviceSetGpuLockedClocks
func nvmlDeviceSetGpuLockedClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetGpuLockedClocks")
}

//export nvmlDeviceSetGpuOperationMode
func nvmlDeviceSetGpuOperationMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetGpuOperationMode")
}

//export nvmlDeviceSetMemClkVfOffset
func nvmlDeviceSetMemClkVfOffset() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetMemClkVfOffset")
}

//export nvmlDeviceSetMemoryLockedClocks
func nvmlDeviceSetMemoryLockedClocks() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetMemoryLockedClocks")
}

//export nvmlDeviceSetMigMode
func nvmlDeviceSetMigMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetMigMode")
}

//export nvmlDeviceSetNvLinkDeviceLowPowerThreshold
func nvmlDeviceSetNvLinkDeviceLowPowerThreshold() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetNvLinkDeviceLowPowerThreshold")
}

//export nvmlDeviceSetNvLinkUtilizationControl
func nvmlDeviceSetNvLinkUtilizationControl() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetNvLinkUtilizationControl")
}

//export nvmlDeviceSetNvlinkBwMode
func nvmlDeviceSetNvlinkBwMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetNvlinkBwMode")
}

//export nvmlDeviceSetPersistenceMode
func nvmlDeviceSetPersistenceMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPersistenceMode")
}

//export nvmlDeviceSetPowerManagementLimit
func nvmlDeviceSetPowerManagementLimit() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPowerManagementLimit")
}

//export nvmlDeviceSetPowerManagementLimit_v2
func nvmlDeviceSetPowerManagementLimit_v2() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPowerManagementLimit_v2")
}

//export nvmlDeviceSetPowerMizerMode_v1
func nvmlDeviceSetPowerMizerMode_v1() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetPowerMizerMode_v1")
}

//export nvmlDeviceSetTemperatureThreshold
func nvmlDeviceSetTemperatureThreshold() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetTemperatureThreshold")
}

//export nvmlDeviceSetVgpuCapabilities
func nvmlDeviceSetVgpuCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVgpuCapabilities")
}

//export nvmlDeviceSetVgpuHeterogeneousMode
func nvmlDeviceSetVgpuHeterogeneousMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVgpuHeterogeneousMode")
}

//export nvmlDeviceSetVgpuSchedulerState
func nvmlDeviceSetVgpuSchedulerState() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVgpuSchedulerState")
}

//export nvmlDeviceSetVirtualizationMode
func nvmlDeviceSetVirtualizationMode() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceSetVirtualizationMode")
}

//export nvmlDeviceValidateInforom
func nvmlDeviceValidateInforom() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceValidateInforom")
}

//export nvmlDeviceWorkloadPowerProfileClearRequestedProfiles
func nvmlDeviceWorkloadPowerProfileClearRequestedProfiles() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileClearRequestedProfiles")
}

//export nvmlDeviceWorkloadPowerProfileGetCurrentProfiles
func nvmlDeviceWorkloadPowerProfileGetCurrentProfiles() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileGetCurrentProfiles")
}

//export nvmlDeviceWorkloadPowerProfileGetProfilesInfo
func nvmlDeviceWorkloadPowerProfileGetProfilesInfo() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileGetProfilesInfo")
}

//export nvmlDeviceWorkloadPowerProfileSetRequestedProfiles
func nvmlDeviceWorkloadPowerProfileSetRequestedProfiles() C.nvmlReturn_t {
	return stubReturn("nvmlDeviceWorkloadPowerProfileSetRequestedProfiles")
}

//export nvmlEventSetCreate
func nvmlEventSetCreate() C.nvmlReturn_t {
	return stubReturn("nvmlEventSetCreate")
}

//export nvmlEventSetFree
func nvmlEventSetFree() C.nvmlReturn_t {
	return stubReturn("nvmlEventSetFree")
}

//export nvmlEventSetWait_v1
func nvmlEventSetWait_v1() C.nvmlReturn_t {
	return stubReturn("nvmlEventSetWait_v1")
}

//export nvmlEventSetWait_v2
func nvmlEventSetWait_v2() C.nvmlReturn_t {
	return stubReturn("nvmlEventSetWait_v2")
}

//export nvmlGetExcludedDeviceCount
func nvmlGetExcludedDeviceCount() C.nvmlReturn_t {
	return stubReturn("nvmlGetExcludedDeviceCount")
}

//export nvmlGetExcludedDeviceInfoByIndex
func nvmlGetExcludedDeviceInfoByIndex() C.nvmlReturn_t {
	return stubReturn("nvmlGetExcludedDeviceInfoByIndex")
}

//export nvmlGetVgpuCompatibility
func nvmlGetVgpuCompatibility() C.nvmlReturn_t {
	return stubReturn("nvmlGetVgpuCompatibility")
}

//export nvmlGetVgpuDriverCapabilities
func nvmlGetVgpuDriverCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlGetVgpuDriverCapabilities")
}

//export nvmlGetVgpuVersion
func nvmlGetVgpuVersion() C.nvmlReturn_t {
	return stubReturn("nvmlGetVgpuVersion")
}

//export nvmlGpmMetricsGet
func nvmlGpmMetricsGet() C.nvmlReturn_t {
	return stubReturn("nvmlGpmMetricsGet")
}

//export nvmlGpmMigSampleGet
func nvmlGpmMigSampleGet() C.nvmlReturn_t {
	return stubReturn("nvmlGpmMigSampleGet")
}

//export nvmlGpmQueryDeviceSupport
func nvmlGpmQueryDeviceSupport() C.nvmlReturn_t {
	return stubReturn("nvmlGpmQueryDeviceSupport")
}

//export nvmlGpmQueryIfStreamingEnabled
func nvmlGpmQueryIfStreamingEnabled() C.nvmlReturn_t {
	return stubReturn("nvmlGpmQueryIfStreamingEnabled")
}

//export nvmlGpmSampleAlloc
func nvmlGpmSampleAlloc() C.nvmlReturn_t {
	return stubReturn("nvmlGpmSampleAlloc")
}

//export nvmlGpmSampleFree
func nvmlGpmSampleFree() C.nvmlReturn_t {
	return stubReturn("nvmlGpmSampleFree")
}

//export nvmlGpmSampleGet
func nvmlGpmSampleGet() C.nvmlReturn_t {
	return stubReturn("nvmlGpmSampleGet")
}

//export nvmlGpmSetStreamingEnabled
func nvmlGpmSetStreamingEnabled() C.nvmlReturn_t {
	return stubReturn("nvmlGpmSetStreamingEnabled")
}

//export nvmlGpuInstanceCreateComputeInstance
func nvmlGpuInstanceCreateComputeInstance() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceCreateComputeInstance")
}

//export nvmlGpuInstanceCreateComputeInstanceWithPlacement
func nvmlGpuInstanceCreateComputeInstanceWithPlacement() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceCreateComputeInstanceWithPlacement")
}

//export nvmlGpuInstanceDestroy
func nvmlGpuInstanceDestroy() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceDestroy")
}

//export nvmlGpuInstanceGetActiveVgpus
func nvmlGpuInstanceGetActiveVgpus() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetActiveVgpus")
}

//export nvmlGpuInstanceGetComputeInstanceById
func nvmlGpuInstanceGetComputeInstanceById() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceById")
}

//export nvmlGpuInstanceGetComputeInstancePossiblePlacements
func nvmlGpuInstanceGetComputeInstancePossiblePlacements() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstancePossiblePlacements")
}

//export nvmlGpuInstanceGetComputeInstanceProfileInfo
func nvmlGpuInstanceGetComputeInstanceProfileInfo() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceProfileInfo")
}

//export nvmlGpuInstanceGetComputeInstanceProfileInfoV
func nvmlGpuInstanceGetComputeInstanceProfileInfoV() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceProfileInfoV")
}

//export nvmlGpuInstanceGetComputeInstanceRemainingCapacity
func nvmlGpuInstanceGetComputeInstanceRemainingCapacity() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstanceRemainingCapacity")
}

//export nvmlGpuInstanceGetComputeInstances
func nvmlGpuInstanceGetComputeInstances() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetComputeInstances")
}

//export nvmlGpuInstanceGetCreatableVgpus
func nvmlGpuInstanceGetCreatableVgpus() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetCreatableVgpus")
}

//export nvmlGpuInstanceGetInfo
func nvmlGpuInstanceGetInfo() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetInfo")
}

//export nvmlGpuInstanceGetVgpuHeterogeneousMode
func nvmlGpuInstanceGetVgpuHeterogeneousMode() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuHeterogeneousMode")
}

//export nvmlGpuInstanceGetVgpuSchedulerLog
func nvmlGpuInstanceGetVgpuSchedulerLog() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuSchedulerLog")
}

//export nvmlGpuInstanceGetVgpuSchedulerState
func nvmlGpuInstanceGetVgpuSchedulerState() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuSchedulerState")
}

//export nvmlGpuInstanceGetVgpuTypeCreatablePlacements
func nvmlGpuInstanceGetVgpuTypeCreatablePlacements() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceGetVgpuTypeCreatablePlacements")
}

//export nvmlGpuInstanceSetVgpuHeterogeneousMode
func nvmlGpuInstanceSetVgpuHeterogeneousMode() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceSetVgpuHeterogeneousMode")
}

//export nvmlGpuInstanceSetVgpuSchedulerState
func nvmlGpuInstanceSetVgpuSchedulerState() C.nvmlReturn_t {
	return stubReturn("nvmlGpuInstanceSetVgpuSchedulerState")
}

//export nvmlSetVgpuVersion
func nvmlSetVgpuVersion() C.nvmlReturn_t {
	return stubReturn("nvmlSetVgpuVersion")
}

//export nvmlSystemEventSetCreate
func nvmlSystemEventSetCreate() C.nvmlReturn_t {
	return stubReturn("nvmlSystemEventSetCreate")
}

//export nvmlSystemEventSetFree
func nvmlSystemEventSetFree() C.nvmlReturn_t {
	return stubReturn("nvmlSystemEventSetFree")
}

//export nvmlSystemEventSetWait
func nvmlSystemEventSetWait() C.nvmlReturn_t {
	return stubReturn("nvmlSystemEventSetWait")
}

//export nvmlSystemGetConfComputeCapabilities
func nvmlSystemGetConfComputeCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeCapabilities")
}

//export nvmlSystemGetConfComputeGpusReadyState
func nvmlSystemGetConfComputeGpusReadyState() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeGpusReadyState")
}

//export nvmlSystemGetConfComputeKeyRotationThresholdInfo
func nvmlSystemGetConfComputeKeyRotationThresholdInfo() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeKeyRotationThresholdInfo")
}

//export nvmlSystemGetConfComputeSettings
func nvmlSystemGetConfComputeSettings() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeSettings")
}

//export nvmlSystemGetConfComputeState
func nvmlSystemGetConfComputeState() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetConfComputeState")
}

//export nvmlSystemGetDriverBranch
func nvmlSystemGetDriverBranch() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetDriverBranch")
}

//export nvmlSystemGetHicVersion
func nvmlSystemGetHicVersion() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetHicVersion")
}

//export nvmlSystemGetNvlinkBwMode
func nvmlSystemGetNvlinkBwMode() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetNvlinkBwMode")
}

//export nvmlSystemGetProcessName
func nvmlSystemGetProcessName() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetProcessName")
}

//export nvmlSystemGetTopologyGpuSet
func nvmlSystemGetTopologyGpuSet() C.nvmlReturn_t {
	return stubReturn("nvmlSystemGetTopologyGpuSet")
}

//export nvmlSystemRegisterEvents
func nvmlSystemRegisterEvents() C.nvmlReturn_t {
	return stubReturn("nvmlSystemRegisterEvents")
}

//export nvmlSystemSetConfComputeGpusReadyState
func nvmlSystemSetConfComputeGpusReadyState() C.nvmlReturn_t {
	return stubReturn("nvmlSystemSetConfComputeGpusReadyState")
}

//export nvmlSystemSetConfComputeKeyRotationThresholdInfo
func nvmlSystemSetConfComputeKeyRotationThresholdInfo() C.nvmlReturn_t {
	return stubReturn("nvmlSystemSetConfComputeKeyRotationThresholdInfo")
}

//export nvmlSystemSetNvlinkBwMode
func nvmlSystemSetNvlinkBwMode() C.nvmlReturn_t {
	return stubReturn("nvmlSystemSetNvlinkBwMode")
}

//export nvmlUnitGetCount
func nvmlUnitGetCount() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetCount")
}

//export nvmlUnitGetDevices
func nvmlUnitGetDevices() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetDevices")
}

//export nvmlUnitGetFanSpeedInfo
func nvmlUnitGetFanSpeedInfo() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetFanSpeedInfo")
}

//export nvmlUnitGetHandleByIndex
func nvmlUnitGetHandleByIndex() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetHandleByIndex")
}

//export nvmlUnitGetLedState
func nvmlUnitGetLedState() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetLedState")
}

//export nvmlUnitGetPsuInfo
func nvmlUnitGetPsuInfo() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetPsuInfo")
}

//export nvmlUnitGetTemperature
func nvmlUnitGetTemperature() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetTemperature")
}

//export nvmlUnitGetUnitInfo
func nvmlUnitGetUnitInfo() C.nvmlReturn_t {
	return stubReturn("nvmlUnitGetUnitInfo")
}

//export nvmlUnitSetLedState
func nvmlUnitSetLedState() C.nvmlReturn_t {
	return stubReturn("nvmlUnitSetLedState")
}

//export nvmlVgpuInstanceClearAccountingPids
func nvmlVgpuInstanceClearAccountingPids() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceClearAccountingPids")
}

//export nvmlVgpuInstanceGetAccountingMode
func nvmlVgpuInstanceGetAccountingMode() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetAccountingMode")
}

//export nvmlVgpuInstanceGetAccountingPids
func nvmlVgpuInstanceGetAccountingPids() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetAccountingPids")
}

//export nvmlVgpuInstanceGetAccountingStats
func nvmlVgpuInstanceGetAccountingStats() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetAccountingStats")
}

//export nvmlVgpuInstanceGetEccMode
func nvmlVgpuInstanceGetEccMode() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEccMode")
}

//export nvmlVgpuInstanceGetEncoderCapacity
func nvmlVgpuInstanceGetEncoderCapacity() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEncoderCapacity")
}

//export nvmlVgpuInstanceGetEncoderSessions
func nvmlVgpuInstanceGetEncoderSessions() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEncoderSessions")
}

//export nvmlVgpuInstanceGetEncoderStats
func nvmlVgpuInstanceGetEncoderStats() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetEncoderStats")
}

//export nvmlVgpuInstanceGetFBCSessions
func nvmlVgpuInstanceGetFBCSessions() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFBCSessions")
}

//export nvmlVgpuInstanceGetFBCStats
func nvmlVgpuInstanceGetFBCStats() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFBCStats")
}

//export nvmlVgpuInstanceGetFbUsage
func nvmlVgpuInstanceGetFbUsage() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFbUsage")
}

//export nvmlVgpuInstanceGetFrameRateLimit
func nvmlVgpuInstanceGetFrameRateLimit() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetFrameRateLimit")
}

//export nvmlVgpuInstanceGetGpuInstanceId
func nvmlVgpuInstanceGetGpuInstanceId() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetGpuInstanceId")
}

//export nvmlVgpuInstanceGetGpuPciId
func nvmlVgpuInstanceGetGpuPciId() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetGpuPciId")
}

//export nvmlVgpuInstanceGetLicenseInfo_v1
func nvmlVgpuInstanceGetLicenseInfo_v1() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetLicenseInfo_v1")
}

//export nvmlVgpuInstanceGetLicenseInfo_v2
func nvmlVgpuInstanceGetLicenseInfo_v2() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetLicenseInfo_v2")
}

//export nvmlVgpuInstanceGetLicenseStatus
func nvmlVgpuInstanceGetLicenseStatus() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetLicenseStatus")
}

//export nvmlVgpuInstanceGetMdevUUID
func nvmlVgpuInstanceGetMdevUUID() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetMdevUUID")
}

//export nvmlVgpuInstanceGetMetadata
func nvmlVgpuInstanceGetMetadata() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetMetadata")
}

//export nvmlVgpuInstanceGetPlacementId
func nvmlVgpuInstanceGetPlacementId() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetPlacementId")
}

//export nvmlVgpuInstanceGetRuntimeStateSize
func nvmlVgpuInstanceGetRuntimeStateSize() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetRuntimeStateSize")
}

//export nvmlVgpuInstanceGetType
func nvmlVgpuInstanceGetType() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetType")
}

//export nvmlVgpuInstanceGetUUID
func nvmlVgpuInstanceGetUUID() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetUUID")
}

//export nvmlVgpuInstanceGetVmDriverVersion
func nvmlVgpuInstanceGetVmDriverVersion() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetVmDriverVersion")
}

//export nvmlVgpuInstanceGetVmID
func nvmlVgpuInstanceGetVmID() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceGetVmID")
}

//export nvmlVgpuInstanceSetEncoderCapacity
func nvmlVgpuInstanceSetEncoderCapacity() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuInstanceSetEncoderCapacity")
}

//export nvmlVgpuTypeGetBAR1Info
func nvmlVgpuTypeGetBAR1Info() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetBAR1Info")
}

//export nvmlVgpuTypeGetCapabilities
func nvmlVgpuTypeGetCapabilities() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetCapabilities")
}

//export nvmlVgpuTypeGetClass
func nvmlVgpuTypeGetClass() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetClass")
}

//export nvmlVgpuTypeGetDeviceID
func nvmlVgpuTypeGetDeviceID() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetDeviceID")
}

//export nvmlVgpuTypeGetFbReservation
func nvmlVgpuTypeGetFbReservation() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetFbReservation")
}

//export nvmlVgpuTypeGetFrameRateLimit
func nvmlVgpuTypeGetFrameRateLimit() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetFrameRateLimit")
}

//export nvmlVgpuTypeGetFramebufferSize
func nvmlVgpuTypeGetFramebufferSize() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetFramebufferSize")
}

//export nvmlVgpuTypeGetGpuInstanceProfileId
func nvmlVgpuTypeGetGpuInstanceProfileId() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetGpuInstanceProfileId")
}

//export nvmlVgpuTypeGetGspHeapSize
func nvmlVgpuTypeGetGspHeapSize() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetGspHeapSize")
}

//export nvmlVgpuTypeGetLicense
func nvmlVgpuTypeGetLicense() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetLicense")
}

//export nvmlVgpuTypeGetMaxInstances
func nvmlVgpuTypeGetMaxInstances() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetMaxInstances")
}

//export nvmlVgpuTypeGetMaxInstancesPerGpuInstance
func nvmlVgpuTypeGetMaxInstancesPerGpuInstance() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetMaxInstancesPerGpuInstance")
}

//export nvmlVgpuTypeGetMaxInstancesPerVm
func nvmlVgpuTypeGetMaxInstancesPerVm() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetMaxInstancesPerVm")
}

//export nvmlVgpuTypeGetName
func nvmlVgpuTypeGetName() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetName")
}

//export nvmlVgpuTypeGetNumDisplayHeads
func nvmlVgpuTypeGetNumDisplayHeads() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetNumDisplayHeads")
}

//export nvmlVgpuTypeGetResolution
func nvmlVgpuTypeGetResolution() C.nvmlReturn_t {
	return stubReturn("nvmlVgpuTypeGetResolution")
}
