# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvml-mock.fullname" . }}
  labels:
    {{- include "nvml-mock.labels" . | nindent 4 }}
