//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUBoard) DeepCopyInto(out *GPUBoard) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUBoard.
func (in *GPUBoard) DeepCopy() *GPUBoard {
	if in == nil {
		return nil
	}
	out := new(GPUBoard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCapabilities) DeepCopyInto(out *GPUCapabilities) {
	*out = *in
	out.MIG = in.MIG
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]GPUCapabilityAttribute, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCapabilities.
func (in *GPUCapabilities) DeepCopy() *GPUCapabilities {
	if in == nil {
		return nil
	}
	out := new(GPUCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCapabilityAttribute) DeepCopyInto(out *GPUCapabilityAttribute) {
	*out = *in
	if in.Bool != nil {
		in, out := &in.Bool, &out.Bool
		*out = new(bool)
		**out = **in
	}
	if in.Strings != nil {
		in, out := &in.Strings, &out.Strings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCapabilityAttribute.
func (in *GPUCapabilityAttribute) DeepCopy() *GPUCapabilityAttribute {
	if in == nil {
		return nil
	}
	out := new(GPUCapabilityAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClockSet) DeepCopyInto(out *GPUClockSet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClockSet.
func (in *GPUClockSet) DeepCopy() *GPUClockSet {
	if in == nil {
		return nil
	}
	out := new(GPUClockSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClocks) DeepCopyInto(out *GPUClocks) {
	*out = *in
	out.MaximumMHz = in.MaximumMHz
	if in.Supported != nil {
		in, out := &in.Supported, &out.Supported
		*out = make([]GPUSupportedClock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClocks.
func (in *GPUClocks) DeepCopy() *GPUClocks {
	if in == nil {
		return nil
	}
	out := new(GPUClocks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUComputeCapability) DeepCopyInto(out *GPUComputeCapability) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUComputeCapability.
func (in *GPUComputeCapability) DeepCopy() *GPUComputeCapability {
	if in == nil {
		return nil
	}
	out := new(GPUComputeCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCores) DeepCopyInto(out *GPUCores) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCores.
func (in *GPUCores) DeepCopy() *GPUCores {
	if in == nil {
		return nil
	}
	out := new(GPUCores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmware) DeepCopyInto(out *GPUFirmware) {
	*out = *in
	out.InfoROM = in.InfoROM
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmware.
func (in *GPUFirmware) DeepCopy() *GPUFirmware {
	if in == nil {
		return nil
	}
	out := new(GPUFirmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUInfoROM) DeepCopyInto(out *GPUInfoROM) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUInfoROM.
func (in *GPUInfoROM) DeepCopy() *GPUInfoROM {
	if in == nil {
		return nil
	}
	out := new(GPUInfoROM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGCapability) DeepCopyInto(out *GPUMIGCapability) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGCapability.
func (in *GPUMIGCapability) DeepCopy() *GPUMIGCapability {
	if in == nil {
		return nil
	}
	out := new(GPUMIGCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMemory) DeepCopyInto(out *GPUMemory) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	out.Reserved = in.Reserved.DeepCopy()
	out.BAR1Capacity = in.BAR1Capacity.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMemory.
func (in *GPUMemory) DeepCopy() *GPUMemory {
	if in == nil {
		return nil
	}
	out := new(GPUMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUModel) DeepCopyInto(out *GPUModel) {
	*out = *in
	out.ComputeCapability = in.ComputeCapability
	out.Cores = in.Cores
	out.Board = in.Board
	out.Firmware = in.Firmware
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUModel.
func (in *GPUModel) DeepCopy() *GPUModel {
	if in == nil {
		return nil
	}
	out := new(GPUModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPCI) DeepCopyInto(out *GPUPCI) {
	*out = *in
	out.MaxLink = in.MaxLink
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPCI.
func (in *GPUPCI) DeepCopy() *GPUPCI {
	if in == nil {
		return nil
	}
	out := new(GPUPCI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPCILink) DeepCopyInto(out *GPUPCILink) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPCILink.
func (in *GPUPCILink) DeepCopy() *GPUPCILink {
	if in == nil {
		return nil
	}
	out := new(GPUPCILink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPower) DeepCopyInto(out *GPUPower) {
	*out = *in
	out.LimitsMilliWatts = in.LimitsMilliWatts
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPower.
func (in *GPUPower) DeepCopy() *GPUPower {
	if in == nil {
		return nil
	}
	out := new(GPUPower)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPowerLimits) DeepCopyInto(out *GPUPowerLimits) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPowerLimits.
func (in *GPUPowerLimits) DeepCopy() *GPUPowerLimits {
	if in == nil {
		return nil
	}
	out := new(GPUPowerLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSupportedClock) DeepCopyInto(out *GPUSupportedClock) {
	*out = *in
	if in.GraphicsMHz != nil {
		in, out := &in.GraphicsMHz, &out.GraphicsMHz
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSupportedClock.
func (in *GPUSupportedClock) DeepCopy() *GPUSupportedClock {
	if in == nil {
		return nil
	}
	out := new(GPUSupportedClock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUThermal) DeepCopyInto(out *GPUThermal) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUThermal.
func (in *GPUThermal) DeepCopy() *GPUThermal {
	if in == nil {
		return nil
	}
	out := new(GPUThermal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUCapacity) DeepCopyInto(out *SGPUCapacity) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUCapacity.
func (in *SGPUCapacity) DeepCopy() *SGPUCapacity {
	if in == nil {
		return nil
	}
	out := new(SGPUCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUGPUFabric) DeepCopyInto(out *SGPUGPUFabric) {
	*out = *in
	out.Domain = in.Domain
	if in.Switches != nil {
		in, out := &in.Switches, &out.Switches
		*out = new(SGPUGPUFabricSwitches)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUGPUFabric.
func (in *SGPUGPUFabric) DeepCopy() *SGPUGPUFabric {
	if in == nil {
		return nil
	}
	out := new(SGPUGPUFabric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUGPUFabricDomain) DeepCopyInto(out *SGPUGPUFabricDomain) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUGPUFabricDomain.
func (in *SGPUGPUFabricDomain) DeepCopy() *SGPUGPUFabricDomain {
	if in == nil {
		return nil
	}
	out := new(SGPUGPUFabricDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUGPUFabricSwitches) DeepCopyInto(out *SGPUGPUFabricSwitches) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUGPUFabricSwitches.
func (in *SGPUGPUFabricSwitches) DeepCopy() *SGPUGPUFabricSwitches {
	if in == nil {
		return nil
	}
	out := new(SGPUGPUFabricSwitches)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUGPUSlot) DeepCopyInto(out *SGPUGPUSlot) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUGPUSlot.
func (in *SGPUGPUSlot) DeepCopy() *SGPUGPUSlot {
	if in == nil {
		return nil
	}
	out := new(SGPUGPUSlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUHardware) DeepCopyInto(out *SGPUHardware) {
	*out = *in
	out.Model = in.Model
	in.Memory.DeepCopyInto(&out.Memory)
	out.PCI = in.PCI
	out.Power = in.Power
	out.Thermal = in.Thermal
	in.Clocks.DeepCopyInto(&out.Clocks)
	in.Capabilities.DeepCopyInto(&out.Capabilities)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUHardware.
func (in *SGPUHardware) DeepCopy() *SGPUHardware {
	if in == nil {
		return nil
	}
	out := new(SGPUHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUHost) DeepCopyInto(out *SGPUHost) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(SGPUHostCPU)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(SGPUHostMemory)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUHost.
func (in *SGPUHost) DeepCopy() *SGPUHost {
	if in == nil {
		return nil
	}
	out := new(SGPUHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUHostCPU) DeepCopyInto(out *SGPUHostCPU) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUHostCPU.
func (in *SGPUHostCPU) DeepCopy() *SGPUHostCPU {
	if in == nil {
		return nil
	}
	out := new(SGPUHostCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUHostMemory) DeepCopyInto(out *SGPUHostMemory) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUHostMemory.
func (in *SGPUHostMemory) DeepCopy() *SGPUHostMemory {
	if in == nil {
		return nil
	}
	out := new(SGPUHostMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventory) DeepCopyInto(out *SGPUInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventory.
func (in *SGPUInventory) DeepCopy() *SGPUInventory {
	if in == nil {
		return nil
	}
	out := new(SGPUInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventoryList) DeepCopyInto(out *SGPUInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SGPUInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventoryList.
func (in *SGPUInventoryList) DeepCopy() *SGPUInventoryList {
	if in == nil {
		return nil
	}
	out := new(SGPUInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventorySpec) DeepCopyInto(out *SGPUInventorySpec) {
	*out = *in
	if in.RackGroups != nil {
		in, out := &in.RackGroups, &out.RackGroups
		*out = make([]SGPURackGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventorySpec.
func (in *SGPUInventorySpec) DeepCopy() *SGPUInventorySpec {
	if in == nil {
		return nil
	}
	out := new(SGPUInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventoryStatus) DeepCopyInto(out *SGPUInventoryStatus) {
	*out = *in
	out.Capacity = in.Capacity
	out.Usage = in.Usage
	if in.RackGroups != nil {
		in, out := &in.RackGroups, &out.RackGroups
		*out = make([]SGPURackGroupStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventoryStatus.
func (in *SGPUInventoryStatus) DeepCopy() *SGPUInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(SGPUInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUNetwork) DeepCopyInto(out *SGPUNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUNetwork.
func (in *SGPUNetwork) DeepCopy() *SGPUNetwork {
	if in == nil {
		return nil
	}
	out := new(SGPUNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUNodeReference) DeepCopyInto(out *SGPUNodeReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUNodeReference.
func (in *SGPUNodeReference) DeepCopy() *SGPUNodeReference {
	if in == nil {
		return nil
	}
	out := new(SGPUNodeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUNodeTopology) DeepCopyInto(out *SGPUNodeTopology) {
	*out = *in
	if in.GPUSlots != nil {
		in, out := &in.GPUSlots, &out.GPUSlots
		*out = make([]SGPUGPUSlot, len(*in))
		copy(*out, *in)
	}
	if in.GPUFabric != nil {
		in, out := &in.GPUFabric, &out.GPUFabric
		*out = new(SGPUGPUFabric)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(SGPUNetwork)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUNodeTopology.
func (in *SGPUNodeTopology) DeepCopy() *SGPUNodeTopology {
	if in == nil {
		return nil
	}
	out := new(SGPUNodeTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUPlacement) DeepCopyInto(out *SGPUPlacement) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUPlacement.
func (in *SGPUPlacement) DeepCopy() *SGPUPlacement {
	if in == nil {
		return nil
	}
	out := new(SGPUPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfile) DeepCopyInto(out *SGPUProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfile.
func (in *SGPUProfile) DeepCopy() *SGPUProfile {
	if in == nil {
		return nil
	}
	out := new(SGPUProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileList) DeepCopyInto(out *SGPUProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SGPUProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileList.
func (in *SGPUProfileList) DeepCopy() *SGPUProfileList {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileNode) DeepCopyInto(out *SGPUProfileNode) {
	*out = *in
	in.GPUs.DeepCopyInto(&out.GPUs)
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(SGPUHost)
		(*in).DeepCopyInto(*out)
	}
	in.Topology.DeepCopyInto(&out.Topology)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileNode.
func (in *SGPUProfileNode) DeepCopy() *SGPUProfileNode {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileRack) DeepCopyInto(out *SGPUProfileRack) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileRack.
func (in *SGPUProfileRack) DeepCopy() *SGPUProfileRack {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileRack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileSpec) DeepCopyInto(out *SGPUProfileSpec) {
	*out = *in
	out.Rack = in.Rack
	in.Node.DeepCopyInto(&out.Node)
	out.Software = in.Software
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileSpec.
func (in *SGPUProfileSpec) DeepCopy() *SGPUProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURack) DeepCopyInto(out *SGPURack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURack.
func (in *SGPURack) DeepCopy() *SGPURack {
	if in == nil {
		return nil
	}
	out := new(SGPURack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPURack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackGPU) DeepCopyInto(out *SGPURackGPU) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackGPU.
func (in *SGPURackGPU) DeepCopy() *SGPURackGPU {
	if in == nil {
		return nil
	}
	out := new(SGPURackGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackGroup) DeepCopyInto(out *SGPURackGroup) {
	*out = *in
	out.ProfileRef = in.ProfileRef
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(SGPUPlacement)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackGroup.
func (in *SGPURackGroup) DeepCopy() *SGPURackGroup {
	if in == nil {
		return nil
	}
	out := new(SGPURackGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackGroupStatus) DeepCopyInto(out *SGPURackGroupStatus) {
	*out = *in
	out.Capacity = in.Capacity
	out.Usage = in.Usage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackGroupStatus.
func (in *SGPURackGroupStatus) DeepCopy() *SGPURackGroupStatus {
	if in == nil {
		return nil
	}
	out := new(SGPURackGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackIdentity) DeepCopyInto(out *SGPURackIdentity) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackIdentity.
func (in *SGPURackIdentity) DeepCopy() *SGPURackIdentity {
	if in == nil {
		return nil
	}
	out := new(SGPURackIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackInventoryReference) DeepCopyInto(out *SGPURackInventoryReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackInventoryReference.
func (in *SGPURackInventoryReference) DeepCopy() *SGPURackInventoryReference {
	if in == nil {
		return nil
	}
	out := new(SGPURackInventoryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackList) DeepCopyInto(out *SGPURackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SGPURack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackList.
func (in *SGPURackList) DeepCopy() *SGPURackList {
	if in == nil {
		return nil
	}
	out := new(SGPURackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPURackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackProfileReference) DeepCopyInto(out *SGPURackProfileReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackProfileReference.
func (in *SGPURackProfileReference) DeepCopy() *SGPURackProfileReference {
	if in == nil {
		return nil
	}
	out := new(SGPURackProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackSlot) DeepCopyInto(out *SGPURackSlot) {
	*out = *in
	if in.NodeRef != nil {
		in, out := &in.NodeRef, &out.NodeRef
		*out = new(SGPUNodeReference)
		**out = **in
	}
	if in.GPUs != nil {
		in, out := &in.GPUs, &out.GPUs
		*out = make([]SGPURackGPU, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackSlot.
func (in *SGPURackSlot) DeepCopy() *SGPURackSlot {
	if in == nil {
		return nil
	}
	out := new(SGPURackSlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackSpec) DeepCopyInto(out *SGPURackSpec) {
	*out = *in
	out.InventoryRef = in.InventoryRef
	out.ProfileRef = in.ProfileRef
	out.Identity = in.Identity
	if in.GPUFabric != nil {
		in, out := &in.GPUFabric, &out.GPUFabric
		*out = new(SGPUGPUFabric)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(SGPUNetwork)
		**out = **in
	}
	if in.Slots != nil {
		in, out := &in.Slots, &out.Slots
		*out = make([]SGPURackSlot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackSpec.
func (in *SGPURackSpec) DeepCopy() *SGPURackSpec {
	if in == nil {
		return nil
	}
	out := new(SGPURackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURackStatus) DeepCopyInto(out *SGPURackStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURackStatus.
func (in *SGPURackStatus) DeepCopy() *SGPURackStatus {
	if in == nil {
		return nil
	}
	out := new(SGPURackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUSoftware) DeepCopyInto(out *SGPUSoftware) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUSoftware.
func (in *SGPUSoftware) DeepCopy() *SGPUSoftware {
	if in == nil {
		return nil
	}
	out := new(SGPUSoftware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUUsage) DeepCopyInto(out *SGPUUsage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUUsage.
func (in *SGPUUsage) DeepCopy() *SGPUUsage {
	if in == nil {
		return nil
	}
	out := new(SGPUUsage)
	in.DeepCopyInto(out)
	return out
}
