# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright 2026 NVIDIA CORPORATION

processor:
  ignoreTypes:
    - "(.+)List$"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: "1.32"
