# RuntimeClass for NVIDIA GPU support
#
# This RuntimeClass tells Kubernetes to use the nvidia runtime
# for containers that request it.

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
