//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityAttribute) DeepCopyInto(out *CapabilityAttribute) {
	*out = *in
	if in.Bool != nil {
		in, out := &in.Bool, &out.Bool
		*out = new(bool)
		**out = **in
	}
	if in.Int != nil {
		in, out := &in.Int, &out.Int
		*out = new(int64)
		**out = **in
	}
	if in.Strings != nil {
		in, out := &in.Strings, &out.Strings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityAttribute.
func (in *CapabilityAttribute) DeepCopy() *CapabilityAttribute {
	if in == nil {
		return nil
	}
	out := new(CapabilityAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClockRates) DeepCopyInto(out *ClockRates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClockRates.
func (in *ClockRates) DeepCopy() *ClockRates {
	if in == nil {
		return nil
	}
	out := new(ClockRates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClocksTelemetry) DeepCopyInto(out *ClocksTelemetry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClocksTelemetry.
func (in *ClocksTelemetry) DeepCopy() *ClocksTelemetry {
	if in == nil {
		return nil
	}
	out := new(ClocksTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeCapability) DeepCopyInto(out *ComputeCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeCapability.
func (in *ComputeCapability) DeepCopy() *ComputeCapability {
	if in == nil {
		return nil
	}
	out := new(ComputeCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricDomain) DeepCopyInto(out *FabricDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricDomain.
func (in *FabricDomain) DeepCopy() *FabricDomain {
	if in == nil {
		return nil
	}
	out := new(FabricDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSwitches) DeepCopyInto(out *FabricSwitches) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSwitches.
func (in *FabricSwitches) DeepCopy() *FabricSwitches {
	if in == nil {
		return nil
	}
	out := new(FabricSwitches)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUBoard) DeepCopyInto(out *GPUBoard) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUBoard.
func (in *GPUBoard) DeepCopy() *GPUBoard {
	if in == nil {
		return nil
	}
	out := new(GPUBoard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCapabilities) DeepCopyInto(out *GPUCapabilities) {
	*out = *in
	if in.MIG != nil {
		in, out := &in.MIG, &out.MIG
		*out = new(MIGCapability)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]CapabilityAttribute, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCapabilities.
func (in *GPUCapabilities) DeepCopy() *GPUCapabilities {
	if in == nil {
		return nil
	}
	out := new(GPUCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClocks) DeepCopyInto(out *GPUClocks) {
	*out = *in
	if in.MaximumMHz != nil {
		in, out := &in.MaximumMHz, &out.MaximumMHz
		*out = new(ClockRates)
		**out = **in
	}
	if in.Supported != nil {
		in, out := &in.Supported, &out.Supported
		*out = make([]SupportedClocks, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClocks.
func (in *GPUClocks) DeepCopy() *GPUClocks {
	if in == nil {
		return nil
	}
	out := new(GPUClocks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCores) DeepCopyInto(out *GPUCores) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCores.
func (in *GPUCores) DeepCopy() *GPUCores {
	if in == nil {
		return nil
	}
	out := new(GPUCores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFabric) DeepCopyInto(out *GPUFabric) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(FabricDomain)
		**out = **in
	}
	if in.Switches != nil {
		in, out := &in.Switches, &out.Switches
		*out = new(FabricSwitches)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFabric.
func (in *GPUFabric) DeepCopy() *GPUFabric {
	if in == nil {
		return nil
	}
	out := new(GPUFabric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmware) DeepCopyInto(out *GPUFirmware) {
	*out = *in
	if in.InfoROM != nil {
		in, out := &in.InfoROM, &out.InfoROM
		*out = new(InfoROM)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmware.
func (in *GPUFirmware) DeepCopy() *GPUFirmware {
	if in == nil {
		return nil
	}
	out := new(GPUFirmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMemory) DeepCopyInto(out *GPUMemory) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	if in.Reserved != nil {
		in, out := &in.Reserved, &out.Reserved
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Bar1Capacity != nil {
		in, out := &in.Bar1Capacity, &out.Bar1Capacity
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMemory.
func (in *GPUMemory) DeepCopy() *GPUMemory {
	if in == nil {
		return nil
	}
	out := new(GPUMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUModel) DeepCopyInto(out *GPUModel) {
	*out = *in
	if in.ComputeCapability != nil {
		in, out := &in.ComputeCapability, &out.ComputeCapability
		*out = new(ComputeCapability)
		**out = **in
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(GPUCores)
		**out = **in
	}
	if in.Board != nil {
		in, out := &in.Board, &out.Board
		*out = new(GPUBoard)
		**out = **in
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(GPUFirmware)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUModel.
func (in *GPUModel) DeepCopy() *GPUModel {
	if in == nil {
		return nil
	}
	out := new(GPUModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPCI) DeepCopyInto(out *GPUPCI) {
	*out = *in
	if in.MaxLink != nil {
		in, out := &in.MaxLink, &out.MaxLink
		*out = new(PCILink)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPCI.
func (in *GPUPCI) DeepCopy() *GPUPCI {
	if in == nil {
		return nil
	}
	out := new(GPUPCI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPower) DeepCopyInto(out *GPUPower) {
	*out = *in
	if in.LimitsMilliWatts != nil {
		in, out := &in.LimitsMilliWatts, &out.LimitsMilliWatts
		*out = new(PowerLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPower.
func (in *GPUPower) DeepCopy() *GPUPower {
	if in == nil {
		return nil
	}
	out := new(GPUPower)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSlot) DeepCopyInto(out *GPUSlot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSlot.
func (in *GPUSlot) DeepCopy() *GPUSlot {
	if in == nil {
		return nil
	}
	out := new(GPUSlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUThermal) DeepCopyInto(out *GPUThermal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUThermal.
func (in *GPUThermal) DeepCopy() *GPUThermal {
	if in == nil {
		return nil
	}
	out := new(GPUThermal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCPU) DeepCopyInto(out *HostCPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCPU.
func (in *HostCPU) DeepCopy() *HostCPU {
	if in == nil {
		return nil
	}
	out := new(HostCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMemory) DeepCopyInto(out *HostMemory) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMemory.
func (in *HostMemory) DeepCopy() *HostMemory {
	if in == nil {
		return nil
	}
	out := new(HostMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfoROM) DeepCopyInto(out *InfoROM) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfoROM.
func (in *InfoROM) DeepCopy() *InfoROM {
	if in == nil {
		return nil
	}
	out := new(InfoROM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryCapacity) DeepCopyInto(out *InventoryCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryCapacity.
func (in *InventoryCapacity) DeepCopy() *InventoryCapacity {
	if in == nil {
		return nil
	}
	out := new(InventoryCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryUsage) DeepCopyInto(out *InventoryUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryUsage.
func (in *InventoryUsage) DeepCopy() *InventoryUsage {
	if in == nil {
		return nil
	}
	out := new(InventoryUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MIGCapability) DeepCopyInto(out *MIGCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MIGCapability.
func (in *MIGCapability) DeepCopy() *MIGCapability {
	if in == nil {
		return nil
	}
	out := new(MIGCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTopology) DeepCopyInto(out *NetworkTopology) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTopology.
func (in *NetworkTopology) DeepCopy() *NetworkTopology {
	if in == nil {
		return nil
	}
	out := new(NetworkTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCILink) DeepCopyInto(out *PCILink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCILink.
func (in *PCILink) DeepCopy() *PCILink {
	if in == nil {
		return nil
	}
	out := new(PCILink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PercentRange) DeepCopyInto(out *PercentRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PercentRange.
func (in *PercentRange) DeepCopy() *PercentRange {
	if in == nil {
		return nil
	}
	out := new(PercentRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyTargetRef) DeepCopyInto(out *PolicyTargetRef) {
	*out = *in
	if in.RackGroups != nil {
		in, out := &in.RackGroups, &out.RackGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RackIndexes != nil {
		in, out := &in.RackIndexes, &out.RackIndexes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.NodeIndexes != nil {
		in, out := &in.NodeIndexes, &out.NodeIndexes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.GPUIndexes != nil {
		in, out := &in.GPUIndexes, &out.GPUIndexes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyTargetRef.
func (in *PolicyTargetRef) DeepCopy() *PolicyTargetRef {
	if in == nil {
		return nil
	}
	out := new(PolicyTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLimits) DeepCopyInto(out *PowerLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLimits.
func (in *PowerLimits) DeepCopy() *PowerLimits {
	if in == nil {
		return nil
	}
	out := new(PowerLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerTelemetry) DeepCopyInto(out *PowerTelemetry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerTelemetry.
func (in *PowerTelemetry) DeepCopy() *PowerTelemetry {
	if in == nil {
		return nil
	}
	out := new(PowerTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileReference) DeepCopyInto(out *ProfileReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileReference.
func (in *ProfileReference) DeepCopy() *ProfileReference {
	if in == nil {
		return nil
	}
	out := new(ProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RackGroup) DeepCopyInto(out *RackGroup) {
	*out = *in
	out.ProfileRef = in.ProfileRef
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(RackPlacement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RackGroup.
func (in *RackGroup) DeepCopy() *RackGroup {
	if in == nil {
		return nil
	}
	out := new(RackGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RackGroupStatus) DeepCopyInto(out *RackGroupStatus) {
	*out = *in
	out.Capacity = in.Capacity
	out.Usage = in.Usage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RackGroupStatus.
func (in *RackGroupStatus) DeepCopy() *RackGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RackGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RackPlacement) DeepCopyInto(out *RackPlacement) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RackPlacement.
func (in *RackPlacement) DeepCopy() *RackPlacement {
	if in == nil {
		return nil
	}
	out := new(RackPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeModes) DeepCopyInto(out *RuntimeModes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeModes.
func (in *RuntimeModes) DeepCopy() *RuntimeModes {
	if in == nil {
		return nil
	}
	out := new(RuntimeModes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeState) DeepCopyInto(out *RuntimeState) {
	*out = *in
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = new(RuntimeModes)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(RuntimeTelemetry)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeState.
func (in *RuntimeState) DeepCopy() *RuntimeState {
	if in == nil {
		return nil
	}
	out := new(RuntimeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTelemetry) DeepCopyInto(out *RuntimeTelemetry) {
	*out = *in
	if in.Utilization != nil {
		in, out := &in.Utilization, &out.Utilization
		*out = new(UtilizationTelemetry)
		(*in).DeepCopyInto(*out)
	}
	if in.Power != nil {
		in, out := &in.Power, &out.Power
		*out = new(PowerTelemetry)
		**out = **in
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(TemperatureTelemetry)
		**out = **in
	}
	if in.Clocks != nil {
		in, out := &in.Clocks, &out.Clocks
		*out = new(ClocksTelemetry)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTelemetry.
func (in *RuntimeTelemetry) DeepCopy() *RuntimeTelemetry {
	if in == nil {
		return nil
	}
	out := new(RuntimeTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUGPUs) DeepCopyInto(out *SGPUGPUs) {
	*out = *in
	in.Model.DeepCopyInto(&out.Model)
	in.Memory.DeepCopyInto(&out.Memory)
	in.PCI.DeepCopyInto(&out.PCI)
	if in.Power != nil {
		in, out := &in.Power, &out.Power
		*out = new(GPUPower)
		(*in).DeepCopyInto(*out)
	}
	if in.Thermal != nil {
		in, out := &in.Thermal, &out.Thermal
		*out = new(GPUThermal)
		**out = **in
	}
	if in.Clocks != nil {
		in, out := &in.Clocks, &out.Clocks
		*out = new(GPUClocks)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(GPUCapabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUGPUs.
func (in *SGPUGPUs) DeepCopy() *SGPUGPUs {
	if in == nil {
		return nil
	}
	out := new(SGPUGPUs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUHost) DeepCopyInto(out *SGPUHost) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(HostCPU)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(HostMemory)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUHost.
func (in *SGPUHost) DeepCopy() *SGPUHost {
	if in == nil {
		return nil
	}
	out := new(SGPUHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventory) DeepCopyInto(out *SGPUInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventory.
func (in *SGPUInventory) DeepCopy() *SGPUInventory {
	if in == nil {
		return nil
	}
	out := new(SGPUInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventoryList) DeepCopyInto(out *SGPUInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SGPUInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventoryList.
func (in *SGPUInventoryList) DeepCopy() *SGPUInventoryList {
	if in == nil {
		return nil
	}
	out := new(SGPUInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventorySpec) DeepCopyInto(out *SGPUInventorySpec) {
	*out = *in
	if in.RackGroups != nil {
		in, out := &in.RackGroups, &out.RackGroups
		*out = make([]RackGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventorySpec.
func (in *SGPUInventorySpec) DeepCopy() *SGPUInventorySpec {
	if in == nil {
		return nil
	}
	out := new(SGPUInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUInventoryStatus) DeepCopyInto(out *SGPUInventoryStatus) {
	*out = *in
	out.Capacity = in.Capacity
	out.Usage = in.Usage
	if in.RackGroups != nil {
		in, out := &in.RackGroups, &out.RackGroups
		*out = make([]RackGroupStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUInventoryStatus.
func (in *SGPUInventoryStatus) DeepCopy() *SGPUInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(SGPUInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUNode) DeepCopyInto(out *SGPUNode) {
	*out = *in
	in.GPUs.DeepCopyInto(&out.GPUs)
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(SGPUHost)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(SGPUTopology)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUNode.
func (in *SGPUNode) DeepCopy() *SGPUNode {
	if in == nil {
		return nil
	}
	out := new(SGPUNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfile) DeepCopyInto(out *SGPUProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfile.
func (in *SGPUProfile) DeepCopy() *SGPUProfile {
	if in == nil {
		return nil
	}
	out := new(SGPUProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileDefaults) DeepCopyInto(out *SGPUProfileDefaults) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileDefaults.
func (in *SGPUProfileDefaults) DeepCopy() *SGPUProfileDefaults {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileList) DeepCopyInto(out *SGPUProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SGPUProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileList.
func (in *SGPUProfileList) DeepCopy() *SGPUProfileList {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPUProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUProfileSpec) DeepCopyInto(out *SGPUProfileSpec) {
	*out = *in
	out.Rack = in.Rack
	in.Node.DeepCopyInto(&out.Node)
	if in.Software != nil {
		in, out := &in.Software, &out.Software
		*out = new(SGPUSoftware)
		**out = **in
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(SGPUProfileDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUProfileSpec.
func (in *SGPUProfileSpec) DeepCopy() *SGPUProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SGPUProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURack) DeepCopyInto(out *SGPURack) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURack.
func (in *SGPURack) DeepCopy() *SGPURack {
	if in == nil {
		return nil
	}
	out := new(SGPURack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURuntimePolicy) DeepCopyInto(out *SGPURuntimePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURuntimePolicy.
func (in *SGPURuntimePolicy) DeepCopy() *SGPURuntimePolicy {
	if in == nil {
		return nil
	}
	out := new(SGPURuntimePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPURuntimePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURuntimePolicyList) DeepCopyInto(out *SGPURuntimePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SGPURuntimePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURuntimePolicyList.
func (in *SGPURuntimePolicyList) DeepCopy() *SGPURuntimePolicyList {
	if in == nil {
		return nil
	}
	out := new(SGPURuntimePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SGPURuntimePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPURuntimePolicySpec) DeepCopyInto(out *SGPURuntimePolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPURuntimePolicySpec.
func (in *SGPURuntimePolicySpec) DeepCopy() *SGPURuntimePolicySpec {
	if in == nil {
		return nil
	}
	out := new(SGPURuntimePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUSoftware) DeepCopyInto(out *SGPUSoftware) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUSoftware.
func (in *SGPUSoftware) DeepCopy() *SGPUSoftware {
	if in == nil {
		return nil
	}
	out := new(SGPUSoftware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGPUTopology) DeepCopyInto(out *SGPUTopology) {
	*out = *in
	if in.GPUSlots != nil {
		in, out := &in.GPUSlots, &out.GPUSlots
		*out = make([]GPUSlot, len(*in))
		copy(*out, *in)
	}
	if in.GPUFabric != nil {
		in, out := &in.GPUFabric, &out.GPUFabric
		*out = new(GPUFabric)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkTopology)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGPUTopology.
func (in *SGPUTopology) DeepCopy() *SGPUTopology {
	if in == nil {
		return nil
	}
	out := new(SGPUTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportedClocks) DeepCopyInto(out *SupportedClocks) {
	*out = *in
	if in.GraphicsMHz != nil {
		in, out := &in.GraphicsMHz, &out.GraphicsMHz
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportedClocks.
func (in *SupportedClocks) DeepCopy() *SupportedClocks {
	if in == nil {
		return nil
	}
	out := new(SupportedClocks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemperatureTelemetry) DeepCopyInto(out *TemperatureTelemetry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemperatureTelemetry.
func (in *TemperatureTelemetry) DeepCopy() *TemperatureTelemetry {
	if in == nil {
		return nil
	}
	out := new(TemperatureTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UtilizationPattern) DeepCopyInto(out *UtilizationPattern) {
	*out = *in
	if in.GPUPercent != nil {
		in, out := &in.GPUPercent, &out.GPUPercent
		*out = new(PercentRange)
		**out = **in
	}
	if in.MemoryPercent != nil {
		in, out := &in.MemoryPercent, &out.MemoryPercent
		*out = new(PercentRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UtilizationPattern.
func (in *UtilizationPattern) DeepCopy() *UtilizationPattern {
	if in == nil {
		return nil
	}
	out := new(UtilizationPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UtilizationTelemetry) DeepCopyInto(out *UtilizationTelemetry) {
	*out = *in
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(UtilizationPattern)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UtilizationTelemetry.
func (in *UtilizationTelemetry) DeepCopy() *UtilizationTelemetry {
	if in == nil {
		return nil
	}
	out := new(UtilizationTelemetry)
	in.DeepCopyInto(out)
	return out
}
