kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    labels:
      run.ai/simulated-gpu-node-pool: integration
  - role: worker
    labels:
      run.ai/simulated-gpu-node-pool: scale
  - role: worker
    labels:
      run.ai/simulated-gpu-node-pool: scale
