// SPDX-License-Identifier: GPL-2.0
// Copyright 2026 NVIDIA CORPORATION
//
// Stub kernel module named "nvidia": provides real, kernel-global
// /sys/module/nvidia and /proc/driver/nvidia entries for GPU mocking on
// nodes with no NVIDIA hardware. Loading any module named "nvidia" makes the
// kernel itself create /sys/module/nvidia (refcnt, version via
// MODULE_VERSION); this stub additionally serves the /proc/driver/nvidia
// files in the NVRM format. It registers no devices, allocates nothing
// per-request, and touches no hardware -- the entire runtime surface is two
// read-only procfs files.
//
// Built and loaded at runtime by deployments/mock-driver/scripts/nvidia-driver
// when MOCK_KMOD is enabled (mirroring how the real driver container builds
// the real module); the entrypoint falls back to mount-namespace fakes when
// building or loading is not possible.

#include <linux/module.h>
#include <linux/proc_fs.h>
#include <linux/seq_file.h>

// Generated by the entrypoint before the build so the module version agrees
// with the mock NVML profile; the fallback keeps standalone builds working.
#if __has_include("stub_version.h")
#include "stub_version.h"
#endif
#ifndef STUB_DRIVER_VERSION
#define STUB_DRIVER_VERSION "550.163.01"
#endif

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("Stub nvidia module: kernel-global /proc and /sys presence for GPU mocking");
MODULE_VERSION(STUB_DRIVER_VERSION);

static struct proc_dir_entry *nv_dir;

/*
 * The version and params text must stay byte-compatible with
 * drl_write_proc_files() in deployments/nvml-mock/scripts/lib-driver-root.sh,
 * which produces the same files for the non-kmod (mount-namespace) path. Keep
 * the two in sync so /proc/driver/nvidia looks identical in either mode.
 */
static int version_show(struct seq_file *m, void *v)
{
	seq_printf(m,
		"NVRM version: NVIDIA UNIX x86_64 Kernel Module  " STUB_DRIVER_VERSION "  Thu Feb 20 23:41:34 UTC 2026\n"
		"GCC version:  gcc version 12.2.0 (Debian 12.2.0-14)\n");
	return 0;
}

static int params_show(struct seq_file *m, void *v)
{
	seq_puts(m,
		"EnableMSI: 1\n"
		"NVreg_RegistryDwords:\n"
		"NVreg_DeviceFileGID: 0\n"
		"NVreg_DeviceFileMode: 438\n"
		"NVreg_DeviceFileUID: 0\n"
		"NVreg_ModifyDeviceFiles: 1\n"
		"NVreg_PreserveVideoMemoryAllocations: 0\n"
		"NVreg_EnableResizableBar: 0\n");
	return 0;
}

static int __init nv_init(void)
{
	/*
	 * proc_mkdir("driver/nvidia") creates only the "nvidia" leaf; the
	 * "driver" parent already exists in every procfs, so remove_proc_subtree
	 * on exit takes down exactly what we created and never the shared parent.
	 */
	nv_dir = proc_mkdir("driver/nvidia", NULL);
	if (!nv_dir)
		return -ENOMEM;
	if (!proc_create_single("version", 0444, nv_dir, version_show) ||
	    !proc_create_single("params", 0444, nv_dir, params_show)) {
		remove_proc_subtree("driver/nvidia", NULL);
		return -ENOMEM;
	}
	return 0;
}

static void __exit nv_exit(void)
{
	remove_proc_subtree("driver/nvidia", NULL);
}

module_init(nv_init);
module_exit(nv_exit);
