# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: cdi-smoke
  namespace: gpu-mock
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: cdi-smoke
    spec:
      restartPolicy: Never
      volumes:
        - name: host-cdi
          hostPath:
            path: /etc/cdi
        - name: host-driver
          hostPath:
            path: /var/lib/nvidia-mock/driver
      containers:
        - name: check
          image: debian:bookworm-slim
          volumeMounts:
            - name: host-cdi
              mountPath: /host/etc/cdi
              readOnly: true
            - name: host-driver
              mountPath: /host/var/lib/nvidia-mock/driver
              readOnly: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -ex
              
              # Check CDI spec exists
              test -s /host/etc/cdi/nvidia.yaml
              echo "✓ CDI spec exists"
              
              # Check mock driver libraries
              test -f /host/var/lib/nvidia-mock/driver/lib64/libcuda.so.1
              test -L /host/var/lib/nvidia-mock/driver/lib64/libcuda.so
              test -f /host/var/lib/nvidia-mock/driver/lib64/libnvidia-ml.so.1
              test -L /host/var/lib/nvidia-mock/driver/lib64/libnvidia-ml.so
              echo "✓ Mock driver libraries present"
              
              # Check binaries
              test -x /host/var/lib/nvidia-mock/driver/bin/nvidia-smi
              echo "✓ Mock binaries present"
              
              # Show tree
              echo "Mock driver tree:"
              find /host/var/lib/nvidia-mock/driver -type f -o -type l | sort | head -20
              
              # Show CDI spec snippet
              echo ""
              echo "CDI spec (first 30 lines):"
              head -30 /host/etc/cdi/nvidia.yaml
              
              echo ""
              echo "✓ CDI smoke test PASSED"

